---
ID: "a2d4df09-3782-48a1-b150-61080ee67ecd"
Parent: "549b0ab9-47c0-4484-bc39-93f3d2880d74"
Template: "549b0ab9-47c0-4484-bc39-93f3d2880d74"
Path: /sitecore/templates/Feature/PageContent/Merchandising Banner Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{1C4F1B82-90B3-4BCA-A852-CC8A42F07D68}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200807T143638Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
