//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace easyJet.Holidays.External.Atcom.Models.Internal
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/CancellationRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/CancellationRequest", IsNullable = false)]
    public partial class CancellationRequest : AtcomresBaseRequest
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BkgNum", Namespace = "AtComRes/Common")]
        public BkgNum[] BkgNum;

        /// <remarks/>
        public bool Cnx_Without_Fee;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cnx_Without_FeeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Memo", Namespace = "AtComRes/Common")]
        public Memo[] Memo;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string Amd_MktCd;
    }
}