import { mockSitecoreField, mockSitecoreImageField } from 'frontend/utils/tests.utils';
import {
    IItinerarySummarySummaryFields,
    IItineraryTransferFields,
    ITransferInstructionsPopupFields,
} from 'frontend/components/renderings/ItinerarySummary/interfaces';

const instructionPopupFieldsMocks: ITransferInstructionsPopupFields = {
    MapLocationButtonLabel: mockSitecoreField('MapLocationButtonLabel'),
    MapLocationDescription: mockSitecoreField('MapLocationDescription'),
    AppleMapLocationButtonLabel: mockSitecoreField('AppleMapLocationButtonLabel'),
    GoogleMapLocationButtonLabel: mockSitecoreField('GoogleMapLocationButtonLabel'),
    ThreeWordsLocationButtonLabel: mockSitecoreField('ThreeWordsLocationButtonLabel'),
    ThreeWordsLocationDescription: mockSitecoreField('ThreeWordsLocationDescription'),
    InstructionsSubtitle: mockSitecoreField('InstructionsSubtitle'),
    LocationsTitle: mockSitecoreField('LocationsTitle'),
    AdditionalInstructions: mockSitecoreField('AdditionalInstructions'),
};

const itineraryTransferFieldsMocks: IItineraryTransferFields = {
    AllowTimeDescription: mockSitecoreField('Allow time desc'),
    AllowTimeTitle: mockSitecoreField('Allow time'),
    ArriveEarlierPickupText: mockSitecoreField('Arrive early'),
    ArriveEarlierPrivateText: mockSitecoreField('Private early'),
    ArriveEarlierSharedText: mockSitecoreField('Shared early'),
    DiffPickupLocationText: mockSitecoreField('Different location'),
    DriverNameLabel: mockSitecoreField('Driver name'),
    DriverNumberLabel: mockSitecoreField('Driver number'),
    DurationLabel: mockSitecoreField('Duration'),
    DurationText: mockSitecoreField('Approx {duration}'),
    ErrorLoadingTransferText: mockSitecoreField('Error loading transfer'),
    ExpandAllLabel: mockSitecoreField('Expand'),
    FlightDelayDescription: mockSitecoreField('Flight delay desc'),
    FlightDelayTitle: mockSitecoreField('Flight delay'),
    NoPickUpTimeText: mockSitecoreField('No pickup time yet'),
    NoTransferDescription: mockSitecoreField('You chose to make your own way'),
    NoTransferTitle: mockSitecoreField('No transfer title'),
    PickupInstructionsAndHelpLabel: mockSitecoreField('Pickup instructions & help'),
    PickupInstructionsLabel: mockSitecoreField('Instructions label'),
    PickupInstructionsText: mockSitecoreField('Instructions text'),
    PickupLocationLabel: mockSitecoreField('Pickup location'),
    PickupTimeFullText: mockSitecoreField('Full time {time}'),
    PickupTimeLabel: mockSitecoreField('Pickup time'),
    PickupTimeShortText: mockSitecoreField('Short {time}'),
    SameLocationText: mockSitecoreField('Same location'),
    SharedStandardBusText: mockSitecoreField('Standard bus {provider}'),
    SharedTransfer: mockSitecoreField('Shared transfer'),
    PrivateTransfer: mockSitecoreField('Private transfer'),
    TimeMayVaryText: mockSitecoreField('Time may vary'),
    ToAirportLabel: mockSitecoreField('to airport'),
    ToHotelLabel: mockSitecoreField('to hotel'),
    VehicleLabel: mockSitecoreField('Vehicle'),
    VehicleRegistrationLabel: mockSitecoreField('Registration'),
    HoursToGrayOut: mockSitecoreField(24),
    SubjectToChangeText: mockSitecoreField('Subject to change'),
    PrivateTransferProviderText: mockSitecoreField('Private transfer {provider}'),
    ...instructionPopupFieldsMocks,
};

const itinerarySummaryFieldsMocks: IItinerarySummarySummaryFields = {
    ExpandAllButton: mockSitecoreField('Expand all'),
    CloseAllButton: mockSitecoreField('Close all'),
    AddressLabel: mockSitecoreField('addressLabel'),
    ArrivesLabel: mockSitecoreField('arrivesLabel'),
    DepartsLabel: mockSitecoreField('departLabel'),
    DirectionsLabel: mockSitecoreField('directionsLabel'),
    FlightInbound: mockSitecoreField('flightInbound'),
    FlightOutbound: mockSitecoreField('flightOutbound'),
    HideFullItineraryLabel: mockSitecoreField('hideFull'),
    HotelDetailsLabel: mockSitecoreField('hotelDetails'),
    HotelTitle: mockSitecoreField('hotelTitle'),
    ItineraryTitle: mockSitecoreField('itineraryTitle'),
    RoomsLabelPlural: mockSitecoreField('Rooms:'),
    RoomsLabelSingular: mockSitecoreField('Your room:'),
    TransferTitle: mockSitecoreField('transferTitle'),
    ViewFullItineraryLabel: mockSitecoreField('viewFullItinerary'),
    CloseDrawerLabel: mockSitecoreField('closeDrawer'),
    GoogleMapsLabel: mockSitecoreField('Google Maps'),
    AppleMapsLabel: mockSitecoreField('Apple Maps'),
    MapsApplicationLabel: mockSitecoreField('Which application would you like to use?'),
    AirportTitle: mockSitecoreField('AirportTitle'),
    ArriveByLabel: mockSitecoreField('ArriveByLabel'),
    ArriveByText: mockSitecoreField('ArriveByText'),
    FastTrackIcon: mockSitecoreField(mockSitecoreImageField('FastTrackIcon')),
    FastTrackLabel: mockSitecoreField('FastTrackLabel'),
    FastTrackText: mockSitecoreField('FastTrackText'),
    SpeedyBoardingIcon: mockSitecoreField(mockSitecoreImageField('SpeedyBoardingIcon')),
    SpeedyBoardingLabel: mockSitecoreField('SpeedyBoardingLabel'),
    SpeedyBoardingText: mockSitecoreField('SpeedyBoardingText'),
    SpeedyBoardingTooltip: mockSitecoreField('SpeedyBoardingTooltip'),
    ...itineraryTransferFieldsMocks,
};

export default itinerarySummaryFieldsMocks;
