//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace easyJet.Holidays.External.Atcom.Models.Internal
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/DisplayResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/DisplayResponse", IsNullable = false)]
    public partial class DisplayResponse : AtcomresBookingBaseResponse
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DisplayOnly;

        /// <remarks/>
        public Amendments Amendments;

        public DisplayResponse()
        {
            this.DisplayOnly = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/DisplayResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/DisplayResponse", IsNullable = false)]
    public partial class Amendments
    {
        /// <remarks/>
        public Amend_Rights Bkg;

        /// <remarks/>
        public Amend_Rights Route;

        /// <remarks/>
        public Amend_Rights Accom;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public Amend_Item[] Items;

        /// <remarks/>
        public Amend_Rights Flight_Extra;

        /// <remarks/>
        public Amend_Rights Car_Rental;

        /// <remarks/>
        public Amend_Rights Cruise;

        /// <remarks/>
        public Amend_Rights Pax;

        /// <remarks/>
        public Amend_Rights Memo;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AtComRes/DisplayResponse")]
    public partial class Amend_Rights
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Add;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Amend;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Cancel;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Amend_Name_Only;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AtComRes/DisplayResponse")]
    public partial class Amend_Item
    {
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Amend_Item_Type Item_Type;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Add;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Amend;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Cancel;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Downgrade_Allow;
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/Common")]
    public enum Amend_Item_Type
    {
        EXT,
        TRF,  //Transfer
    }
}
