---
ID: "47f8c41b-478f-4a14-9ef6-a61a690a72de"
Parent: "076c2ca2-b619-4387-84a1-481dc964cdfa"
Template: "076c2ca2-b619-4387-84a1-481dc964cdfa"
Path: /sitecore/templates/Foundation/Presentation/Base/_Base Composed Title/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230710T113320Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
