---
ID: "ad9c1367-7723-4072-b468-be700118ec13"
Parent: "74a99c09-cebb-4cfc-9a61-45e26fdf7412"
Template: "74a99c09-cebb-4cfc-9a61-45e26fdf7412"
Path: /sitecore/templates/Feature/Destinations/Comparison/Settings/Compare Deals/__Standard Values
DB: master
SharedFields:
- ID: "9d438f21-2e31-49ec-b4ff-a27cb4d19f6b"
  Hint: IsCompareDealsEnabledOnSearchResultsPage
  Type: Checkbox
  Value: 1
- ID: "a63b5994-28be-4b3e-859a-07440d66bdda"
  Hint: MaxCompareItemCount
  Value: 3
- ID: "e8dd853d-eff5-4022-9592-5164e7e87955"
  Hint: MinCompareItemCount
  Value: 2
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251112T143407Z
