---
ID: "bbe57b53-0740-4551-aaeb-d6cef60760f5"
Parent: "1bfa4442-2f24-4720-9d1f-6823ce43769a"
Template: "1bfa4442-2f24-4720-9d1f-6823ce43769a"
Path: /sitecore/templates/Foundation/Destinations/Reports/Room Name Upload Report/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210113T120124Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
