---
ID: "ffd68d94-c301-4ac8-9e05-56ecead30e78"
Parent: "efeb331a-38b4-4deb-8c76-a828134349ca"
Template: "efeb331a-38b4-4deb-8c76-a828134349ca"
Path: /sitecore/templates/Project/Holidays/Site Settings/Other Routes Settings/__Standard Values
DB: master
SharedFields:
- ID: "405f42ea-b0a5-4efc-9a6d-be0b2f91c1fb"
  Hint: IsEnabled
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201124T133245Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
