---
ID: "5c22cd73-9fb4-4875-9882-5b46fa0e8831"
Parent: "3b1c3399-8610-40ee-a397-f2a639eff262"
Template: "3b1c3399-8610-40ee-a397-f2a639eff262"
Path: /sitecore/templates/Foundation/SiteModes/Maintenance Mode Per Market Setting/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221102T135339Z
