---
ID: "2a2d87e4-dd20-48e2-a765-4ba7cc09dce7"
Parent: "f5b19227-440f-49a9-a6f0-308c8e17fa10"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Destinations/Live Price/Live Price Settings/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200803T104101Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
