---
ID: "319f455a-738a-44e6-9b78-637f2d88c7e5"
Parent: "f767a94f-b34e-4762-9426-08c1a3a81405"
Template: "f767a94f-b34e-4762-9426-08c1a3a81405"
Path: /sitecore/templates/Feature/PageContent/Weather Data Carousel/__Standard Values
DB: master
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "23cb232e-bade-4033-afee-b1241b6b0e22"
      Hint: Title
      Value: "Durchschnittswetter in {region}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240216T094828Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "23cb232e-bade-4033-afee-b1241b6b0e22"
      Hint: Title
      Value: "Durchschnittswetter in {region}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240216T094909Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "23cb232e-bade-4033-afee-b1241b6b0e22"
      Hint: Title
      Value: "Average weather in {region}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240207T161735Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: "fr-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "23cb232e-bade-4033-afee-b1241b6b0e22"
      Hint: Title
      Value: "Météo moyenne dans {region}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240216T094604Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "23cb232e-bade-4033-afee-b1241b6b0e22"
      Hint: Title
      Value: "Météo moyenne dans {region}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240216T094649Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
