<Project>
    <ItemGroup>
        <!-- Microsoft -->
        <PackageReference Update="System.Memory" Version="4.5.5" />
        <PackageReference Update="System.Data.SqlClient" Version="4.8.6" />
        <PackageReference Update="System.Buffers" Version="4.5.1"/>
        <PackageReference Update="System.ValueTuple" Version="4.5.0" />
        <PackageReference Update="System.Linq.Async" Version="4.0.0" />
        <PackageReference Update="System.Numerics.Vectors" Version="4.5.0" />
        <PackageReference Update="System.Threading.Tasks.Dataflow" Version="6.0.0" />
        <PackageReference Update="System.Text.Encodings.Web" Version="8.0.0" />
        <PackageReference Update="System.Text.Json" Version="8.0.6" />
        <PackageReference Update="System.Linq.Async.Queryable" Version="4.0.0" />
        <PackageReference Update="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
        <PackageReference Update="System.Collections.Immutable" Version="1.7.1" />
        <PackageReference Update="Microsoft.Extensions.Logging" Version="7.0.0" />
        <PackageReference Update="Microsoft.AspNet.Mvc" version="5.2.4" />
        <PackageReference Update="Microsoft.AspNet.Razor" version="3.2.4" />
        <PackageReference Update="Microsoft.AspNet.WebApi" Version="5.2.6" />
        <PackageReference Update="Microsoft.AspNet.WebPages" Version="3.2.4" />
        <PackageReference Update="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
        <PackageReference Update="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="2.0.1" />
        <PackageReference Update="Microsoft.CSharp" Version="4.4.1" />
        <PackageReference Update="Microsoft.Net.Compilers" version="2.1.0" developmentDependency="true" />
        <PackageReference Update="Microsoft.Web.Infrastructure" version="1.0.0" />
        <PackageReference Update="Microsoft.Extensions.DependencyInjection.Abstractions" version="7.0.0" />
        <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" version="7.0.0" />
        <PackageReference Update="Microsoft.IdentityModel.JsonWebTokens" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Logging" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Tokens" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Tokens.Saml" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Xml" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Protocols" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.7.0" />
        <PackageReference Update="Microsoft.IdentityModel.Protocols.WsFederation" version="5.7.0" />
        <PackageReference Update="System.IdentityModel.Tokens.Jwt" version="5.7.0" />
        <PackageReference Update="EnterpriseLibrary.Common" version="6.0.1304" />
        <PackageReference Update="EntityFramework" Version="6.4.4"/>
        <PackageReference Update="Microsoft.Owin" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Host.SystemWeb" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Security.ActiveDirectory" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Security.Cookies" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Security" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Security.Jwt" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Security.OAuth" Version="4.2.2"/>
        <PackageReference Update="Microsoft.Owin.Security.OpenIdConnect" Version="4.2.2"/>
        <PackageReference Update="System.Security.AccessControl" Version="6.0.0"/>
        <PackageReference Update="System.Security.Cryptography.Xml" Version="6.0.1"/>
        <PackageReference Update="System.Security.Permissions" Version="4.5.0"/>
        <PackageReference Update="System.Security.Principal.Windows" Version="5.0.0"/>
        <PackageReference Update="System.Interactive.Async.Providers" Version="4.0.0" />
        
        <!-- Sitecore -->
        <PackageReference Update="Sitecore.Analytics" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Analytics.Core" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Analytics.Model" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Analytics.XConnect" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Buckets" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.CES" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.CES.GeoIp" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.CES.GeoIp.Core" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.CES.GeoIp.IpFiltering" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Cintel" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Cintel.Client" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Client" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentSearch" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentSearch.Data" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentSearch.Linq" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentSearch.ContentExtraction" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentSearch.SolrProvider" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentTesting" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentTesting.Model" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ExperienceEditor" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Kernel" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Logging" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Logging.Client" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Mvc" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Marketing" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Marketing.Core" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Marketing.Taxonomy" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Services.Infrastructure" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Personalization.Mvc" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.Xdb.MarketingAutomation.Core" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Client" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Client.Configuration" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Collection.Model" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Core" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.DataTools.Abstractions" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Diagnostics" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Segmentation.Predicates" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Segmentation.Predicates.Model" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.XConnect.Service" Version="$(SitecoreVersion)" />
        <PackageReference Update="Sitecore.ContentSearch.SolrNetExtension" Version="$(SitecoreVersion)" />
        
        <!-- Sitecore Publishing Service -->
        <PackageReference Update="Sitecore.Publishing.Service" Version="12.0.5" />
        <PackageReference Update="Sitecore.Publishing.Service.Client.Http" Version="12.0.5" />

        <!-- Sitecore JSS-->
        <PackageReference Update="Sitecore.JavaScriptServices.Configuration" Version="$(SitecoreJSSVersion)" />
        <PackageReference Update="Sitecore.JavaScriptServices.Media" Version="$(SitecoreJSSVersion)" />
        
        <PackageReference Update="Sitecore.Framework.Conditions" Version="6.0.0" />
        <PackageReference Update="Sitecore.Framework.Data.Blobs.Abstractions" Version="3.0.1" />
        <PackageReference Update="Sitecore.Framework.Configuration.Extensions" Version="7.0.0" />
        <PackageReference Update="Sitecore.Framework.Rules" Version="6.0.0" />
        <PackageReference Update="Sitecore.Framework.Rules.Abstractions" Version="6.0.0" />

        <PackageReference Update="Sitecore.Nexus" Version="10.1.3" />
        <PackageReference Update="Sitecore.Nexus.Licensing" Version="2.0.6" />
        <PackageReference Update="Sitecore.Nexus.Consumption" Version="1.4.2" />

        <!-- Sitecore currently overriden by hotfix dll in libs folder -->
        <!--
        <PackageReference Update="Sitecore.JavaScriptServices.Tracker" Version="$(SitecoreJSSVersion)" />
        <PackageReference Update="Sitecore.JavaScriptServices.ViewEngine" Version="$(SitecoreJSSVersion)" />
        <PackageReference Update="Sitecore.LayoutService" Version="10.0.6" />
        <PackageReference Update="Sitecore.LayoutService.Mvc" Version="10.0.6" />
        <PackageReference Update="Sitecore.LayoutService.GraphQL" Version="10.0.6" />
        -->

        <!-- External -->
        <PackageReference Update="Scriban" Version="5.10.0" />
        <PackageReference Update="StyleCop.Analyzers" Version="1.1.118" />
        <PackageReference Update="Microsoft.VisualStudio.SlowCheetah" Version="4.0.50" />
        <PackageReference Update="Voucherify" Version="7.0.0" />
        <PackageReference Update="FluentValidation" Version="11.4.0" />
        <PackageReference Update="SSH.NET" Version="2020.0.1" />
        <PackageReference Update="Configy" Version="1.0.0" />
        <PackageReference Update="Kamsar.WebConsole" Version="2.0.1" />
        <PackageReference Update="MicroCHAP" Version="1.2.2.2" />
        <PackageReference Update="CsvHelper" Version="12.3.2" />
        <PackageReference Update="ImageResizer" Version="4.2.8" />
        <PackageReference Update="Schema.NET" Version="10.0.0" />
        <PackageReference Update="HtmlAgilityPack" Version="1.4.9.5" />
        <PackageReference Update="SharpZipLib" Version="1.4.2" />
        <PackageReference Update="SolrNet.Core" Version="1.0.19" />
        <PackageReference Update="Polly" Version="6.1.2" />

        <!-- Newtonsoft -->
        <PackageReference Update="Newtonsoft.Json" Version="13.0.2" />

        <!-- Dianoga -->
        <PackageReference Update="Dianoga" Version="6.1.0" />
        <PackageReference Update="Dianoga.ImageMagick" Version="1.2.4" />
        <PackageReference Update="Dianoga.svgtools" Version="5.4.1" />

        <!-- AWS -->
        <PackageReference Update="AWSSDK.Core" Version="4.0.6.1" />
        <PackageReference Update="AWSSDK.S3" Version="4.0.23" />
        <PackageReference Update="AWSSDK.DynamoDBv2" Version="4.0.18.1" />
        <PackageReference Update="AWSSDK.SecretsManager" Version="4.0.4.20" />
        <PackageReference Update="AWSSDK.SQS" Version="4.0.2.28" />
        <PackageReference Update="AWSSDK.SecurityToken" Version="4.0.6.3" />

        <!-- Unicorn -->
        <PackageReference Update="Castle.Core" Version="4.4.0" />
        <PackageReference Update="Rainbow" Version="2.1.4" />
        <PackageReference Update="Rainbow.Core" Version="2.1.4" />
        <PackageReference Update="Rainbow.Storage.Sc" Version="2.1.4" />
        <PackageReference Update="Rainbow.Storage.Yaml" Version="2.1.4" />
        <PackageReference Update="Unicorn" Version="4.1.6" />
        <PackageReference Update="Unicorn.Core" Version="4.1.6" />
        <PackageReference Update="Unicorn.Roles" Version="4.1.6" />
        <PackageReference Update="Unicorn.Roles.Core" Version="4.1.6" />

        <!-- Testing -->
        <PackageReference Update="AutoFixture" Version="4.17.0" />
        <PackageReference Update="AutoFixture.Xunit2" Version="4.17.0" />
        <PackageReference Update="AutoFixture.AutoNSubstitute" Version="4.17.0" />
        <PackageReference Update="FluentAssertions" Version="5.7.0" />
        <PackageReference Update="NSubstitute" Version="4.2.2" />
        <PackageReference Update="NSubstitute.Analyzers.CSharp" Version="1.0.16"/>
        <PackageReference Update="Sitecore.NSubstituteUtils" Version="2.0.2" />
        <PackageReference Update="Sitecore.FakeDb" Version="3.0.0-alpha1" />
        <PackageReference Update="Sitecore.FakeDb.AutoFixture" Version="3.0.0-alpha1" />
        <PackageReference Update="RichardSzalay.MockHttp" Version="7.0.0" />
        <PackageReference Update="xunit" Version="2.4.1" />
        <PackageReference Update="xunit.abstractions" Version="2.0.3" />
        <PackageReference Update="xunit.analyzers" Version="0.10.0" />
        <PackageReference Update="xunit.assert" Version="2.4.1" />
        <PackageReference Update="xunit.core" Version="2.4.1" />
        <PackageReference Update="xunit.extensibility.core" Version="2.4.1" />
        <PackageReference Update="xunit.extensibility.execution" Version="2.4.1" />
        <PackageReference Update="xunit.runner.visualstudio" Version="2.4.1" />
        <PackageReference Update="coverlet.collector" Version="6.0.4" />
        <PackageReference Update="coverlet.msbuild" Version="6.0.0" />

        <!-- Powershell -->
        <PackageReference Update="Spe" Version="7.0.0" />
        <PackageReference Update="Spe.Abstractions" Version="7.0.0" />

        <!-- Optimizely -->
        <PackageReference Update="Optimizely.SDK" Version="4.1.0" />
    </ItemGroup>
</Project>