---
ID: "fd4ecfef-5669-4809-9186-443fc9c103c0"
Parent: "22f4da75-1f74-47db-9e5b-93b71f12663c"
Template: "22f4da75-1f74-47db-9e5b-93b71f12663c"
Path: /sitecore/templates/Feature/Destinations/Dynamic Promo Page/Destination Datasource Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{5A207E2B-5C45-4235-8A11-A53F88DA6840}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231107T031923Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
