---
ID: "86ee05e5-6582-4d6c-87e1-7c13a4406585"
Parent: "2b3e79fb-a982-417b-ae47-8754e986d3de"
Template: "2b3e79fb-a982-417b-ae47-8754e986d3de"
Path: /sitecore/templates/Project/Trade Portal/Pages/Hotel Details Page/__Standard Values
DB: master
SharedFields:
- ID: "37cef6a9-6298-4f19-812f-1176d2a6a39a"
  Hint: ChangeFrequency
  Value: "{BF310BAC-6A31-4366-85B9-5A173937EEDD}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4696E3CC-7DA0-4264-BF00-B6E49C11B857}">
        <r
          ds=""
          id="{CFDDA56D-9D28-45DE-BED6-FF67AC4C38B5}"
          par="ForceReloadChildren"
          ph="/header"
          uid="{1B7389EC-57FF-43DB-BF57-6594FA778E20}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{216FE85C-936E-4135-894B-E7DE8BF8A4C2}"
          par="AlternativeView=Back%20To%20Search%20View&amp;IsSticky&amp;ShowTitle&amp;RedirectToSearchResults=1&amp;ForceReloadChildren"
          ph="/header"
          uid="{3E982AE0-27C1-47B3-B2C2-FA55E666DAB5}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{F3BEFB97-4213-4C6B-9336-9FC2C2A3624B}"
          par="IsNextButtonHidden&amp;ForceReloadChildren"
          ph="header"
          uid="{B961D261-F34D-4FF9-8651-06AA3457E892}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsFullWidth&amp;IgnoreValidation&amp;IsGreyBackground=1&amp;IsTriangleStart&amp;IsTriangleEnd=1&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom"
          ph="body"
          uid="{C6FD7B30-86A0-416D-822C-B64B2E95074F}" />
        <r
          ds=""
          id="{D8BDDC7F-CDA2-4CB6-B1DE-1FB62C0426F0}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{c6fd7b30-86a0-416d-822c-b64b2e95074f}-0"
          uid="{D81D4155-A18F-415C-8B78-A53B1AAD5C74}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{55EC56AC-9658-4575-8D0E-0C20BE4B3135}"
          par="reviewsAnchor=reviews&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{c6fd7b30-86a0-416d-822c-b64b2e95074f}-0/hotel-image-sidebar-{d81d4155-a18f-415c-8b78-a53b1aad5c74}-0"
          uid="{27EA1F90-1983-4AC8-9251-73C2C0627CC2}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{705184BB-B790-4EF3-8DF8-C49FB1D9E89C}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{c6fd7b30-86a0-416d-822c-b64b2e95074f}-0"
          uid="{AD616063-F94E-4F61-BAAE-25530489BB09}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{8FC67B08-BA02-4D1C-B5A2-BC0CA048E3C2}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{c6fd7b30-86a0-416d-822c-b64b2e95074f}-0/hotel-image-sidebar-{d81d4155-a18f-415c-8b78-a53b1aad5c74}-0/share-holiday-button-{27EA1F90-1983-4AC8-9251-73C2C0627CC2}-0"
          uid="{F739ECC3-9DE0-46AB-96C1-144EF1A0959A}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{D43D1B92-A2CD-4F51-920B-4BDB7066B9CD}"
          par="ForceReloadChildren"
          ph="body"
          uid="{FFA9631E-BE3F-4B07-816E-F19D0501AC9E}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky"
          ph="body"
          uid="{5755A37A-907A-4126-BF29-5BDF4FBA241D}" />
        <r
          ds=""
          id="{CB029F29-F813-4455-BBFC-0DEBC0F8478B}"
          par="Anchor=hotel-info&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{5755a37a-907a-4126-bf29-5bdf4fba241d}-0"
          uid="{98342CB2-D093-4FF1-8255-1CA2DFE2C3F1}"
          ccb="Clear on publish" />
        <r
          ds="{DEA68433-8646-449E-9030-3025FCE98B52}"
          id="{8B4B958A-7F3C-4404-9003-DE7F4CC3AABF}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{5755a37a-907a-4126-bf29-5bdf4fba241d}-0/eco-certified-{98342cb2-d093-4ff1-8255-1ca2dfe2c3f1}-0"
          uid="{BBB3E357-17D7-4937-B8EA-F894F7961E09}"
          ccb="Clear on publish" />
        <r
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          ph="body"
          uid="{45570846-28E8-4441-8675-536959FE352D}" />
        <r
          ds=""
          id="{ECB6DA05-21A2-490B-80CD-439A652F8EF3}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{45570846-28e8-4441-8675-536959fe352d}-0"
          uid="{7CE4FFD4-FD19-4D4E-B9CC-542FECEDBADF}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsFullWidth=1"
          ph="body"
          uid="{947690A8-F593-46F3-BEA4-34CFD1A7A968}" />
        <r
          ds=""
          id="{40F87A5B-8104-4E37-9EF1-6710BDF90C36}"
          par="CentralLatitude&amp;InitialZoom&amp;CentralLongitude&amp;MinZoom=7&amp;MaxZoom&amp;Zoom=13&amp;ZoomControl=1&amp;ExpandedControl&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{947690a8-f593-46f3-bea4-34cfd1a7a968}-0"
          uid="{8BB30986-13FA-42EC-B06F-A8FE20D8ACE2}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="body"
          uid="{FF6AFFDC-0EEC-4AAD-B5AE-85781E29BFC7}"
          ccb="Clear on publish" />
        <r
          ds="{C8471136-D1C4-4722-A6FD-83C92E6F9513}"
          id="{43644156-B07A-48D9-80B8-9DF3B9AD6517}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{FF6AFFDC-0EEC-4AAD-B5AE-85781E29BFC7}-0"
          uid="{353EDB94-53DF-434B-B69C-1CED80EF3F73}"
          ccb="Clear on publish" />
        <r
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          ph="/body"
          uid="{684F9515-B2C3-4F19-BDC9-FA62FA20858E}" />
        <r
          cnd=""
          ds="/sitecore/content/EasyJet/TradePortal/Data/Weather Data Carousel"
          id="{48F21C15-5DD1-419D-9BF3-A07C2EAA0843}"
          mvt=""
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{684F9515-B2C3-4F19-BDC9-FA62FA20858E}-0"
          uid="{59E474AC-DC57-459D-8EA9-6D95AE8237E5}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsTriangleStart=1&amp;IsTriangleEnd=1&amp;IsGreyBackground=1"
          ph="body"
          uid="{E890F86D-1EC7-485D-9A88-50108B2470CA}" />
        <r
          ds=""
          id="{5F21DED9-4FB3-4407-8F58-F779D18B142F}"
          par="Anchor=board-types&amp;IsExpanded=1&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{e890f86d-1ec7-485d-9a88-50108b2470ca}-0"
          uid="{516952FD-CBFC-4CA5-BE2F-B763D664B68B}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{A07E8AAB-47FD-436E-9BA7-39086751D37B}"
          par="Anchor=room-types"
          ph="/body/component-wrapper-inner-{e890f86d-1ec7-485d-9a88-50108b2470ca}-0"
          uid="{660910E7-22C5-46F6-9325-27E0D735D474}"
          ccb="Clear on publish" />
        <r
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          ph="body"
          uid="{AB1BE6B9-76F4-453C-B0B4-D43928DABE31}" />
        <r
          ds=""
          id="{B37F9DEA-D7C1-4D09-9344-D2FFE1A590AF}"
          par="Anchor=flights&amp;IsExpanded=1&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{ab1be6b9-76f4-453c-b0b4-d43928dabe31}-0"
          uid="{6B9A51A9-2975-475D-B6C1-903B34C22583}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{85A40B2A-26E6-421E-ABB6-371817447E89}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{ab1be6b9-76f4-453c-b0b4-d43928dabe31}-0/price-graph-{6B9A51A9-2975-475D-B6C1-903B34C22583}-0"
          uid="{DB3DA866-4C20-49F1-8F41-20BE6D7AE303}"
          ccb="Clear on publish" />
        <r
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="?IsTriangleStart=0&amp;IsTriangleEnd=0&amp;IsGreyBackground=0"
          ph="body"
          uid="{6AC3D725-D25D-441C-8478-24C99623555E}" />
        <r
          ds=""
          id="{46B05525-D600-40B9-ACD9-F32B3DA08D78}"
          par="Anchor=reviews&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{6AC3D725-D25D-441C-8478-24C99623555E}-0"
          uid="{CA319593-EB56-4D61-89B0-0E14AD5C3B7F}"
          ccb="Clear on publish" />
        <r
          id="{37E88C36-C5AC-46BF-ABA7-F83606E493B3}"
          ph="body"
          uid="{FB08335E-2863-4034-BC3B-0D9EE2FB48FC}" />
        <r
          ds="{BECA3EE7-5D7C-4F93-936C-9A2D1CE22924}"
          id="{92561376-9A31-490C-8876-AF753D8CF335}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{c6fd7b30-86a0-416d-822c-b64b2e95074f}-0/hotel-image-sidebar-{d81d4155-a18f-415c-8b78-a53b1aad5c74}-0/listed-items-{27EA1F90-1983-4AC8-9251-73C2C0627CC2}-0"
          uid="{C2B51AB7-D0B1-4B92-93A2-41CE96A5A3EE}"
          ccb="Clear on publish" />
        <r
          ds="{C1E2C961-66BF-4A63-9520-F52AE7DB1168}"
          id="{F643A7DF-CCC5-4125-B857-54ADFAA1C579}"
          par="PaddingSize&amp;DisableLazyLoading&amp;TitleTag&amp;TitlePosition&amp;TitleFontStyle&amp;TitleFontSize&amp;TitleWeight&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{5755a37a-907a-4126-bf29-5bdf4fba241d}-0/tiles-carousel-{98342cb2-d093-4ff1-8255-1ca2dfe2c3f1}-0"
          uid="{B12B9260-FC54-4444-BED7-B969F42DC5F6}"
          ccb="Clear on publish" />
        <r
          ds="{C3937F2A-EC37-4ABA-B658-8A3905C19F93}"
          id="{F643A7DF-CCC5-4125-B857-54ADFAA1C579}"
          par="PaddingSize&amp;DisableLazyLoading&amp;TitleTag&amp;TitlePosition&amp;TitleFontStyle&amp;TitleFontSize&amp;TitleWeight&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{5755a37a-907a-4126-bf29-5bdf4fba241d}-0/tiles-carousel-{98342cb2-d093-4ff1-8255-1ca2dfe2c3f1}-0"
          uid="{E99AC848-CE8C-4568-A4E8-AB3BDCD12113}"
          ccb="Clear on publish" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190708T093031Z
