---
ID: "638b9e0b-849f-428f-8dcd-5ff6c2186132"
Parent: "41831d30-a4bd-4ad0-b5f2-a3d0a6f7828a"
Template: "41831d30-a4bd-4ad0-b5f2-a3d0a6f7828a"
Path: /sitecore/templates/Project/Holidays/Pages/Destinations/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {5F03C6EF-EF52-4F2E-BC5A-B1F065A1E745}
    {3BB7CB0A-8F57-48D6-9602-30A6198720D0}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4696E3CC-7DA0-4264-BF00-B6E49C11B857}">
        <r
          ds="{43379DA2-1D47-412C-B527-3889F16BF4B3}"
          id="{CFDDA56D-9D28-45DE-BED6-FF67AC4C38B5}"
          par=""
          ph="/header"
          uid="{EDF900E0-28A4-47D2-A9FA-D01F1E1D353D}" />
        <r
          ds=""
          id="{216FE85C-936E-4135-894B-E7DE8BF8A4C2}"
          par="AlternativeView&amp;IsSticky&amp;ShowTitle&amp;RedirectToSearchResults"
          ph="/header"
          uid="{6DF2E267-F6E3-4116-9D2B-55F09BF3AC40}" />
        <r
          ds=""
          id="{8697E1B1-A31B-4641-B6F9-0DBC289C5B59}"
          par="TextOrder&amp;IsTriangleGrey&amp;IsTriangleStart=1&amp;ShowImageGradient=1&amp;Height&amp;FontSize=40&amp;Variant=Grey%20Small%20Centeted%20Text%20Banner"
          ph="body"
          uid="{34E7A2B6-0463-4BB3-A1E2-54BD890ACEE5}" />
        <r
          ds=""
          id="{94A6DA9E-F932-46DE-B745-1665F7C51156}"
          par=""
          ph="/body/hero-banner-top-section-{34e7a2b6-0463-4bb3-a1e2-54bd890acee5}-0"
          uid="{D2CB04EC-13E8-499E-8D7E-D3F1F16FC600}" />
        <r
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          ph="body"
          uid="{EA7EF5D0-AAD7-431B-AE2E-921B56B9DF8B}" />
        <r
          ds="{83C5C952-9286-489A-A351-77883CAF5F47}"
          id="{46292809-EBD3-4A20-BD6C-375C10AC52DD}"
          par="Icon=%3Cimage%20mediaid%3D%22%7B4D749FD9-6644-47B5-8F74-99426FB8365B%7D%22%20%2F%3E"
          ph="/body/component-wrapper-inner-{ea7ef5d0-aad7-431b-ae2e-921b56b9df8b}-0"
          uid="{E7C7BF53-A47F-4573-87E1-8C8572E495F7}" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsFullWidth&amp;IsGreyBackground=1&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse=1&amp;IsBorderBottom&amp;IsSticky"
          ph="body"
          uid="{67AFF177-8F93-49F2-B26A-C0F46B564195}" />
        <r
          ds="{0D8A922B-5C8B-479C-B784-00FF90FA1B64}"
          id="{43546A28-D231-4287-96D2-25DEF529F1A5}"
          par="TitleTag=h2&amp;TitlePosition=center&amp;TitleFontStyle=rounded&amp;DescriptionPosition=center"
          ph="/body/component-wrapper-inner-{67aff177-8f93-49f2-b26a-c0f46b564195}-0"
          uid="{04C2BA51-0C35-48B2-9CE0-D98123654EF8}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190611T123332Z
    - ID: "2f0fd5f2-8ef7-4c8d-99be-900ddc1bad9a"
      Hint: Title
      Value:  
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
