---
ID: "961b1fa3-52fa-4fd7-896f-505473b70d78"
Parent: "f7ab832c-48ad-4b04-8bbf-ee74b122c533"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Booking/View Booking/Cancel Booking Banner Folder/Cancel Booking Type/Buttons Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251204T162525Z
