---
ID: "f66ce8f6-e22b-4eb3-ae16-71ea8077165d"
Parent: "ae5da933-19f8-4b3b-a158-4fe856a6c1f5"
Template: "ae5da933-19f8-4b3b-a158-4fe856a6c1f5"
Path: /sitecore/templates/Feature/PageContent/Health Entry Requirements/Health Entry Requirements Block/__Standard Values
DB: master
SharedFields:
- ID: "02e02ce5-0040-4c56-824c-036373976c89"
  Hint: HealthEntryRequirements
  Type: Treelist
  Value: 
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {26A7902F-6625-42AD-89D3-8E8A332B2311}
    {899A5AAA-E367-4D14-9913-3E5866C6CB7B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210325T135419Z
