---
ID: "c6bc8e91-db6a-4383-81cf-ffa7313e1602"
Parent: "b278cafc-5c97-4b37-af77-604ecd979ee5"
Template: "b278cafc-5c97-4b37-af77-604ecd979ee5"
Path: /sitecore/templates/Project/Holidays/Pages/Holiday Type Grouping/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {B278CAFC-5C97-4B37-AF77-604ECD979EE5}
    {C6C7FCEF-96CD-4D17-81C1-80CDA7873612}
- ID: "37107ef0-1210-42d4-91c0-4de610af345b"
  Hint: TransparentItem
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230727T115303Z
