---
ID: "7b6a263e-02a1-4675-9af2-507989528e1e"
Parent: "feebd005-3dda-4a48-a216-dab9041ed7af"
Template: "feebd005-3dda-4a48-a216-dab9041ed7af"
Path: /sitecore/templates/Feature/Destinations/Alternative Boards Popup/__Standard Values
DB: master
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230606T154024Z
    - ID: "27f14a4d-e731-4be5-8817-fcae4c20df66"
      Hint: MainTitle
      Value: Verpflegungsoptionen für diesen Urlaub
    - ID: "323a0eb5-a80d-45d9-8669-6c6155b2532b"
      Hint: RoomChangeInfoMessage
      Value: <p>Einige unserer Zimmer sind nur bei bestimmten Pauschalreisen mit bestimmten Verpflegungsarten verfügbar. Wenn du also die Verpflegungsart hier änderst, wird möglicherweise ein anderer Zimmername angezeigt.</p>
    - ID: "4833b8cc-3332-4b9d-af43-c6cdf8df202f"
      Hint: CurrentChoiceTitle
      Value: Deine aktuell gewählte Verpflegungsart
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6a4f2afc-8cef-48d7-90b1-241c1a8a7fb9"
      Hint: WithoutFreeChildPlaceTitle
      Value: "{number} Andere Verpflegungsoptionen ohne kostenlosen Platz für Kinder"
    - ID: "7404c56e-9b7e-46e4-bd93-69358ef1a92c"
      Hint: OtherOptionTitle
      Value: "{number} Andere Verpflegungsoptionen"
    - ID: "75de50e9-4aac-4e08-9723-d2b4c8eda810"
      Hint: RoomChangeInfoTitle
      Value: Die Änderung der Verpflegungsart könnte sich auf dein Zimmer auswirken
    - ID: "f2acea7c-0ed5-4442-ab69-5b31caee2d11"
      Hint: WithFreeChildPlaceTitle
      Value: "{number} Andere Verpflegungsoptionen mit einem freien Kinderplatz"
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230606T154024Z
    - ID: "27f14a4d-e731-4be5-8817-fcae4c20df66"
      Hint: MainTitle
      Value: Board Options for this Holiday
    - ID: "323a0eb5-a80d-45d9-8669-6c6155b2532b"
      Hint: RoomChangeInfoMessage
      Value: <p>Some of our rooms are only available with certain boards on some package holidays, so by changing the board here you may see a different room name.</p>
    - ID: "4833b8cc-3332-4b9d-af43-c6cdf8df202f"
      Hint: CurrentChoiceTitle
      Value: Your current board choice
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6a4f2afc-8cef-48d7-90b1-241c1a8a7fb9"
      Hint: WithoutFreeChildPlaceTitle
      Value: "{number} Other Board Options without a Free Child Place"
    - ID: "7404c56e-9b7e-46e4-bd93-69358ef1a92c"
      Hint: OtherOptionTitle
      Value: "{number} Other Board Options"
    - ID: "75de50e9-4aac-4e08-9723-d2b4c8eda810"
      Hint: RoomChangeInfoTitle
      Value: Changing board could change your room
    - ID: "f2acea7c-0ed5-4442-ab69-5b31caee2d11"
      Hint: WithFreeChildPlaceTitle
      Value: "{number} Other Board Options with a Free Child Place"
- Language: "fr-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230606T154024Z
    - ID: "27f14a4d-e731-4be5-8817-fcae4c20df66"
      Hint: MainTitle
      Value:  Options d’hébergement pour ce séjour 
    - ID: "323a0eb5-a80d-45d9-8669-6c6155b2532b"
      Hint: RoomChangeInfoMessage
      Value: "<p>Certaines de nos chambres sont disponibles pour certaines options d’hébergement uniquement et pour certains forfaits vacances. Si vous changez d’option d’hébergement, vous verrez peut-être s’afficher un nom de chambre différent.</p>"
    - ID: "4833b8cc-3332-4b9d-af43-c6cdf8df202f"
      Hint: CurrentChoiceTitle
      Value:  Votre choix d’hébergement actuel 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6a4f2afc-8cef-48d7-90b1-241c1a8a7fb9"
      Hint: WithoutFreeChildPlaceTitle
      Value: " {number} autres options d’hébergement sans place enfant gratuite "
    - ID: "7404c56e-9b7e-46e4-bd93-69358ef1a92c"
      Hint: OtherOptionTitle
      Value: " {number} autres options d’hébergement "
    - ID: "75de50e9-4aac-4e08-9723-d2b4c8eda810"
      Hint: RoomChangeInfoTitle
      Value:  Changer d’option d’hébergement pourrait modifier votre chambre 
    - ID: "f2acea7c-0ed5-4442-ab69-5b31caee2d11"
      Hint: WithFreeChildPlaceTitle
      Value: " {number} autres options de pension avec une place gratuite pour les enfants"
