---
ID: "4378d601-1298-43a6-bed8-822b36854fa1"
Parent: "a16039b9-14f4-428d-880c-9eb13e6789c8"
Template: "a16039b9-14f4-428d-880c-9eb13e6789c8"
Path: /sitecore/templates/Project/Holidays/Site Settings/Price Jump Popup Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210726T124645Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
