---
ID: "ea7a8855-40d4-45c0-8cbd-4c15a41ae197"
Parent: "02f89113-4c03-40f8-988b-5ae62329b681"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/Content Sync/Update Price Graph Settings
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    $itemPath = "master:/content/EasyJet/Holidays/Settings/Price Graph Settings"
    $itemTemplateId = "{F1047BD4-9FB5-4F7D-9089-09950498A6E2}";
    
    $item = Get-Item -path $itemPath -ErrorAction SilentlyContinue
    
    if ($item -ne $null) {
        $item.Editing.BeginEdit()
        $item["PriceGraphDepartureIcon"] = '<image mediaid="{E64ABAF1-8DD4-4C6C-B9D9-7559E57385F6}" />';
        $item["PriceGraphArrivalIcon"] = '<image mediaid="{39AFBE07-2502-4BB3-8237-EA769D786A6E}" />';
        $item["PriceGraphNoFlightIcon"] = '<image mediaid="{F2A5EB24-7722-4867-B386-9341B7DD67FA}" />';
        $item["PriceGraphDatesForLoading"] = 15;
        $item["PriceGraphAmountOfLoadingItems"] = 3;
        $item["PriceGraphHideInfoMessage"] = "0";
        
        $item.Editing.EndEdit() | Out-Null;
        
        Write-Host "Item" $item.Name "successfully updated";
    }
    
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 900
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191226T143505Z
