---
ID: "3e1c4217-5b0f-48ff-a33e-2e2d64506318"
Parent: "5bc69400-4136-4115-8b45-3f22bd635069"
Template: "5bc69400-4136-4115-8b45-3f22bd635069"
Path: /sitecore/templates/Feature/PageContent/SiteMetadata/Settings/Meta Robot/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190814T114610Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
