//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace easyJet.Holidays.External.Atcom.Models.Internal
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/InfoBookingRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/InfoBookingRequest", IsNullable = false)]
    public partial class InfoBookingRequest : AtcomresBookingBaseRequest
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public bool ReturnServiceBreakDown;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnServiceBreakDownSpecified;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Inc_AutoSelectedItems;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public bool Fetch_Cost;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fetch_CostSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public bool Chk_Inv;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Chk_InvSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common", DataType = "date")]
        public System.DateTime Cost_Dt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cost_DtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string Disc_Code;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Return_SearchResults;

        /// <remarks/>
        public bool Chk_Ext_Flt_Inv;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Chk_Ext_Flt_InvSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public bool Fetch_Rm_Cost_Prices;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fetch_Rm_Cost_PricesSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public bool Fetch_Item_Cost_Prices;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fetch_Item_Cost_PricesSpecified;

        /// <remarks/>
        public bool ApplyDuplicateCheck;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplyDuplicateCheckSpecified;

        public InfoBookingRequest()
        {
            this.Inc_AutoSelectedItems = false;
            this.Fetch_Cost = false;
            this.Chk_Inv = true;
            this.Return_SearchResults = false;
            this.Chk_Ext_Flt_Inv = false;
            this.ApplyDuplicateCheck = false;
        }
    }
}