export enum ApiErrors {
    AccountLockedOrInvalidPassword = '1500003',
    EmailDoesNotExists = '104008',
    EmailAlreadyExists = '1600019',
    OfferNotAvailable = 'API-ERR-100000',
    CommitBookingError = 'API-ERR-300020',
    CancelPaymentError = 'API-ERR-300022',
    ResetPasswordError = 'API-ERR-1000003',
    DenyPayment = '267',
    CanNotCreateBooking = 'API-ERR-300000',
    WrongDiscount = 'API-ERR-1500007',
    WrongDiscountNotFound = 'API-ERR-1500008',
    WrongDiscountExceeded = 'API-ERR-1500009',
    WrongSystemDiscount = 'E34011',
    WrongSystemDiscountDates = 'E34009',
    BookingTransferIsNotAvailable = 'API-ERR-300104',
    PromocodeValidation = 'API-ERR-1500200',
    AcountLockedBySitecoreSettings = 'API-ERR-1000005',
    VoucherExpired = 'API-ERR-1500010',
    VoucherWasRedeemedBySomeoneElse = 'API-ERR-1500011',
    VoucherWasRedeemedByYou = 'API-ERR-1500012',
    PromocodeIsRequired = 'API-ERR-000001',
    NotLeadPassengerLogged = 'API-ERR-300002',
    RoutesModifyProhibited = 'API-ERR-240001',
    SelectedSeatsNotAvailable = 'API-ERR-300302',
    NotAllSeatsForFlightSelected = 'API-ERR-300304',
    MaxPriceJumpExceeded = 'API-ERR-100003',
    PriceNotValid = 'API-ERR-300010',
    ChangeLimitExeeded = 'API-ERR-240008',
    CharactersChangeLimitExeeded = 'API-ERR-240009',
    SelectedSeatsUnavailableAmendFlow = 'API-ERR-240011',
    SelectedSeatsPriceChangeAmendFlow = 'API-ERR-240012',
    RoomAndBoardVariantsUnavailable = 'API-ERR-240016',
    LargeCabinBagAllowanceExceeded = 'API-ERR-300411',
    AlternativeHotelCantBeValidated = 'API-ERR-240023',
    AirportAncillarySearchNotPermittedForCriteria = 'E10731',
    AirportAncillaryParkingSearchNotPermittedForCriteria = 'E10732',
    AirportAncillaryUnableToBookExternalItem = 'E10729',
    AirportAncillarySearchTypeNotCombined = 'E10730',
    AirportParkingValidationErrorDropOffTime = 'E10737',
    AirportParkingValidationErrorPickUpTime = 'E10738',
    AirportParkingValidationErrorE11037 = 'E11037',
    UnconfirmedAncillaryServicesOnBooking = 'E10743',
    UKAncillaryServiceNotValidForBooking = 'E10744',
    CommitBookingPriceJump = 'API-ERR-300024',
}

export const AMEND_SEATS_UNAVAILABLE_API_ERRORS = [
    ApiErrors.SelectedSeatsUnavailableAmendFlow,
    ApiErrors.SelectedSeatsPriceChangeAmendFlow,
];

export const AIRPORT_PARKING_UNAVAILABLE_API_ERRORS = [
    ApiErrors.AirportAncillarySearchNotPermittedForCriteria,
    ApiErrors.AirportAncillaryParkingSearchNotPermittedForCriteria,
    ApiErrors.UnconfirmedAncillaryServicesOnBooking,
    ApiErrors.UKAncillaryServiceNotValidForBooking,
];

export const AIRPORT_PARKING_VALIDATION_API_ERRORS = [
    ApiErrors.AirportParkingValidationErrorE11037,
    ApiErrors.AirportAncillaryUnableToBookExternalItem,
    ApiErrors.AirportAncillarySearchTypeNotCombined,
    ApiErrors.AirportAncillarySearchNotPermittedForCriteria,
    ApiErrors.AirportAncillaryParkingSearchNotPermittedForCriteria,
    ApiErrors.AirportParkingValidationErrorDropOffTime,
    ApiErrors.AirportParkingValidationErrorPickUpTime,
];
