export enum ValidationRule {
    Required = 'required',
    MaxLength = 'maxLength',
    MinLength = 'minLength',
    Pattern = 'pattern',
    ReversePattern = 'reversePattern',
    CardNumber = 'cardNumber',
    Number = 'number',
    PaymentMethod = 'paymentMethod',
    ConstLength = 'constLength',
    ExpiryDate = 'expiryDate',
    Date = 'date',
    TomorrowDate = 'tomorrowDate',
    MaxLengthPhone = 'maxLengthPhone',
    MaxValue = 'maxValue',
    FileSize = 'fileSize',
    FileType = 'fileType',
    FilesAmount = 'filesAmount',
    MinValue = 'minValue',
    MaxDecimalPlaces = 'maxDecimalPlaces',
    ProhibitedWords = 'prohibitedWords',
}
