---
ID: "34e73dc5-515e-4a7b-ab15-fd2c025fb47e"
Parent: "2743018f-e73c-437f-be33-ff0ea923c9fa"
Template: "2743018f-e73c-437f-be33-ff0ea923c9fa"
Path: /sitecore/templates/Foundation/Destinations/Filters/Search Filters Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{1814B832-3501-4BF1-834C-60962AFC02B3}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211101T082712Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
