import { mockBooking } from 'frontend/__mocks__/booking';

export const mockPreparedBookingDetailsData = {
    luggageCount: 7,
    night: 30,
    packageIcons: mockBooking.package.accom.hotel.theme.packageIcons,
    routeArr: {
        arrDate: '2023-05-19T00:45:00+00:00',
        arrLocation: 'London',
        arrItemName: 'London Gatwick',
        arrName: 'London Gatwick',
        arrPt: 'LGW',
        bkgCls: 'Z',
        car: 'EZY',
        depDate: '2023-05-18T20:40:00+00:00',
        depLocation: 'Costa Teguise',
        depItemName: 'Lanzarote',
        depName: 'Lanzarote',
        depPt: 'ACE',
        direction: 'inbound',
        extRefId: 'K6578ZK',
        fltNo: '6572',
        id: '170430/2978',
        isExt: true,
        paxs: [{ paxId: '1' }, { paxId: '2' }],
    },
    routeDep: {
        arrDate: '2023-05-11T16:25:00+00:00',
        arrLocation: 'Costa Teguise',
        arrName: 'Lanzarote',
        arrItemName: 'Lanzarote',
        arrPt: 'ACE',
        bkgCls: 'Z',
        car: 'EZY',
        depDate: '2023-05-11T12:10:00+00:00',
        depLocation: 'London',
        depName: 'London Gatwick',
        depItemName: 'London Gatwick',
        depPt: 'LGW',
        direction: 'outbound',
        extRefId: 'K6578ZK',
        fltNo: '6453',
        id: '170430/3978',
        isExt: true,
        paxs: [{ paxId: '1' }, { paxId: '2' }],
    },
    transfer: {
        autoInclude: false,
        code: 'ABCN0/LCO',
        content: 'content',
        iconUrl: 'string',
        id: '1',
        isHidden: false,
        method: 'PI',
        name: 'Private taxi',
        price: 10,
        pricePP: 5,
        prom: 'AUCI',
        quantity: 2,
        rateRule: 'DAY',
        startDate: '2023-05-22T00:00:00',
        transferInfo: { depInstr: 'some dep instr', arrivalInstr: 'some arr instr', duration: 50 },
        type: 'PRIVATE',
    },
};
