<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Sitecore.Analytics" />
        <PackageReference Include="Sitecore.Analytics.Core" />
        <PackageReference Include="Sitecore.Analytics.Model" />
        <PackageReference Include="Sitecore.CES.GeoIp.Core" />
        <PackageReference Include="Sitecore.XConnect" />
        <PackageReference Include="Sitecore.XConnect.Collection.Model" />
        <PackageReference Include="Sitecore.XConnect.Core" />
    </ItemGroup>
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Foundation\Analytics\code\easyJet.Foundation.Analytics.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Foundation\PushNotification\code\easyJet.Foundation.PushNotifications.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Feature\PushNotifications\code\easyJet.Feature.PushNotifications.csproj" />
    </ItemGroup>
</Project>