SELECT 'ALTER INDEX ' + QUOTENAME(I.NAME) + ' ON ' +QUOTENAME(OBJECT_SCHEMA_NAME(I.OBJECT_ID)) + '.'+ QUOTENAME(OBJECT_NAME(I.OBJECT_ID)) + ' REBUILD ' AS [SQLQUERY]
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(), NULL, NULL, NULL, NULL) INS
INNER JOIN SYS.INDEXES I ON I.OBJECT_ID = INS.OBJECT_ID
AND I.INDEX_ID = INS.INDEX_ID
WHERE INS.AVG_FRAGMENTATION_IN_PERCENT > 10 
AND I.NAME IS NOT NULL
ORDER BY INS.AVG_FRAGMENTATION_IN_PERCENT DESC