---
ID: "3507ceec-e1d4-4c93-8106-254afec91d04"
Parent: "7f3f4b1e-c2f7-47dc-8454-13a6c571d627"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Presentation/Base/_Base Filters Order/Filters Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200803T134701Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
