using Amazon.DynamoDBv2.DataModel;
using easyJet.Holidays.Api.Domain.Data.Booking;

namespace easyJet.Holidays.Api.Domain.Data.DynamoDB.Bookings
{
    public class GroupBooking
    {
        /// <summary>
        /// Id, that is being generated by WebApi before saving
        /// </summary>
        [DynamoDBHashKey]
        public string Id { get; set; }

        /// <summary>
        /// UTC time, that is being generated by WebApi before saving
        /// </summary>
        [DynamoDBProperty]
        public DateTime Created { get; set; }

        /// <summary>
        /// Trade agent name
        /// </summary>
        [DynamoDBProperty]
        public string AgentName { get; set; }

        /// <summary>
        /// Requester's contact email
        /// </summary>
        [DynamoDBProperty]
        public string Email { get; set; }

        /// <summary>
        /// Agent's ABTA number
        /// </summary>
        [DynamoDBProperty]
        public string ABTANumber { get; set; }

        /// <summary>
        /// Desirable number of rooms. if set to 0 - means "I don't mind"
        /// </summary>
        [DynamoDBProperty]
        public int NumberOfRooms { get; set; }

        /// <summary>
        /// Adults, Children and Infants amounts, which should be added to the request
        /// </summary>
        [DynamoDBProperty]
        public TotalPassengers TotalPassengers { get; set; }

        /// <summary>
        /// Departure airport
        /// </summary>
        [DynamoDBProperty]
        public DepartureAirport DepartureAirport { get; set; }

        /// <summary>
        /// Departure date. should be in future when group booking request is being performed.
        /// </summary>
        [DynamoDBProperty]
        public DateTime DepartureDate { get; set; }

        /// <summary>
        /// Duration of the holiday. at least 1 day
        /// </summary>
        [DynamoDBProperty]
        public int DurationOfHoliday { get; set; }

        /// <summary>
        /// Board basis
        /// </summary>
        [DynamoDBProperty]
        public string BoardBasis { get; set; }

        /// <summary>
        /// Target destination of the trip
        /// </summary>
        [DynamoDBProperty]
        public string DestinationHotelOrRegion { get; set; }

        /// <summary>
        /// Additional requests/things which should be mentioned
        /// </summary>
        [DynamoDBProperty]
        public string AdditionalDetails { get; set; }

        /// <summary>
        /// Information about rooms
        /// </summary>
        [DynamoDBProperty]
        public List<GroupBookingRoom> Rooms { get; set; }
    }
}