<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AWSProjectType>Lambda</AWSProjectType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PublishReadyToRun>true</PublishReadyToRun>
    <AssemblyName>Ejh.HbgHotelDiscounts</AssemblyName>
    <!-- Enable source generation for Lambda Annotations -->
    <GenerateLambdaAnnotationsSource>true</GenerateLambdaAnnotationsSource>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <!-- Lambda + AWS packages -->
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
    <PackageReference Include="Amazon.Lambda.Annotations" />
    <PackageReference Include="AWSSDK.DynamoDBv2" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
    <PackageReference Include="AWSSDK.SSO" />
    <PackageReference Include="AWSSDK.SSOOIDC" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\easyJet.Holidays.External.AWS.Domain\easyJet.Holidays.External.AWS.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>