---
ID: "93547680-763f-4a62-89ad-1ed5cc55a63f"
Parent: "ae0776fb-f0ae-4fa8-8aba-676ae82cc6cf"
Template: "ae0776fb-f0ae-4fa8-8aba-676ae82cc6cf"
Path: /sitecore/templates/Project/Holidays/Pages/404 Page/__Standard Values
DB: master
SharedFields:
- ID: "37cef6a9-6298-4f19-812f-1176d2a6a39a"
  Hint: ChangeFrequency
  Value: "{BF310BAC-6A31-4366-85B9-5A173937EEDD}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4696E3CC-7DA0-4264-BF00-B6E49C11B857}">
        <r
          ds="{43379DA2-1D47-412C-B527-3889F16BF4B3}"
          id="{CFDDA56D-9D28-45DE-BED6-FF67AC4C38B5}"
          par=""
          ph="/header"
          uid="{689C1132-6AB0-4957-AAD3-328B9EA62DD5}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191029T093318Z
