---
ID: "17c254a6-0cc9-41fc-b3d5-4b5aa8b0196a"
Parent: "5b4eca4d-46fa-4375-b622-b7a8a2a655ef"
Template: "5b4eca4d-46fa-4375-b622-b7a8a2a655ef"
Path: /sitecore/templates/Project/MicroApps/UserManagement/Components/Agencies/Agency Form/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 250
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240418T194623Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
