<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<AssemblyName>CheapestMonthSync</AssemblyName>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improvement cold starts. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents"  />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
    <PackageReference Include="Amazon.Lambda.Annotations"  />
    <PackageReference Include="Amazon.Lambda.SQSEvents" />
  </ItemGroup>
  <!-- 
    The FrameworkReference is used to reduce the deployment bundle size by not having to include 
    dependencies like Microsoft.Extensions.DependencyInjection. The Microsoft.AspNetCore.App
    which is available in the Managed .NET Lambda runtime already includes those assemblies.
  -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\easyJet.Holidays.Api.Domain\easyJet.Holidays.Api.Domain.csproj" />
    <ProjectReference Include="..\easyJet.Holidays.External.Atcom\easyJet.Holidays.External.Atcom.csproj" />
    <ProjectReference Include="..\easyJet.Holidays.External.AWS.Domain\easyJet.Holidays.External.AWS.Domain.csproj" />
    <ProjectReference Include="..\easyJet.Holidays.External.DA\easyJet.Holidays.External.DA.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
	  <Content Include="..\easyJet.Holidays.External.AWS.Domain\appsettings.shared.json" Link="appsettings.shared.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>
</Project>