using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace easyJet.Holidays.Api.Domain.Data.AirportParking
{
    /// <summary>
    /// Airport parking item coming from AtCom as XML for deserialization.
    /// </summary>
    [Serializable]
    [DataContract]
    public class AirportParkingItem
    {
        /// <summary>
        /// Name of the parking.
        /// </summary>
        [DataMember]
        public string Title { get; set; }

        /// <summary>
        /// First part of the description.
        /// </summary>
        [DataMember]
        public string Description { get; set; }

        /// <summary>
        /// Second part of the description.
        /// </summary>
        [DataMember]
        public string TransferTip { get; set; }

        /// <summary>
        /// Meet and Greet value
        /// </summary>
        [DataMember]
        public bool IsMeetAndGreet { get; set; }

        /// <summary>
        /// Park And Ride value
        /// </summary>
        [DataMember]
        public bool IsParkAndRide { get; set; }

        /// <summary>
        /// Park and Stroll value
        /// </summary>
        [DataMember]
        public bool IsParkAndStroll { get; set; }

        /// <summary>
        /// Product brand image.
        /// </summary>
        [DataMember]
        public Uri BrandImage { get; set; }
        
        /// <summary>
        /// Product address
        /// </summary>
        [DataMember]
        public string Address { get; set; }

        /// <summary>
        /// <inheritdoc cref="AirportParkingBookingDetails"/>
        /// </summary>
        [DataMember]
        public AirportParkingBookingDetails BookingDetails { get; set; } = new();
    }

    /// <summary>
    /// Contains all info generated by AtCom. It's not necessary for the presentation layer but for the validation.
    /// </summary>
    [Serializable]
    [DataContract]
    public class AirportParkingBookingDetails
    {
        /// <summary>
        /// Product Code of the parking to be used with Holiday Extras API.
        /// </summary>
        [DataMember]
        public string ProductCode { get; set; }

        /// <summary>
        /// Total price of the offer.
        /// </summary>
        [DataMember]
        public decimal TotalPrice { get; set; }

        /// <summary>
        /// Car Parking Arrival Time
        /// </summary>
        [DataMember(Name = "startTime")]
        [Required]
        public string StartTime { get; set; }

        /// <summary>
        /// Car Parking Departure Time
        /// </summary>
        [DataMember(Name = "endTime")]
        [Required]
        public string EndTime { get; set; }

        /// <summary>
        /// Car Parking Type
        /// </summary>
        [DataMember(Name = "type")]
        public ParkingType Type { get; set; }

        /// <summary>
        /// Start date for the parking booking.
        /// </summary>
        [DataMember]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// End date for the parking booking. It can be different (later) from the date of the return flight, due to the <see cref="EndTime"/> property.
        /// </summary>
        [DataMember]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Promotion Code, given by AtCom
        /// </summary>
        [DataMember]
        public string PromotionCode { get; set; }

        /// <summary>
        /// Contains some source XML with a request that AtCom needs to perform against Holiday Extras to verify the information and perform the booking. It is serialized within a CDATA element.
        /// </summary>
        [DataMember]
        public string KeyData { get; set; }
        
        /// <summary>
        /// Contains the parking reference code from atcom
        /// </summary>
        [DataMember(Name= "extRefId")]
        public string BookingReferenceCode { get; set; }
    }

    /// <summary>
    /// Parking type, based on AtCom parking type
    /// </summary>
    public enum ParkingType
    {
#pragma warning disable CA1707 // Identifiers should not contain underscores
        /// <summary>
        /// On site
        /// </summary>
        ON_SITE,

        /// <summary>
        /// Off site
        /// </summary>
        OFF_SITE,

        /// <summary>
        /// Meet and greeet
        /// </summary>
        MEET_AND_GREET,

        /// <summary>
        /// On airport
        /// </summary>
        ON_AIRPORT,
#pragma warning restore CA1707
    }
}