---
ID: "39133b43-2187-4201-ac96-e7a55180081e"
Parent: "434e365e-d63b-4a66-9e88-88c07ec2b97d"
Template: "434e365e-d63b-4a66-9e88-88c07ec2b97d"
Path: /sitecore/templates/Foundation/Destinations/Transfers Info/Transfer Info/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200217T085512Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
