<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\easyJet.Holidays.External.AWS.CheapestMonthSyncRunner\easyJet.Holidays.External.AWS.CheapestMonthSyncRunner.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
