//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace easyJet.Holidays.External.Atcom.Models.Internal
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/FlightExtraSearchResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/FlightExtraSearchResponse", IsNullable = false)]
    public partial class FlightExtraSearchResponse : AtcomresBaseOfferSearchResponse
    {

        private Pax[] paxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pax", Namespace = "AtComRes/Common")]
        public Pax[] Pax
        {
            get
            {
                return this.paxField;
            }
            set
            {
                this.paxField = value;
            }
        }
    }
}
