---
ID: "c45ee951-5989-4666-abe7-e19f3efe048d"
Parent: "6f657c6f-36d0-4545-853b-ba63bea8af24"
Template: "38b64494-c7f8-4d9e-b375-55ee30904f53"
Path: /sitecore/content/EasyJet/TradePortal/Settings
DB: master
SharedFields:
- ID: "a20757ac-8119-4bf2-aa70-f7dd4480ce25"
  Hint: Item Not Found Page
  Value: "{B7906B48-8366-4360-8C1B-CB780A604845}"
- ID: "c49b4b31-1c4c-4dda-a4a5-8899b524a688"
  Hint: Maintenance Page Enabled
  Type: Checkbox
  Value: 0
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\easyJet SEO Manager|pe|-item:write|+item:read|^*|pd|-item:write|+item:read|^*|ar|sitecore\easyJet Read Only|pe|-item:rename|-item:delete|+item:read|-item:admin|-item:write|-item:create|^*|pd|-item:rename|-item:delete|+item:read|-item:admin|-item:write|-item:create|^*|ar|sitecore\Content Administrator|pe|-item:rename|-item:delete|+item:read|-item:admin|-item:write|-item:create|^*|pd|-item:rename|-item:delete|+item:read|-item:admin|-item:write|-item:create|^*|ar|sitecore\easyJet Content Author|pe|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|^*|pd|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|^*|ar|sitecore\easyJet General User|pe|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|^*|pd|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|^*|ar|sitecore\easyJet Restricted Content Author|pe|-item:delete|-item:write|pd|-item:delete|-item:write|ar|sitecore\eJ Booking Manager|pe|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|!*|pd|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|!*|
- ID: "f842d9d2-e44b-4f14-b6cc-ac45c309025a"
  Hint: Maintenance Page
  Value: "{B7906B48-8366-4360-8C1B-CB780A604845}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T155034Z
