---
ID: "6a78a5b0-e5ad-4f6a-946e-263aa070f1db"
Parent: "02ccff8b-01e9-4f6f-b706-aa4326819d13"
Template: "02ccff8b-01e9-4f6f-b706-aa4326819d13"
Path: /sitecore/templates/Project/Trade Portal/Datasource/Seats Availability Error Popup Trade/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230619T134541Z
    - ID: "2f0fd5f2-8ef7-4c8d-99be-900ddc1bad9a"
      Hint: Title
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6fc927df-f428-4ddb-b06d-23846c68adc6"
      Hint: Description
      Value: 
    - ID: "71b1c46b-7153-4109-b2a2-a96f8de557b2"
      Hint: ConfirmationCheckboxLabel
      Value: 
    - ID: "9bad66f4-e8f9-48b7-b6fe-9ab07343bca6"
      Hint: ClearSeatsButtonText
      Value: 
    - ID: "cd2ab5f1-7dd2-4304-a257-975b50f3f4ae"
      Hint: ReselectSeatsButtonText
      Value: 
