---
ID: "c88f1275-7565-4adb-929b-577424de86dc"
Parent: "bc1c3670-54c0-4041-946f-ab4cc240bab4"
Template: "bc1c3670-54c0-4041-946f-ab4cc240bab4"
Path: /sitecore/templates/Feature/Booking/Cancel Booking/Cancel Booking Header/_Standard Values
DB: master
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "16962e4a-1ecb-4af6-90ee-cd7651500532"
      Hint: Title
      Value: Stornieren Sie Ihren Urlaub
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240906T113815Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a289f8bc-35b7-4ce8-b843-51444c154146"
      Hint: Subtitle
      Value: Wir bedauern, dass Sie Ihre Meinung geändert haben, aber Sie können Ihren Urlaub in 3 einfachen Schritten stornieren.
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "16962e4a-1ecb-4af6-90ee-cd7651500532"
      Hint: Title
      Value: Stornieren Sie Ihren Urlaub
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240906T113925Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a289f8bc-35b7-4ce8-b843-51444c154146"
      Hint: Subtitle
      Value: Wir bedauern, dass Sie Ihre Meinung geändert haben, aber Sie können Ihren Urlaub in 3 einfachen Schritten stornieren.
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "16962e4a-1ecb-4af6-90ee-cd7651500532"
      Hint: Title
      Value: Cancel your holiday
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240906T113402Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a289f8bc-35b7-4ce8-b843-51444c154146"
      Hint: Subtitle
      Value: We are sorry to hear you have changed your mind, but you can cancel your holiday in 3 simple steps below.
- Language: "fr-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "16962e4a-1ecb-4af6-90ee-cd7651500532"
      Hint: Title
      Value: Annulez vos vacances
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240906T113744Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a289f8bc-35b7-4ce8-b843-51444c154146"
      Hint: Subtitle
      Value: Nous sommes désolés d'apprendre que vous avez changé d'avis, mais vous pouvez annuler votre séjour en trois étapes simples.
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "16962e4a-1ecb-4af6-90ee-cd7651500532"
      Hint: Title
      Value: Annulez vos vacances
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240906T113951Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a289f8bc-35b7-4ce8-b843-51444c154146"
      Hint: Subtitle
      Value: Nous sommes désolés d'apprendre que vous avez changé d'avis, mais vous pouvez annuler votre séjour en trois étapes simples.
