---
ID: "e0b34df8-9354-4841-b3ec-d8b0a2e1f374"
Parent: "ca9b20eb-f054-41a0-873a-f63776b9fe68"
Template: "ca9b20eb-f054-41a0-873a-f63776b9fe68"
Path: /sitecore/templates/Foundation/Destinations/Search/Search Pod Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {05D15AAB-CFF6-4FF9-B048-F9E48DA7153E}
    {E24DE0D7-390F-424F-B937-761CE71C5E21}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201007T085332Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
