---
ID: "6f98dda9-0a34-41ce-9c36-4bc1f286cd46"
Parent: "15c8583c-f86b-4982-85e3-b21ac3c587c1"
Template: "15c8583c-f86b-4982-85e3-b21ac3c587c1"
Path: /sitecore/templates/Foundation/Destinations/Facilities/Overview Facility Virtual Grouping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220221T071159Z
