---
ID: "c77b63bd-7734-43de-9476-86b390acac6e"
Parent: "e24de0d7-390f-424f-b937-761ce71c5e21"
Template: "e24de0d7-390f-424f-b937-761ce71c5e21"
Path: /sitecore/templates/Foundation/Destinations/Search/Promopage Search Pod/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201007T095856Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
