---
ID: "815b763e-1aec-4b10-b019-afbc749c9af0"
Parent: "a48b79e1-fb35-470f-a030-2c8c204dd37e"
Template: "a48b79e1-fb35-470f-a030-2c8c204dd37e"
Path: /sitecore/templates/Feature/Destinations/Amend/Amend Dates/Amend Dates Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "20e2cb23-1b67-4be7-87f3-fd56902a4334"
      Hint: isAttentionMessageEnabled
      Type: Checkbox
      Value: 1
    - ID: "233c8d14-625d-42ca-82f5-9afefc67a82d"
      Hint: PopupSubtext
      Value: "Unfortunately these dates are not available online. Please select new dates or call the call centre on {number} to complete your change."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210521T074901Z
    - ID: "2c3f70b8-ce34-4878-b6f6-2c04a425605d"
      Hint: PopupIcon
      Value: |
        <image mediaid="{A484212A-377A-4DC9-8754-BABFE7701E3D}" />
    - ID: "5afa6cfe-448f-49d3-970b-54e098ffed1a"
      Hint: isStickySummaryEnabled
      Type: Checkbox
      Value: 1
    - ID: "5b87f54b-ffb7-4e3a-b3db-3b2a0888f658"
      Hint: Phone
      Value: 03305515165
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
          sitecore\admin
    - ID: "b3b80d73-c803-46b5-8645-a8be2c7318e9"
      Hint: PopupTitle
      Value: Dates unavailable
    - ID: "fe7c4fcc-87b7-4cf8-9fad-eeba0384598a"
      Hint: PopupCTA
      Value: Back to calendar
