<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="SoapReference\" />
        <Folder Include="Services\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.Security.Cryptography.Pkcs" />
        <PackageReference Include="System.ServiceModel.Http" />
        <PackageReference Include="System.ServiceModel.Primitives" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\easyJet.Holidays.Api.Domain\easyJet.Holidays.Api.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.ServiceModel.Duplex" />
        <PackageReference Include="System.ServiceModel.NetTcp" />
        <PackageReference Include="System.ServiceModel.Security" />
        <PackageReference Include="System.ServiceModel.Federation" />
    </ItemGroup>
</Project>