---
ID: "6f158033-2288-4726-8c31-4ce544a214e9"
Parent: "7cba18e5-ce20-4e9b-9819-c52472995d3a"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Destinations/Settings/Summary Bar Settings/Summary Bar Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250709T095949Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
