---
ID: "bb4b4e13-66bc-41be-9120-d979be8357d7"
Parent: "f8d9caeb-c4a2-4d82-bce5-03ca2a790c5a"
Template: "f8d9caeb-c4a2-4d82-bce5-03ca2a790c5a"
Path: /sitecore/templates/Foundation/Destinations/Dialing Codes/Dialing Codes Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{D333F42F-ADB6-402F-84C7-9015755BC38E}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191026T114226Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
