---
ID: "87991b77-a625-4289-8a24-59d586038304"
Parent: "86f2ac20-fdb7-4279-847b-93d097f9ad2c"
Template: "86f2ac20-fdb7-4279-847b-93d097f9ad2c"
Path: /sitecore/templates/Project/Holidays/Site Settings/Analytic Settings/__Standard Values
DB: master
SharedFields:
- ID: "02209222-a246-43ff-b835-8f1b0f1a4359"
  Hint: SitecorePersonalizeTimeout
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230119T114547Z
    - ID: "68225ae3-1c53-4ff7-8d61-a5af722def63"
      Hint: EnablePersonalization
      Type: Checkbox
      Value: 1
