import { FC } from 'react';
import classNames from 'classnames';
import { observer } from 'mobx-react';

import useStore from 'frontend/hooks/useStore';
import { hasUrlQuery, hasUrlQueryParam } from 'frontend/utils/url.utils';
import { IRequestedPrice } from 'models/data/IRequestedPrice';
import { MediaSize } from 'models/data/MediaSizeParams';
import { QueryParamName } from 'models/enum/QueryParamName';
import { EventTypes } from 'models/enum/tracking/EventTypes';
import { JSSImageNext } from 'frontend/components/common/JSSImageNext/JSSImageNext';
import DealsDestinationTile from 'frontend/components/renderings/DealsDestinations/components/DealsDestinationTile/DealsDestinationTile';
import { IDealsDestinationCardFields } from 'frontend/components/renderings/DealsDestinations/interfaces';

import styles from './DealsDestinationsGroupCard.module.scss';

export interface IDealsDestinationsGroupCardProps {
    fields: IDealsDestinationCardFields;
    pricesByDestCodes: Map<string, IRequestedPrice> | undefined;
    requestedSearchUrl: string | undefined;
    setIsTouristTaxTooltipDisplayed: React.Dispatch<React.SetStateAction<boolean>>;
}

export const DealsDestinationsGroupCard: FC<IDealsDestinationsGroupCardProps> = ({
    fields,
    requestedSearchUrl,
    pricesByDestCodes,
    setIsTouristTaxTooltipDisplayed,
}) => {
    const { isEditMode, trackHolidayTypesHubEvents, isHolidayTypePage, isDealsHubPage } = useStore(stores => ({
        isEditMode: stores.layoutStore.isEditMode,
        trackHolidayTypesHubEvents: stores.trackingStore.trackHolidayTypesHubEvents,
        isHolidayTypePage: stores.layoutStore.isHolidayTypePage,
        isDealsHubPage: stores.layoutStore.isDealsHubPage,
    }));

    if (!fields) return null;

    const { Title, Country, Image, Tiles } = fields;
    const title = Title?.value;
    const countryName = Country?.fields?.Name?.value;
    const countryCode = Country?.fields?.Code?.value;

    const buildUrl = (): string | null => {
        if (!requestedSearchUrl || !countryCode) {
            return null;
        }

        // Don't override destination if it exists
        // used when promopage not selected and url auto-generated by sitecore
        if (!hasUrlQueryParam(requestedSearchUrl, QueryParamName.Destination)) {
            const separator = hasUrlQuery(requestedSearchUrl) ? '&' : '?';

            return `${requestedSearchUrl}${separator}${QueryParamName.Destination}=${countryCode}`;
        }

        return requestedSearchUrl;
    };

    const getCountryTitleContent = (): string | React.JSX.Element => {
        const url = buildUrl();

        if (!url) {
            return countryName;
        }

        return (
            <a
                className='link-pseudo-overlay'
                href={url}
                onClick={(): void => {
                    (isHolidayTypePage || isDealsHubPage) &&
                        trackHolidayTypesHubEvents(EventTypes.CountryDealsClick, {
                            moduleTitle: countryName,
                            destination: url,
                        });
                }}
            >
                {countryName}
            </a>
        );
    };

    // If title is configured that show it and ignore country field.
    const titleContent = title || getCountryTitleContent();

    return (
        <div className={classNames('deals-destinations-card', styles.card)}>
            {!isEditMode && <JSSImageNext field={Image} fill mediaSize={{ desktop: MediaSize.Large }} />}
            <div className={styles.cardInner}>
                {!!titleContent && (
                    <h3 className={classNames('deals-destinations-card__title', styles.title)}>{titleContent}</h3>
                )}

                <div className={classNames('deals-destinations-card__tiles', styles.tiles)}>
                    {(Tiles || []).map(tile => (
                        <DealsDestinationTile
                            key={tile.id}
                            fields={tile.fields}
                            pricesByDestCodes={pricesByDestCodes}
                            requestedSearchUrl={requestedSearchUrl}
                            parentTitle={title || countryName}
                            setIsTouristTaxTooltipDisplayed={setIsTouristTaxTooltipDisplayed}
                        />
                    ))}
                </div>
            </div>
        </div>
    );
};

export default observer(DealsDestinationsGroupCard);
