---
ID: "51d29caf-b949-4315-82e7-93863aff99d7"
Parent: "5524bbd7-1e01-401c-8958-3b49914336fb"
Template: "5524bbd7-1e01-401c-8958-3b49914336fb"
Path: /sitecore/templates/Foundation/Presentation/Rendering Parameters/Destination Recommended Hotels Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200506T101243Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
