import { mockSitecoreField, mockSitecoreImageField } from 'frontend/utils/tests.utils';
import ComparePriceModuleVariant from 'models/enum/ComparePriceModuleVariant';
import { IComparePriceModuleFields } from 'frontend/components/renderings/ComparePriceModule/components/ComparePriceContent/ComparePriceContent.utils';

export const comparePriceFieldsMock: IComparePriceModuleFields = {
    Variant: mockSitecoreField(ComparePriceModuleVariant.NothingVariant),
    IsBestValueEnabled: mockSitecoreField('IsBestValueEnabled'),
    ReservationNotificationDescription: mockSitecoreField('ReservationNotificationDescription'),
    ReservationNotificationTitle: mockSitecoreField('ReservationNotificationTitle'),
    RoomOrBoardChangesAreRequiredLabel: mockSitecoreField('RoomOrBoardChangesAreRequiredLabel'),
    ApplyWithChangesButtonText: mockSitecoreField('ApplyWithChangesButtonText'),
    BoardChangeSubtitle: mockSitecoreField('BoardChangeSubtitle'),
    BoardChangeTitle: mockSitecoreField('BoardChangeTitle'),
    ChangingFromBoardLabel: mockSitecoreField('ChangingFromBoardLabel'),
    ChangingFromRoomLabel: mockSitecoreField('ChangingFromRoomLabel'),
    ConfirmationPopupIcon: mockSitecoreField(mockSitecoreImageField('confirm icon')),
    ConfirmationPopupSubtitle: mockSitecoreField('ConfirmationPopupSubtitle'),
    ConfirmationPopupTitle: mockSitecoreField('ConfirmationPopupTitle'),
    ErrorPopupIcon: mockSitecoreField(mockSitecoreImageField('error icon')),
    ErrorPopupSubtitle: mockSitecoreField('ErrorPopupSubtitle'),
    ErrorPopupTitle: mockSitecoreField('ErrorPopupTitle'),
    GainFreeChildPlaceSubtitle: mockSitecoreField('GainFreeChildPlaceSubtitle'),
    GainFreeChildPlaceTitle: mockSitecoreField('GainFreeChildPlaceTitle'),
    LoadingText: mockSitecoreField('LoadingText'),
    LoseFreeChildPlaceSubtitle: mockSitecoreField('LoseFreeChildPlaceSubtitle'),
    LoseFreeChildPlaceTitle: mockSitecoreField('LoseFreeChildPlaceTitle'),
    NewBoardLabel: mockSitecoreField('NewBoardLabel'),
    NewRoomLabel: mockSitecoreField('NewRoomLabel'),
    ReviewChangesSubTitle: mockSitecoreField('ReviewChangesSubTitle'),
    ReviewChangesTitle: mockSitecoreField('ReviewChangesTitle'),
    RoomChangeSubtitle: mockSitecoreField('RoomChangeSubtitle'),
    RoomChangeTitle: mockSitecoreField('RoomChangeTitle'),
    BackButtonText: mockSitecoreField('BackButtonText'),
    LoadingErrorPopupSubtitle: mockSitecoreField('LoadingErrorPopupSubtitle'),
    LoadingErrorPopupTitle: mockSitecoreField('LoadingErrorPopupTitle'),
    IsFreeForKidsIconEnabled: mockSitecoreField(true),
    IsCheapestPriceDefault: mockSitecoreField(false),
    IsPriceToggleEnabled: mockSitecoreField(false),
    KeepRoomSingularLabel: mockSitecoreField('Keep Room'),
    KeepRoomPluralLabel: mockSitecoreField('Keep Rooms'),
    CheapestRoomSingularLabel: mockSitecoreField('Cheapest Room'),
    CheapestRoomPluralLabel: mockSitecoreField('Cheapest Rooms'),
};
