import { mockBooking } from './booking';
import { createMockStores } from './createMockStores';
import { mockedOffer } from './offer';
import { mockAmendDatesStore } from './stores';

describe('createMockStores', () => {
    it('should return only skeleton when stores are NOT provided', () => {
        const mockStores = createMockStores();

        expect(mockStores).toStrictEqual({
            appStore: {
                isScreenLessMedium: false,
                isScreenMedium: true,
                isScreenExtraLarge: false,
                isScreenExtraSmall: false,
                isScreenLarge: false,
                isLoading: false,
            },
            layoutStore: {
                getSettingAsNumber: expect.any(Function),
                isCancelledBookingPage: false,
                isSearchResultsPage: false,
                isPromoPage: false,
                displayName: 'Spain',
                isEditMode: false,
                getPhrase: expect.any(Function),
                getSetting: expect.any(Function),
                setWhenDropdownExperimentTestVariant: expect.any(Function),
                basePath: '',
                holdLuggageCategoryCodes: expect.any(Array),
                sportEquipmentCategoryCodes: expect.any(Array),
                largeCabinBagCode: expect.any(Array),
                sitePath: 'sitePath',
                updateLang: expect.any(Function),
                setFullUrl: expect.any(Function),
                setPageSearchSortOrder: expect.any(Function),
                isPostBookingPages: false,
                isPaymentPage: false,
                isAmendPaymentPage: false,
                isViewBookingPage: false,
                isTradePortal: false,
                isConfirmPage: false,
                isExtrasPage: false,
                isConfirmationPage: false,
                minNumberOfDaysToDeparture: 1,
                isCheapestComparePriceOption: false,
                setIsCheapestComparePriceOption: expect.any(Function),
            },
            paymentStore: {
                selectDefaultPaymentOption: expect.any(Function),
            },
            amendPaymentStore: {
                goBackToViewBooking: expect.any(Function),
                clearAmendPaymentStore: expect.any(Function),
            },
            payBalanceStore: {
                booking: mockBooking,
                isFlightExternal: true,
                isLuxuryPackage: false,
            },
            routerStore: {
                redirectTo: expect.any(Function),
                redirectToManageHubPage: expect.any(Function),
                redirectToExtrasPage: expect.any(Function),
                redirectToMicroAppChangeTransferPage: expect.any(Function),
                redirectToMicroAppChangeFlightPage: expect.any(Function),
                redirectToMicroAppChangeDatePage: expect.any(Function),
                redirectToMicroAppChangeNamePage: expect.any(Function),
                redirectToMicroAppChangeSeatsPage: expect.any(Function),
                redirectToMicroAppChangeHotelPage: expect.any(Function),
                redirectToMicroAppChangeRoomAndBoardPage: expect.any(Function),
            },
            marketStore: {
                formatMoney: expect.any(Function),
                getFormattedNumber: expect.any(Function),
            },
            viewBookingStore: {
                isBookingOutOfSync: false,
                isPostTravelPage: false,
                isFlightAndHotelPackage: false,
                isLuxuryPackage: false,
                booking: mockBooking,
                toggleLoading: expect.any(Function),
                loadBooking: expect.any(Function),
                clearBooking: expect.any(Function),
                clearViewBookingPayload: expect.any(Function),
                isBookingClearRequired: expect.any(Function),
                isFlightExternal: true,
                isLoading: false,
                isBookingCanceled: false,
                setSuccessfulAmendmentStatus: expect.any(Function),
                successfulAmendmentStatus: null,
                amendBookingStatuses: [],
                allowanceRestrictions: {},
                isMicroAppManageMyHolidayAllowed: false,
                isMicroAppAmendTransferAllowed: false,
                isMicroAppAmendFlightsAllowed: false,
                isMicroAppAmendHotelAllowed: false,
                isMicroAppAmendMultiRoomAndBoardAllowed: false,
                isMicroAppAmendRoomAndBoardAllowed: false,
                isMicroAppAmendDateAllowed: false,
                isMicroAppAmendSeatsAllowed: false,
                isMicroAppAmendNameAllowed: false,
            },
            userStore: {
                setUserDetails: expect.any(Function),
                toggleLoginPopup: expect.any(Function),
                setRedirectUrl: expect.any(Function),
                setIsRedirectPreventedAfterLogin: expect.any(Function),
                resetPassword: expect.any(Function),
                rerenderForm: expect.any(Function),
                customerErrorHandler: expect.any(Function),
                formRerenderTrigger: expect.any(Function),
                setRememberMe: expect.any(Function),
                onLogin: expect.any(Function),
                initializeCustomerLogin: expect.any(Function),
            },
            engageStore: {
                sendCustomEvent: expect.any(Function),
                sendPromoCodeEvent: expect.any(Function),
            },
            searchFiltersStore: {
                filters: [],
                selectedFilters: [],
            },
            holidayCreditStore: {
                startCreditBooking: expect.any(Function),
                selectedRefundType: 'credit',
                booking: mockBooking,
                isFlightExternal: true,
                isLuxuryPackage: false,
            },
            bookingStore: {
                isPaymentReminderVisible: expect.any(Function),
                extraLuggage: {},
                isFlightExternal: true,
                isFlightAndHotelPackage: false,
                isLuxuryPackage: false,
                clearPackageValidation: expect.any(Function),
                validatePackage: expect.any(Function),
                validatePromoCode: expect.any(Function),
                setSelectedOfferPrices: expect.any(Function),
            },
            trackingStore: {
                trackManageHubClick: expect.any(Function),
                initializePageLoadObject: expect.any(Function),
                trackSeatMapSitTogetherClick: expect.any(Function),
                trackSeatMapSitTogetherImpression: expect.any(Function),
                trackHomepageAction: expect.any(Function),
                trackModuleClick: expect.any(Function),
                addToDataLayer: expect.any(Function),
                trackGenericAmendmentAction: expect.any(Function),
                trackSuccessfulAmendment: expect.any(Function),
                trackCustomError: expect.any(Function),
                trackEventWithParams: expect.any(Function),
                trackGenericAmendmentActionWithGuests: expect.any(Function),
                trackRecommenderHotelClick: expect.any(Function),
                trackRecommenderInteraction: expect.any(Function),
                trackRecommenderPagination: expect.any(Function),
                trackRecommenderLoaded: expect.any(Function),
                buildUrgencyMessagingDimensions: expect.any(Function),
                roomAndBoard: {
                    trackNewRoomOrBoardClick: expect.any(Function),
                    trackNoAvailabilityError: expect.any(Function),
                    trackRoomAndBoardConfirmClick: expect.any(Function),
                    buildAmendRoomAndBoardProduct: expect.any(Function),
                    getRoomAndBoardType: expect.any(Function),
                    getRoomAndBoardsSuffixAndName: expect.any(Function),
                },
                changeHotel: {
                    clickOnRoomAndBoardChange: expect.any(Function),
                    clickOnTransferChange: expect.any(Function),
                    clickOnTransferConfirm: expect.any(Function),
                    priceJumpPopupInteractionEvent: expect.any(Function),
                    priceJumpPopupAppearEvent: expect.any(Function),
                    clickBookHotel: expect.any(Function),
                    clickLoadMoreAmendHotelList: expect.any(Function),
                    clickViewBookingFromAmendHotel: expect.any(Function),
                    trackLoadMoreAmendHotelList: expect.any(Function),
                },
            },
            seatMapStore: {
                isEnabledToBookSeats: true,
                isHideSeatMapWarningMessages: false,
                isSeatMapFlowEnabled: true,
                isSeatMapPostBookingFlowEnabled: true,
                seatsResponse: [],
                shouldOpenSeatMapForced: false,
                currency: 'GBP',
                isPremiumSeatsSelected: false,
                setOpenSeatMapForced: expect.any(Function),
                isSelectedSeatsUnavailableError: true,
                isSeatMapFlowDisabledError: true,
                clearSelectedSeatsUnavailableError: expect.any(Function),
                clearSeatMapFlowDisabledError: expect.any(Function),
                clearSelectedSeatsAndUpdateUrl: expect.any(Function),
                setIsSelectedSeatsUnavailableError: expect.any(Function),
                setSeatMapOpened: expect.any(Function),
                clearValidatedSeats: expect.any(Function),
                setValidatedSelectedSeats: expect.any(Function),
                fetchSeatMap: expect.any(Function),
            },
            amendDatesStore: mockAmendDatesStore,
            amendHotelStore: {
                feePP: 30,
            },
            amendRoomAndBoardStore: {},
            hotelsStore: {
                parentOffers: [mockedOffer, mockedOffer, mockedOffer, mockedOffer, mockedOffer, mockedOffer],
            },
            queryParamStore: {
                buildSearchQuery: expect.any(Function),
                isFlightPlusHotelFunnel: false,
            },
            searchStore: {
                searchTo: {
                    selectedParentDestinationCodesQuery: 'ES',
                },
            },
        });
    });

    it('should merge props with skeleton', () => {
        const mockStores = createMockStores({
            appStore: {
                isScreenLessMedium: false,
                testing: 'testing',
                isScreenExtraLarge: false,
                isScreenExtraSmall: false,
                isScreenLarge: false,
                isScreenMedium: true,
            },
            layoutStore: { getPhrase: 'phrase', testing2: 'testing2' },
            routerStore: { testing3: 'testing3' },
            searchStoresStore: { testing4: 'testing4' },
            marketStore: { testing5: 'testing5' },
            viewBookingStore: { booking: {}, isLoading: true },
            userStore: { anotherFunction: jest.fn() },
            holidayCreditStore: { testFn: jest.fn() },
            bookingStore: { testFn2: jest.fn() },
            trackingStore: { testFn3: jest.fn() },
            seatMapStore: { shouldOpenSeatMapForced: true },
            payBalanceStore: { testing6: 'testing6' },
            paymentStore: { testFn4: jest.fn() },
            amendPaymentStore: { testFn5: jest.fn() },
        });

        expect(mockStores).toStrictEqual({
            appStore: {
                testing: 'testing',
                isScreenLessMedium: false,
                isScreenMedium: true,
                isScreenExtraLarge: false,
                isScreenExtraSmall: false,
                isScreenLarge: false,
                isLoading: false,
            },
            layoutStore: {
                getSettingAsNumber: expect.any(Function),
                isCancelledBookingPage: false,
                isSearchResultsPage: false,
                isPromoPage: false,
                displayName: 'Spain',
                isEditMode: false,
                getPhrase: 'phrase',
                getSetting: expect.any(Function),
                testing2: 'testing2',
                basePath: '',
                sitePath: 'sitePath',
                updateLang: expect.any(Function),
                setFullUrl: expect.any(Function),
                setPageSearchSortOrder: expect.any(Function),
                setWhenDropdownExperimentTestVariant: expect.any(Function),
                holdLuggageCategoryCodes: expect.any(Array),
                sportEquipmentCategoryCodes: expect.any(Array),
                largeCabinBagCode: expect.any(Array),
                isPostBookingPages: false,
                isPaymentPage: false,
                isAmendPaymentPage: false,
                isViewBookingPage: false,
                isTradePortal: false,
                isConfirmPage: false,
                isExtrasPage: false,
                isConfirmationPage: false,
                minNumberOfDaysToDeparture: 1,
                isCheapestComparePriceOption: false,
                setIsCheapestComparePriceOption: expect.any(Function),
            },
            paymentStore: {
                selectDefaultPaymentOption: expect.any(Function),
                testFn4: expect.any(Function),
            },
            amendPaymentStore: {
                goBackToViewBooking: expect.any(Function),
                clearAmendPaymentStore: expect.any(Function),
                testFn5: expect.any(Function),
            },
            payBalanceStore: {
                booking: mockBooking,
                isFlightExternal: true,
                isLuxuryPackage: false,
                testing6: 'testing6',
            },
            routerStore: {
                redirectTo: expect.any(Function),
                redirectToExtrasPage: expect.any(Function),
                redirectToManageHubPage: expect.any(Function),
                redirectToMicroAppChangeTransferPage: expect.any(Function),
                redirectToMicroAppChangeFlightPage: expect.any(Function),
                redirectToMicroAppChangeDatePage: expect.any(Function),
                redirectToMicroAppChangeNamePage: expect.any(Function),
                redirectToMicroAppChangeSeatsPage: expect.any(Function),
                redirectToMicroAppChangeHotelPage: expect.any(Function),
                redirectToMicroAppChangeRoomAndBoardPage: expect.any(Function),
                testing3: 'testing3',
            },
            searchStoresStore: { testing4: 'testing4' },
            marketStore: {
                testing5: 'testing5',
                formatMoney: expect.any(Function),
                getFormattedNumber: expect.any(Function),
            },
            viewBookingStore: {
                isBookingOutOfSync: false,
                isPostTravelPage: false,
                isFlightAndHotelPackage: false,
                isLuxuryPackage: false,
                booking: {},
                toggleLoading: expect.any(Function),
                loadBooking: expect.any(Function),
                clearBooking: expect.any(Function),
                isBookingClearRequired: expect.any(Function),
                isFlightExternal: true,
                clearViewBookingPayload: expect.any(Function),
                setSuccessfulAmendmentStatus: expect.any(Function),
                amendBookingStatuses: [],
                allowanceRestrictions: {},
                successfulAmendmentStatus: null,
                isBookingCanceled: false,
                isLoading: true,
                isMicroAppManageMyHolidayAllowed: false,
                isMicroAppAmendTransferAllowed: false,
                isMicroAppAmendFlightsAllowed: false,
                isMicroAppAmendHotelAllowed: false,
                isMicroAppAmendMultiRoomAndBoardAllowed: false,
                isMicroAppAmendRoomAndBoardAllowed: false,
                isMicroAppAmendDateAllowed: false,
                isMicroAppAmendSeatsAllowed: false,
                isMicroAppAmendNameAllowed: false,
            },
            userStore: {
                setUserDetails: expect.any(Function),
                toggleLoginPopup: expect.any(Function),
                setRedirectUrl: expect.any(Function),
                setIsRedirectPreventedAfterLogin: expect.any(Function),
                resetPassword: expect.any(Function),
                rerenderForm: expect.any(Function),
                customerErrorHandler: expect.any(Function),
                formRerenderTrigger: expect.any(Function),
                setRememberMe: expect.any(Function),
                onLogin: expect.any(Function),
                initializeCustomerLogin: expect.any(Function),
                anotherFunction: expect.any(Function),
            },
            engageStore: {
                sendCustomEvent: expect.any(Function),
                sendPromoCodeEvent: expect.any(Function),
            },
            searchFiltersStore: {
                filters: [],
                selectedFilters: [],
            },
            holidayCreditStore: {
                startCreditBooking: expect.any(Function),
                testFn: expect.any(Function),
                selectedRefundType: 'credit',
                booking: mockBooking,
                isFlightExternal: true,
                isLuxuryPackage: false,
            },
            bookingStore: {
                isFlightExternal: true,
                isFlightAndHotelPackage: false,
                isPaymentReminderVisible: expect.any(Function),
                testFn2: expect.any(Function),
                extraLuggage: {},
                isLuxuryPackage: false,
                clearPackageValidation: expect.any(Function),
                validatePackage: expect.any(Function),
                validatePromoCode: expect.any(Function),
                setSelectedOfferPrices: expect.any(Function),
            },
            trackingStore: {
                initializePageLoadObject: expect.any(Function),
                trackSeatMapSitTogetherClick: expect.any(Function),
                trackSeatMapSitTogetherImpression: expect.any(Function),
                trackHomepageAction: expect.any(Function),
                trackModuleClick: expect.any(Function),
                trackGenericAmendmentAction: expect.any(Function),
                testFn3: expect.any(Function),
                trackSuccessfulAmendment: expect.any(Function),
                trackCustomError: expect.any(Function),
                addToDataLayer: expect.any(Function),
                trackEventWithParams: expect.any(Function),
                trackGenericAmendmentActionWithGuests: expect.any(Function),
                buildUrgencyMessagingDimensions: expect.any(Function),
                trackRecommenderHotelClick: expect.any(Function),
                trackRecommenderInteraction: expect.any(Function),
                trackRecommenderPagination: expect.any(Function),
                trackRecommenderLoaded: expect.any(Function),
                trackManageHubClick: expect.any(Function),
                roomAndBoard: {
                    trackNewRoomOrBoardClick: expect.any(Function),
                    trackNoAvailabilityError: expect.any(Function),
                    trackRoomAndBoardConfirmClick: expect.any(Function),
                    getRoomAndBoardType: expect.any(Function),
                    buildAmendRoomAndBoardProduct: expect.any(Function),
                    getRoomAndBoardsSuffixAndName: expect.any(Function),
                },
                changeHotel: {
                    clickOnRoomAndBoardChange: expect.any(Function),
                    clickOnTransferChange: expect.any(Function),
                    clickOnTransferConfirm: expect.any(Function),
                    priceJumpPopupAppearEvent: expect.any(Function),
                    priceJumpPopupInteractionEvent: expect.any(Function),
                    clickBookHotel: expect.any(Function),
                    clickLoadMoreAmendHotelList: expect.any(Function),
                    clickViewBookingFromAmendHotel: expect.any(Function),
                    trackLoadMoreAmendHotelList: expect.any(Function),
                },
            },
            seatMapStore: {
                isEnabledToBookSeats: true,
                isHideSeatMapWarningMessages: false,
                isSeatMapFlowEnabled: true,
                isSeatMapPostBookingFlowEnabled: true,
                seatsResponse: [],
                shouldOpenSeatMapForced: true,
                currency: 'GBP',
                isPremiumSeatsSelected: false,
                setOpenSeatMapForced: expect.any(Function),
                isSelectedSeatsUnavailableError: true,
                isSeatMapFlowDisabledError: true,
                clearSelectedSeatsUnavailableError: expect.any(Function),
                clearSeatMapFlowDisabledError: expect.any(Function),
                clearSelectedSeatsAndUpdateUrl: expect.any(Function),
                setIsSelectedSeatsUnavailableError: expect.any(Function),
                setSeatMapOpened: expect.any(Function),
                clearValidatedSeats: expect.any(Function),
                setValidatedSelectedSeats: expect.any(Function),
                fetchSeatMap: expect.any(Function),
            },
            amendDatesStore: mockAmendDatesStore,
            amendHotelStore: {
                feePP: 30,
            },
            amendRoomAndBoardStore: {},
            hotelsStore: {
                parentOffers: [mockedOffer, mockedOffer, mockedOffer, mockedOffer, mockedOffer, mockedOffer],
            },
            queryParamStore: {
                buildSearchQuery: expect.any(Function),
                isFlightPlusHotelFunnel: false,
            },
            searchStore: {
                searchTo: {
                    selectedParentDestinationCodesQuery: 'ES',
                },
            },
        });
    });
});
