import { deepClone } from 'frontend/utils/array.utils';
import { CreditType } from 'models/enum/CreditType';

import { mockBooking } from './booking';
import { mockedOffer } from './offer';
import { mockAmendDatesStore } from './stores';
import { mockBaseTrackingProduct } from './tracking';

export const createMockStores = (stores = {} as any) => ({
    ...stores,
    layoutStore: {
        getSettingAsNumber: jest.fn(),
        setWhenDropdownExperimentTestVariant: jest.fn(),
        isCancelledBookingPage: false,
        isSearchResultsPage: false,
        isPromoPage: false,
        displayName: 'Spain',
        getPhrase: jest.fn(p => p),
        getSetting: jest.fn(setting => setting),
        basePath: '',
        sitePath: 'sitePath',
        updateLang: jest.fn(),
        setFullUrl: jest.fn(),
        setPageSearchSortOrder: jest.fn(),
        holdLuggageCategoryCodes: ['BAGE'],
        sportEquipmentCategoryCodes: ['SEO', 'SEC'],
        largeCabinBagCode: ['CABI'],
        isEditMode: false,
        isPostBookingPages: false,
        isPaymentPage: false,
        isAmendPaymentPage: false,
        isViewBookingPage: false,
        isTradePortal: false,
        isConfirmPage: false,
        isExtrasPage: false,
        isConfirmationPage: false,
        minNumberOfDaysToDeparture: 1,
        isCheapestComparePriceOption: false,
        setIsCheapestComparePriceOption: jest.fn(),
        ...stores.layoutStore,
    },
    paymentStore: {
        selectDefaultPaymentOption: jest.fn(),
        ...stores.paymentStore,
    },
    amendPaymentStore: {
        goBackToViewBooking: jest.fn(),
        clearAmendPaymentStore: jest.fn(),
        ...stores.amendPaymentStore,
    },
    payBalanceStore: {
        booking: mockBooking,
        isFlightExternal: true,
        isLuxuryPackage: false,
        ...stores.payBalanceStore,
    },
    appStore: {
        isScreenMedium: true,
        isScreenLessMedium: false,
        isScreenExtraLarge: false,
        isScreenExtraSmall: false,
        isScreenLarge: false,
        isLoading: false,
        ...stores.appStore,
    },
    routerStore: {
        redirectToExtrasPage: jest.fn(),
        redirectTo: jest.fn(),
        redirectToManageHubPage: jest.fn(),
        redirectToMicroAppChangeTransferPage: jest.fn(),
        redirectToMicroAppChangeFlightPage: jest.fn(),
        redirectToMicroAppChangeDatePage: jest.fn(),
        redirectToMicroAppChangeNamePage: jest.fn(),
        redirectToMicroAppChangeSeatsPage: jest.fn(),
        redirectToMicroAppChangeHotelPage: jest.fn(),
        redirectToMicroAppChangeRoomAndBoardPage: jest.fn(),
        ...stores.routerStore,
    },
    searchFiltersStore: {
        filters: [],
        selectedFilters: [],
        ...stores.searchFiltersStore,
    },
    marketStore: {
        formatMoney: jest.fn(a => `£${a}`),
        getFormattedNumber: jest.fn(number => `${number}`),
        ...stores.marketStore,
    },
    viewBookingStore: {
        isPostTravelPage: false,
        booking: mockBooking,
        toggleLoading: jest.fn(),
        loadBooking: jest.fn(),
        clearBooking: jest.fn(),
        clearViewBookingPayload: jest.fn(),
        isBookingClearRequired: jest.fn(() => true),
        isLoading: false,
        isBookingCanceled: false,
        isBookingOutOfSync: false,
        isMicroAppManageMyHolidayAllowed: false,
        isMicroAppAmendTransferAllowed: false,
        isMicroAppAmendFlightsAllowed: false,
        isMicroAppAmendHotelAllowed: false,
        isMicroAppAmendRoomAndBoardAllowed: false,
        isMicroAppAmendMultiRoomAndBoardAllowed: false,
        isMicroAppAmendDateAllowed: false,
        isMicroAppAmendSeatsAllowed: false,
        isMicroAppAmendNameAllowed: false,
        successfulAmendmentStatus: null,
        amendBookingStatuses: [],
        allowanceRestrictions: {},
        setSuccessfulAmendmentStatus: jest.fn(),
        isFlightExternal: true,
        isLuxuryPackage: false,
        isFlightAndHotelPackage: false,
        ...stores.viewBookingStore,
    },
    userStore: {
        setUserDetails: jest.fn(),
        toggleLoginPopup: jest.fn(),
        setRedirectUrl: jest.fn(),
        setIsRedirectPreventedAfterLogin: jest.fn(),
        resetPassword: jest.fn(),
        rerenderForm: jest.fn(),
        customerErrorHandler: jest.fn(),
        formRerenderTrigger: jest.fn(),
        setRememberMe: jest.fn(),
        onLogin: jest.fn(),
        initializeCustomerLogin: jest.fn(),
        ...stores.userStore,
    },
    engageStore: {
        sendCustomEvent: jest.fn(),
        sendPromoCodeEvent: jest.fn(),
        ...stores.engageStore,
    },
    holidayCreditStore: {
        startCreditBooking: jest.fn(),
        selectedRefundType: CreditType.Credit,
        booking: mockBooking,
        isLuxuryPackage: false,
        isFlightExternal: true,
        ...stores.holidayCreditStore,
    },
    bookingStore: {
        isPaymentReminderVisible: jest.fn(),
        isFlightExternal: true,
        extraLuggage: {},
        isLuxuryPackage: false,
        isFlightAndHotelPackage: false,
        clearPackageValidation: jest.fn(),
        validatePackage: jest.fn(),
        validatePromoCode: jest.fn(),
        setSelectedOfferPrices: jest.fn(),
        ...stores.bookingStore,
    },
    trackingStore: {
        initializePageLoadObject: jest.fn(),
        trackSeatMapSitTogetherClick: jest.fn(),
        trackSeatMapSitTogetherImpression: jest.fn(),
        trackModuleClick: jest.fn(),
        trackHomepageAction: jest.fn(),
        trackGenericAmendmentAction: jest.fn(),
        trackSuccessfulAmendment: jest.fn(),
        trackCustomError: jest.fn(),
        trackGenericAmendmentActionWithGuests: jest.fn(),
        trackEventWithParams: jest.fn(),
        addToDataLayer: jest.fn(),
        buildUrgencyMessagingDimensions: jest.fn(),
        trackRecommenderHotelClick: jest.fn(),
        trackRecommenderInteraction: jest.fn(),
        trackRecommenderPagination: jest.fn(),
        trackRecommenderLoaded: jest.fn(),
        trackManageHubClick: jest.fn(),
        roomAndBoard: {
            trackNewRoomOrBoardClick: jest.fn(),
            trackNoAvailabilityError: jest.fn(),
            trackRoomAndBoardConfirmClick: jest.fn(),
            getRoomAndBoardsSuffixAndName: jest.fn(() => ({ name: 'suffix_name' })),
            getRoomAndBoardType: jest.fn().mockImplementation(() => 'rbc_type'),
            buildAmendRoomAndBoardProduct: jest.fn().mockImplementation(() => deepClone(mockBaseTrackingProduct)),
        },
        changeHotel: {
            clickOnTransferChange: jest.fn(),
            clickOnRoomAndBoardChange: jest.fn(),
            clickOnTransferConfirm: jest.fn(),
            priceJumpPopupInteractionEvent: jest.fn(),
            priceJumpPopupAppearEvent: jest.fn(),
            clickBookHotel: jest.fn(),
            clickLoadMoreAmendHotelList: jest.fn(),
            clickViewBookingFromAmendHotel: jest.fn(),
            trackLoadMoreAmendHotelList: jest.fn(),
        },
        ...stores.trackingStore,
    },
    seatMapStore: {
        isSeatMapFlowEnabled: true,
        isSeatMapPostBookingFlowEnabled: true,
        seatsResponse: [],
        setOpenSeatMapForced: jest.fn(),
        isPremiumSeatsSelected: false,
        shouldOpenSeatMapForced: false,
        currency: 'GBP',
        isSelectedSeatsUnavailableError: true,
        isSeatMapFlowDisabledError: true,
        clearSelectedSeatsUnavailableError: jest.fn(),
        clearSeatMapFlowDisabledError: jest.fn(),
        clearSelectedSeatsAndUpdateUrl: jest.fn(() => Promise.resolve()),
        setIsSelectedSeatsUnavailableError: jest.fn(),
        setSeatMapOpened: jest.fn(),
        clearValidatedSeats: jest.fn(),
        setValidatedSelectedSeats: jest.fn(),
        fetchSeatMap: jest.fn(),
        isEnabledToBookSeats: true,
        isHideSeatMapWarningMessages: false,
        ...stores.seatMapStore,
    },
    amendDatesStore: {
        ...mockAmendDatesStore,
        ...stores.amendDatesStore,
    },
    amendHotelStore: {
        feePP: 30,
        ...stores.amendHotelStore,
    },
    amendRoomAndBoardStore: {
        ...stores.amendRoomAndBoardStore,
    },
    hotelsStore: {
        parentOffers: [mockedOffer, mockedOffer, mockedOffer, mockedOffer, mockedOffer, mockedOffer],
        ...stores.hotelsStore,
    },
    queryParamStore: {
        buildSearchQuery: jest.fn(),
        isFlightPlusHotelFunnel: false,
        ...stores.queryParamStore,
    },
    searchStore: {
        searchTo: {
            selectedParentDestinationCodesQuery: 'ES',
        },
        ...stores.searchStore,
    },
});
