import { IAmendPaymentInfo, IAmendTransport } from 'models/data/IAmendBookingFlights';
import { IOffer } from 'models/data/IOffer';
import { IRoute } from 'models/data/IRoute';
import { RouteDirection } from 'models/enum/RouteDirection';
import { TransferType } from 'models/enum/transfer/TransferType';

import { mockPromoCodeBreakdown } from './promocode';
import { mockUnitRoom } from './room';

export const mockOutboundFlight = {
    arrDate: '2023-05-11T16:25:00+00:00',
    arrLocation: 'Costa Teguise',
    arrName: 'Lanzarote',
    arrItemName: 'Lanzarote',
    arrPt: 'ACE',
    bkgCls: 'Z',
    car: 'EZY',
    depDate: '2023-05-11T12:10:00+00:00',
    depLocation: 'London',
    depName: 'London Gatwick',
    depItemName: 'London Gatwick',
    depPt: 'LGW',
    direction: 'outbound',
    extRefId: 'K6578ZK',
    fltNo: '6453',
    id: '170430/3978',
    isExt: true,
    paxs: [{ paxId: '1' }, { paxId: '2' }],
} as IRoute;

export const mockInboundFlight = {
    arrDate: '2023-05-19T00:45:00+00:00',
    arrLocation: 'London',
    arrName: 'London Gatwick',
    arrItemName: 'London Gatwick',
    arrPt: 'LGW',
    bkgCls: 'Z',
    car: 'EZY',
    depDate: '2023-05-18T20:40:00+00:00',
    depLocation: 'Costa Teguise',
    depName: 'Lanzarote',
    depItemName: 'Lanzarote',
    depPt: 'ACE',
    direction: 'inbound',
    extRefId: 'K6578ZK',
    fltNo: '6572',
    id: '170430/2978',
    isExt: true,
    paxs: [{ paxId: '1' }, { paxId: '2' }],
} as IRoute;

export const mockValidatedFlights = {
    transports: [
        {
            amendmentCharges: 226.0,
            packagePrice: 200,
            packagePricePP: 100,
            amendmentPaymentInfo: {
                amendmentCharges: 226.0,
                amendmentChargesWithoutFees: 200.0,
                feesPerPersons: [
                    {
                        feesCount: 13,
                        feesPerPersonAmount: 2,
                    },
                ],
                packagePriceWithFees: 1226,
                packagePriceWithoutFees: 1200,
                totalFeesAmount: 26,
            } as IAmendPaymentInfo,
            promoCodeBreakDown: mockPromoCodeBreakdown,
            routes: [
                {
                    id: 'E0852ea5bdfca278c9dfeabc65fea9917',
                    cycDate: '2023-05-24',
                    depPt: 'LGW',
                    code: 'LGW',
                    depDate: '2023-05-24T12:20:00+00:00',
                    depName: 'London Gatwick',
                    depLocation: 'London',
                    arrPt: 'ALC',
                    arrDate: '2023-05-24T15:55:00+00:00',
                    arrName: 'Alicante',
                    arrLocation: 'Spain',
                    routeCd: 'ALCLGW3T',
                    avail: 8,
                    fltNo: 'EZY8111',
                    car: 'EZY',
                    direction: 'outbound',
                    isExt: true,
                    bkgCls: 'Z',
                },
                {
                    id: 'E71e41ec2b0984df98929bdae00cb85a0',
                    cycDate: '2023-05-27',
                    depPt: 'ALC',
                    depDate: '2023-05-27T16:30:00+00:00',
                    depName: 'Alicante',
                    depLocation: 'Spain',
                    arrPt: 'LGW',
                    arrDate: '2023-05-27T18:05:00+00:00',
                    arrName: 'London Gatwick',
                    arrLocation: 'London',
                    routeCd: 'LGWALC6T',
                    avail: 149,
                    fltNo: 'EZY8114',
                    car: 'EZY',
                    direction: 'inbound',
                    isExt: true,
                },
            ],
            errataFlightInfo: [
                'Errata for Kacper',
                '<span>We will <strong>remove</strong> the <em>refund</em> amount from your <u>holiday</u> balance Please confirm your changes. <span>We will remove the refund amount from your holiday balance Please confirm your changes.</span></span>',
            ],
        },
        {
            amendmentCharges: 234.0,
            packagePrice: 300,
            packagePricePP: 150,
            routes: [
                {
                    id: 'E0852ea5bdfca278c9dfeabc65fea9917',
                    cycDate: '2023-05-24',
                    depPt: 'LGW',
                    code: 'LGW',
                    depDate: '2023-05-24T12:20:00+00:00',
                    depName: 'London Gatwick',
                    depLocation: 'London',
                    arrPt: 'ALC',
                    arrDate: '2023-05-24T15:55:00+00:00',
                    arrName: 'Alicante',
                    arrLocation: 'Spain',
                    routeCd: 'ALCLGW3T',
                    avail: 8,
                    fltNo: 'EZY8111',
                    car: 'EZY',
                    direction: 'outbound',
                    isExt: true,
                    bkgCls: 'Z',
                },
                {
                    id: 'E9e93479c993bbd9664765bb6ecd37c81',
                    cycDate: '2023-05-27',
                    depPt: 'ALC',
                    code: 'ALC',
                    depDate: '2023-05-27T13:40:00+00:00',
                    depName: 'Alicante',
                    depLocation: 'Spain',
                    arrPt: 'LGW',
                    arrDate: '2023-05-27T15:20:00+00:00',
                    arrName: 'London Gatwick',
                    arrLocation: 'London',
                    routeCd: 'LGWALC6T',
                    avail: 145,
                    fltNo: 'EZY8112',
                    car: 'EZY',
                    direction: 'inbound',
                    isExt: true,
                    bkgCls: 'Y',
                },
            ],
            errataFlightInfo: [
                'Errata for Kacper',
                '<span>We will <strong>remove</strong> the <em>refund</em> amount from your <u>holiday</u> balance Please confirm your changes. <span>We will remove the refund amount from your holiday balance Please confirm your changes.</span></span>',
            ],
        },
        {
            amendmentCharges: 226.0,
            packagePrice: 200,
            packagePricePP: 100,
            routes: [
                {
                    id: 'E0852ea5bdfca278c9dfeabc65fea9922',
                    cycDate: '2023-05-24',
                    depPt: 'LGW',
                    code: 'LGW',
                    depDate: '2023-05-24T12:20:00+00:00',
                    depName: 'London Gatwick',
                    depLocation: 'London',
                    arrPt: 'ALC',
                    arrDate: '2023-05-24T15:55:00+00:00',
                    arrName: 'Alicante',
                    arrLocation: 'Spain',
                    routeCd: 'ALCLGW3T',
                    avail: 8,
                    fltNo: 'EZY8111',
                    car: 'EZY',
                    direction: 'outbound',
                    isExt: true,
                    bkgCls: 'Z',
                },
                {
                    id: 'E71e41ec2b0984df98929bdae00cb8511',
                    cycDate: '2023-05-27',
                    depPt: 'ALC',
                    code: 'ALC',
                    depDate: '2023-05-27T16:30:00+00:00',
                    depName: 'Alicante',
                    depLocation: 'Spain',
                    arrPt: 'LGW',
                    arrDate: '2023-05-27T18:05:00+00:00',
                    arrName: 'London Gatwick',
                    arrLocation: 'London',
                    routeCd: 'LGWALC6T',
                    avail: 149,
                    fltNo: 'EZY8114',
                    car: 'EZY',
                    direction: 'inbound',
                    isExt: true,
                    bkgCls: 'Y',
                },
            ],
            errataFlightInfo: [
                'Errata for Kacper',
                '<span>We will <strong>remove</strong> the <em>refund</em> amount from your <u>holiday</u> balance Please confirm your changes. <span>We will remove the refund amount from your holiday balance Please confirm your changes.</span></span>',
            ],
        },
        {
            amendmentCharges: 226.0,
            packagePrice: 200,
            packagePricePP: 100,
            routes: [
                {
                    id: 'E0852ea5bdfca278c9dfeabc65fea9944',
                    cycDate: '2023-05-24',
                    depPt: 'LGW',
                    code: 'LGW',
                    depDate: '2023-05-24T12:20:00+00:00',
                    depName: 'London Gatwick',
                    depLocation: 'London',
                    arrPt: 'ALC',
                    arrDate: '2023-05-24T15:55:00+00:00',
                    arrName: 'Alicante',
                    arrLocation: 'Spain',
                    routeCd: 'ALCLGW3T',
                    avail: 8,
                    fltNo: 'EZY8111',
                    car: 'EZY',
                    direction: 'outbound',
                    isExt: true,
                    bkgCls: 'Z',
                },
                {
                    id: 'E71e41ec2b0984df98929bdae00cb8533',
                    cycDate: '2023-05-27',
                    depPt: 'ALC',
                    code: 'ALC',
                    depDate: '2023-05-27T16:30:00+00:00',
                    depName: 'Alicante',
                    depLocation: 'Spain',
                    arrPt: 'LGW',
                    arrDate: '2023-05-27T18:05:00+00:00',
                    arrName: 'London Gatwick',
                    arrLocation: 'London',
                    routeCd: 'LGWALC6T',
                    avail: 149,
                    fltNo: 'EZY8114',
                    car: 'EZY',
                    direction: 'inbound',
                    isExt: true,
                    bkgCls: 'Y',
                },
            ],
            errataFlightInfo: [
                'Errata for Kacper',
                '<span>We will <strong>remove</strong> the <em>refund</em> amount from your <u>holiday</u> balance Please confirm your changes. <span>We will remove the refund amount from your holiday balance Please confirm your changes.</span></span>',
            ],
        },
    ] as IAmendTransport[],
};

export const mockFlightsRoutes = [mockOutboundFlight, mockInboundFlight];

export const mockFlightsOffers: IOffer[] = [
    {
        transferPrice: 0.0,
        discountAmount: 0.0,
        distanceToOriginalAirport: 10,
        seatsPrice: 0.0,
        totalPrice: 4317.16,
        id: '0',
        date: '2023-08-26T00:00:00',
        stay: 5,
        price: 4317.16,
        pricePP: 1439.05,
        deposit: 180.0,
        accom: {
            date: '2023-08-26T00:00:00',
            stay: 5,
            id: 'ESMJ0017',
            packageId: '2183941081/2/2063/5',
            code: 'ESMJ0017',
            unit: [mockUnitRoom],
            prom: 'EUBO',
            isExt: false,
            latitude: 39.5024,
            longitude: 2.5327,
        },
        transport: {
            errataFlightInfo: ['Flight errata'],
            routes: [
                {
                    id: '2179873450/755956',
                    cycDate: '2023-08-26',
                    depPt: 'BRS',
                    depDate: '2023-08-26T12:45:00+00:00',
                    depName: 'Bristol',
                    depItemName: 'Bristol',
                    depLocation: 'United Kingdom',
                    arrPt: 'PMI',
                    arrDate: '2023-08-26T16:05:00+00:00',
                    arrName: 'Palma',
                    arrItemName: 'Palma',
                    arrLocation: 'Spain',
                    routeCd: 'PMIBRS6ABRSPMI',
                    avail: 21,
                    fltNo: 'EZY2711',
                    car: 'EZY',
                    direction: RouteDirection.Outbound,
                    isExt: false,
                },
                {
                    id: '2180357869/801791',
                    cycDate: '2023-08-31',
                    depPt: 'PMI',
                    depDate: '2023-08-31T14:35:00+00:00',
                    depName: 'Palma',
                    depItemName: 'Palma',
                    depLocation: 'Spain',
                    arrPt: 'BRS',
                    arrDate: '2023-08-31T16:05:00+00:00',
                    arrName: 'Bristol',
                    arrItemName: 'Bristol',
                    arrLocation: 'United Kingdom',
                    routeCd: 'PMIBRS4APMIBRS',
                    avail: 10,
                    fltNo: 'EZY2712',
                    car: 'EZY',
                    direction: RouteDirection.Inbound,
                    isExt: false,
                },
            ],
        },
        transfers: [
            {
                type: TransferType.Shared,
                iconUrl: 'Transfer icon source',
                code: 'JUMB011161SS',
                name: 'Shared Transfer Required',
                autoInclude: false,
                quantity: 3,
                method: 'PP',
                mcMethod: 'MANY',
                price: 66.42,
                minPax: 0,
                maxPax: 0,
                isHidden: false,
            } as any,
        ],
        hasDistressedFlights: false,
        modifiedPrice: 0.0,
        seatSelection: [{ sectorId: '1', flightNumber: '7258', isSeatReservationPossible: true }],
        extraLuggageInfo: {
            items: [
                {
                    itemCode: 'LUS',
                },
            ],
        },
    },
    {
        transferPrice: 0.0,
        discountAmount: 0.0,
        seatsPrice: 0.0,
        totalPrice: 3963.16,
        id: '2',
        date: '2023-08-26T00:00:00',
        stay: 5,
        price: 3963.16,
        pricePP: 1321.05,
        deposit: 180.0,
        accom: {
            date: '2023-08-26T00:00:00',
            stay: 5,
            id: 'ESMJ0017',
            packageId: '2183941081/2/2063/5',
            code: 'ESMJ0017',
            unit: [
                {
                    code: 'JWS01',
                    price: 3488.74,
                    pricePP: 1162.91,
                    discount: 202.26,
                    discountPP: 67.42,
                    avail: 9,
                    isFreeForKids: false,
                    board: 'AI',
                    occupation: { adults: 3, children: 0, infants: 0, paxIds: [1, 2, 3], childAges: [] },
                },
            ] as any,
            prom: 'EUBO',
            isExt: false,
            latitude: 39.5024,
            longitude: 2.5327,
        },
        transport: {
            routes: [
                {
                    id: '2179869764/755595',
                    cycDate: '2023-08-26',
                    depPt: 'BFS',
                    depDate: '2023-08-27T20:50:00+00:00',
                    depName: 'Belfast International',
                    depLocation: 'Belfast',
                    arrPt: 'PMI',
                    arrDate: '2023-08-27T00:40:00+00:00',
                    arrName: 'Palma',
                    arrLocation: 'Spain',
                    routeCd: 'PMIBFS6BBFSPMI',
                    avail: 20,
                    fltNo: 'EZY7258',
                    car: 'EZY',
                    direction: RouteDirection.Outbound,
                    isExt: false,
                },
                {
                    id: '2180354259/801430',
                    cycDate: '2023-08-31',
                    depPt: 'PMI',
                    depDate: '2023-08-30T18:20:00+00:00',
                    depName: 'Palma',
                    depLocation: 'Spain',
                    arrPt: 'BFS',
                    arrDate: '2023-08-31T20:15:00+00:00',
                    arrName: 'Belfast International',
                    arrLocation: 'Belfast',
                    routeCd: 'PMIBFS4BPMIBFS',
                    avail: 20,
                    fltNo: 'EZY7257',
                    car: 'EZY',
                    direction: RouteDirection.Inbound,
                    isExt: false,
                },
            ],
        },
        transfers: [
            {
                type: TransferType.Shared,
                code: 'JUMB011161SS',
                name: 'Shared Transfer Required',
                autoInclude: false,
                quantity: 3,
                method: 'PP',
                mcMethod: 'MANY',
                price: 66.42,
                minPax: 0,
                maxPax: 0,
                isHidden: false,
            } as any,
        ],
        hasDistressedFlights: false,
        seatSelection: [{ sectorId: '1', flightNumber: '7258', isSeatReservationPossible: false }],
        modifiedPrice: 0.0,
    } as any,
];
