---
ID: "073fcdf6-15ec-4f33-800a-1f4ace8bcefc"
Parent: "3c2d4e01-b546-4cb6-9157-21de94bee36a"
Template: "3c2d4e01-b546-4cb6-9157-21de94bee36a"
Path: /sitecore/templates/Foundation/HotelBeds/Reports/Hotel Faciltites Resync Record/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210705T105447Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
