---
ID: "c46beed3-2352-4239-a14c-48279133f929"
Parent: "9fc9c85f-38e5-4ade-aceb-3cfcd092b15f"
Template: "9fc9c85f-38e5-4ade-aceb-3cfcd092b15f"
Path: /sitecore/templates/Foundation/Presentation/Rendering Parameters/Sliced Banner Parameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1218a168-1813-4916-8a89-1d97338d2a5e"
      Hint: CTATheme
      Value: outlined
    - ID: "1f7ea371-5e76-4427-b61c-86a327e09de9"
      Hint: TitleStyle
      Value: thin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191203T164402Z
    - ID: "4f0d6e28-3fe7-4330-907c-6627ccbfbb81"
      Hint: TextAlignment
      Value: right
