---
ID: "4e2d6400-e4af-46f1-8963-8e526991b17d"
Parent: "ab8ab94b-efed-4f2f-96a8-78d830933228"
Template: "ab8ab94b-efed-4f2f-96a8-78d830933228"
Path: /sitecore/templates/Feature/Destinations/View Booking/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191226T130642Z
    - ID: "480f92d7-eb6c-4395-a777-4bfb8a940da8"
      Hint: LoadingBookingTitle
      Value: We're searching for your booking
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "93735c73-3315-4ba5-ba02-1a72f6b8437d"
      Hint: LoadingBookingSubtitle
      Value: This may take a few seconds
