---
ID: "5fec55c8-a3c5-4626-8f26-75bdec63ed95"
Parent: "2c5717af-0f94-4353-999b-e35bfc809050"
Template: "2c5717af-0f94-4353-999b-e35bfc809050"
Path: /sitecore/templates/Foundation/Presentation/Base/_Base Name/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190612T154140Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "f9d78bf5-6aec-4b4b-895a-c10ad6aebae2"
      Hint: Name
      Value: 
