---
ID: "fd58cbae-5d8a-4f05-a33e-78d1c291c14d"
Parent: "94b56bd5-19c6-478a-b008-685e34ae6164"
Template: "94b56bd5-19c6-478a-b008-685e34ae6164"
Path: /sitecore/templates/Feature/PageContent/SEO/SEO Tabs Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{FF713977-4B0F-4EA5-8A64-BDFC11849E02}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240729T113340Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
