---
ID: "7e880a1b-ab64-418f-ad6c-62fe6cce0089"
Parent: "33b3542e-1316-40ca-8971-1cdb3c1d452d"
Template: "33b3542e-1316-40ca-8971-1cdb3c1d452d"
Path: "/sitecore/templates/Project/Holidays/Pages/Destinations/Region - City/__Standard Values"
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4696E3CC-7DA0-4264-BF00-B6E49C11B857}">
        <r
          ds="{43379DA2-1D47-412C-B527-3889F16BF4B3}"
          id="{CFDDA56D-9D28-45DE-BED6-FF67AC4C38B5}"
          par=""
          ph="/header"
          uid="{CEE4C8DC-58C5-45DF-90DF-C626133D9475}" />
        <r
          ds=""
          id="{216FE85C-936E-4135-894B-E7DE8BF8A4C2}"
          par="AlternativeView&amp;IsSticky=1&amp;ShowTitle=1&amp;RedirectToSearchResults=1&amp;EnableNewDesign&amp;ForceReloadChildren"
          ph="/body/floating-searchpod-{72e319f0-0dea-4c64-b472-054583342cff}-0"
          uid="{4B0A1694-93A1-4539-B950-DCF5EBE4FB28}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{8697E1B1-A31B-4641-B6F9-0DBC289C5B59}"
          par="TextOrder=Subtitle%20and%20Title&amp;IsTriangleStart&amp;ShowImageGradient=1&amp;Height=400&amp;FontSize&amp;Variant=Translucent%20Bottom%20Stripe"
          ph="body"
          uid="{72E319F0-0DEA-4C64-B472-054583342CFF}" />
        <r
          ds=""
          id="{94A6DA9E-F932-46DE-B745-1665F7C51156}"
          par=""
          ph="/body/hero-banner-top-section-{72e319f0-0dea-4c64-b472-054583342cff}-0"
          uid="{4DF35DDF-E334-4497-9416-E64B3335E1BC}" />
        <r
          ds=""
          id="{CB1BEF31-64D1-4715-A45E-F2BB7A287F0A}"
          par=""
          ph="/body/live-price-{72e319f0-0dea-4c64-b472-054583342cff}-0"
          uid="{96E1DF4F-1FC8-4A81-995D-6A06D4F52818}" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom"
          ph="body"
          uid="{DD7E3F1D-025E-4748-926A-1FC2EFB8C947}" />
        <r
          ds=""
          id="{C425F05C-0B8B-4EEC-B528-360E18F4EB17}"
          par="EnableLazyLoading=1&amp;EnableSeoReadMoreText=1&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{DD7E3F1D-025E-4748-926A-1FC2EFB8C947}-0"
          uid="{5BCB23F8-18F3-4BEF-8BC0-78134D78BDE8}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="body"
          uid="{76AFA34A-40A1-436C-BC63-1EC31FA63322}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{92E59D27-A78E-4C71-87F6-27046C6136CC}"
          par="PaddingSize=16px&amp;DisableLazyLoading&amp;ForceReloadChildren&amp;EnableLazyLoading=1"
          ph="/body/component-wrapper-inner-{76AFA34A-40A1-436C-BC63-1EC31FA63322}-0"
          uid="{89E8B155-FFF7-4391-8D8B-4168002484FF}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{76AFA34A-40A1-436C-BC63-1EC31FA63322}-0"
          uid="{BC89D7C2-1926-4D97-A663-E36DB3D6AB60}"
          ccb="Clear on publish" />
        <r
          ds="{D8AB9643-EBF3-4961-B33D-09CCE7A231B1}"
          id="{73293589-FB88-4DA0-901B-7FDBC9311583}"
          par="DisableLazyLoading&amp;CentralLatitude&amp;InitialZoom=8&amp;CentralLongitude&amp;MinZoom=7&amp;MaxZoom=24&amp;Zoom&amp;ZoomControl=1&amp;ExpandedControl&amp;ForceReloadChildren&amp;EnableLazyLoading=1"
          ph="/body/component-wrapper-inner-{76AFA34A-40A1-436C-BC63-1EC31FA63322}-0/component-wrapper-inner-{BC89D7C2-1926-4D97-A663-E36DB3D6AB60}-0"
          uid="{61AE01CD-43D4-4425-A7B9-8DE2A0879589}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{43546A28-D231-4287-96D2-25DEF529F1A5}"
          par="DescriptionPosition&amp;TruncateTextOnMobile&amp;PaddingSize&amp;EnableLazyLoading=1&amp;TitleTag&amp;TitlePosition&amp;TitleFontStyle=default&amp;TitleFontSize&amp;TitleWeight&amp;ClassName&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{76AFA34A-40A1-436C-BC63-1EC31FA63322}-0"
          uid="{BFB1B686-3FE0-4D5C-B09E-50A2B8CD8328}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{CCFE4FD5-1E40-4641-9754-C9AA95F32A8A}"
          par="LimitBounds&amp;EnableLazyLoading=1&amp;InitialZoom&amp;MinZoom&amp;MaxZoom&amp;ZoomControl&amp;ExpandedControl&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{76AFA34A-40A1-436C-BC63-1EC31FA63322}-0"
          uid="{7276095D-949A-4E07-8A7A-7E02957259CA}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="body"
          uid="{B1D448E2-6BF6-4646-A1B6-CB4FF0999938}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{92E59D27-A78E-4C71-87F6-27046C6136CC}"
          par="PaddingSize=16px&amp;DisableLazyLoading&amp;ForceReloadChildren&amp;EnableLazyLoading=1"
          ph="/body/component-wrapper-inner-{B1D448E2-6BF6-4646-A1B6-CB4FF0999938}-0"
          uid="{DF86866C-7512-409F-A2C7-07B3D215B51C}"
          ccb="Clear on publish" />
        <r
          ds="{85630FDE-9EEE-4ED5-B8FE-27671EB5307C}"
          id="{D50F78F7-73DC-4A39-A807-BEC8EDA7BC13}"
          par="EnableLazyLoading=1&amp;MaximumNumberSlider=9&amp;IsWhiteBackground=1&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{B1D448E2-6BF6-4646-A1B6-CB4FF0999938}-0"
          uid="{AF40485C-7C4E-486B-9D7E-D1EAE2185C4F}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground=1&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="body"
          uid="{857FD1A8-0476-4BEA-B26B-40A89276B93E}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{2D6A5BC4-CE48-4619-AC42-02D1C94D8B44}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{857fd1a8-0476-4bea-b26b-40a89276b93e}-0"
          uid="{C8BA158C-4019-4C3E-B0C2-91344664A664}"
          ccb="Clear on publish" />
        <r
          ds="/sitecore/content/EasyJet/Holidays/Data/View Holidays Results"
          id="{140DD674-A148-4E66-9880-D31EAAD80BE1}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{857fd1a8-0476-4bea-b26b-40a89276b93e}-0"
          uid="{14D760D9-E5A4-4BA4-818D-E1AD99F4FF5D}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom"
          ph="body"
          uid="{FB4DBCED-CAB0-4FB7-88D5-5E1C4FDC7097}" />
        <r
          ds=""
          id="{48F21C15-5DD1-419D-9BF3-A07C2EAA0843}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{FB4DBCED-CAB0-4FB7-88D5-5E1C4FDC7097}-0"
          uid="{3A5BAC32-8639-4169-A4D2-5469AC0CF3E7}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{9C3DFA27-58E8-466E-AB02-1158188EE582}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{FB4DBCED-CAB0-4FB7-88D5-5E1C4FDC7097}-0"
          uid="{DF1E4DF8-5E82-4D85-8F5C-C2E40BAEC3D6}"
          ccb="Clear on publish" />
        <r
          ds="{4BB2E1E6-3BA8-4368-AABB-D189F9DF2111}"
          id="{A467C461-2046-49D3-9EDE-C71FB401BE9B}"
          par="PaddingSize&amp;EnableLazyLoading=1&amp;Theme&amp;TitlePosition&amp;TitleFontStyle&amp;TitleFontSize&amp;TitleWeight&amp;IsModuleClickTrackingEnabled&amp;ModuleLocation&amp;ForceReloadChildren&amp;IsCarouselMobileView=1"
          ph="/body/component-wrapper-inner-{FB4DBCED-CAB0-4FB7-88D5-5E1C4FDC7097}-0"
          uid="{9D36EC20-00B2-4DDD-B89D-12D2527A0C73}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground=1&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="body"
          uid="{2CBDFEFA-F062-4108-B916-6B6BEB67884C}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{43546A28-D231-4287-96D2-25DEF529F1A5}"
          par="DescriptionPosition&amp;TruncateTextOnMobile&amp;PaddingSize&amp;EnableLazyLoading=1&amp;TitleTag=h2&amp;TitlePosition=center&amp;TitleFontStyle=default&amp;TitleFontSize&amp;TitleWeight&amp;ClassName&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{2CBDFEFA-F062-4108-B916-6B6BEB67884C}-0"
          uid="{65712069-7A5F-444A-85B2-1B43B51E01D1}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{2D04B19E-63E4-42FB-9581-0D7370107D7E}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{2CBDFEFA-F062-4108-B916-6B6BEB67884C}-0"
          uid="{7FF7CC33-6831-4F2E-ABF4-709703B0C915}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{F439DE66-8B5C-4235-BE17-8675B58AA50A}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{2CBDFEFA-F062-4108-B916-6B6BEB67884C}-0"
          uid="{191F3BE4-86AC-4D0A-8A30-20A896BF6E5E}"
          ccb="Clear on publish" />
        <r
          ds="/sitecore/content/EasyJet/Holidays/Data/View Holidays Results"
          id="{140DD674-A148-4E66-9880-D31EAAD80BE1}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{2CBDFEFA-F062-4108-B916-6B6BEB67884C}-0"
          uid="{BBE9FE8D-2DAB-4647-A9D8-95B845252369}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          par="Anchor&amp;DisableLazyLoading&amp;IsFullWidth&amp;IsGreyBackground&amp;IsTriangleStart&amp;IsTriangleEnd&amp;IsTriangleEndReverse&amp;IsTriangleStartReverse&amp;IsBorderBottom&amp;IsSticky&amp;IsSearchWrapper&amp;ForceReloadChildren"
          ph="body"
          uid="{69D4005F-3C42-4751-8A14-9AFBEF6E0913}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{43546A28-D231-4287-96D2-25DEF529F1A5}"
          par="DescriptionPosition&amp;TruncateTextOnMobile&amp;PaddingSize&amp;EnableLazyLoading=1&amp;TitleTag=h2&amp;TitlePosition=center&amp;TitleFontStyle=default&amp;TitleFontSize&amp;TitleWeight&amp;ClassName&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{69D4005F-3C42-4751-8A14-9AFBEF6E0913}-0"
          uid="{33BB8EDC-5B66-4B60-8EE4-530A88CA8761}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{2E31778A-36C8-4600-A061-01B3B4F6915D}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{69D4005F-3C42-4751-8A14-9AFBEF6E0913}-0"
          uid="{071BEC53-373C-439F-B53E-4546C369F23C}"
          ccb="Clear on publish" />
        <r
          id="{3CFB6E83-8DFD-418F-86BF-ACDD663328D5}"
          ph="body"
          uid="{4D0F7BC0-4F86-4154-9770-817CA3AC74DC}" />
        <r
          ds=""
          id="{7F3B982E-FE67-4F5E-BB74-68398F882AC2}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{4d0f7bc0-4f86-4154-9770-817ca3ac74dc}-0"
          uid="{37576E25-DE0F-4E2D-BC2C-4627C3EA4C4E}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{F7F7C175-5B76-4011-8E12-C505B3068B38}"
          par="PaddingSize&amp;DisableLazyLoading&amp;Columns=3&amp;ColumnsOnMobile=2&amp;MaxVisibleLinks=24&amp;MaxVisibleLinksOnMobile=20&amp;TitleTag&amp;TitlePosition&amp;TitleFontStyle&amp;TitleFontSize&amp;TitleWeight&amp;IsModuleClickTrackingEnabled&amp;ModuleLocation&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{4d0f7bc0-4f86-4154-9770-817ca3ac74dc}-0"
          uid="{E3EDE817-4085-45BE-90D4-418CD03F5477}"
          ccb="Clear on publish" />
        <r
          ds="/sitecore/content/EasyJet/Holidays/Data/Customers Feedback"
          id="{5295B583-8B18-4FCD-A1B0-10F7F965FD4A}"
          par="ForceReloadChildren"
          ph="/body/component-wrapper-inner-{4d0f7bc0-4f86-4154-9770-817ca3ac74dc}-0"
          uid="{565D393D-0B42-44BD-BF49-13D919DFA065}"
          ccb="Clear on publish" />
        <r
          ds=""
          id="{92E59D27-A78E-4C71-87F6-27046C6136CC}"
          par="PaddingSize=16px&amp;DisableLazyLoading&amp;ForceReloadChildren"
          ph="/body/component-wrapper-inner-{4d0f7bc0-4f86-4154-9770-817ca3ac74dc}-0"
          uid="{64A7E5F2-05B4-48CD-BE5C-DCFA6D1C928E}"
          ccb="Clear on publish" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240317T171703Z
    - ID: "b1c725b7-ac4b-4f21-8d3c-9ccbb64d94ea"
      Hint: PageCategory
      Value: Region
