---
ID: "f47740f3-b210-45a3-85e3-73f7cb281c82"
Parent: "03f1562d-90ee-4bb0-9564-7ccb948e435a"
Template: "03f1562d-90ee-4bb0-9564-7ccb948e435a"
Path: /sitecore/templates/Feature/Destinations/Amend/Amend Hotel Summary/__Standard Values
DB: master
SharedFields:
- ID: "33abcdc6-fc9e-40aa-b05a-2791ab078077"
  Hint: RoomAndBoardIcon
  Value: |
    <image mediaid="{661A15B6-4F55-4DFE-A504-43471F6BAB85}" />
- ID: "4570cb63-fc9a-4aae-938a-efe19691c604"
  Hint: TransferIcon
  Value: |
    <image mediaid="{9A6E7A74-AA0F-45F7-B8A5-E3B5BBECAAC9}" />
- ID: "59ac1a2f-1c68-41aa-a816-67eeb9ecc504"
  Hint: HotelIcon
  Value: |
    <image mediaid="{D2B2D4C7-578A-48BA-960A-C54A1F22287E}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "058a2cf8-4940-4d9c-871d-9b2532ad54b2"
      Hint: ConfirmCTA
      Value: Confirm Changes
    - ID: "1e54c75d-fdae-476f-8609-1fc18cde3ad7"
      Hint: Title
      Value: Review your changes
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240724T130100Z
    - ID: "28a4561e-dbef-4ab3-ae91-335ef4a610bf"
      Hint: TransferTitle
      Value: Transfer
    - ID: "3e4a346a-76fa-48e9-a797-acc1ca8f6e25"
      Hint: RoomAndBoardTitle
      Value: Room & Board
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "649d9dd5-9688-45a9-951f-9cf6af21e9d7"
      Hint: HotelTitle
      Value: Hotel
    - ID: "803ede5e-a861-4550-9d94-e3d98ca89f52"
      Hint: TransferCTA
      Value: Edit
    - ID: "b6df1052-e4d4-49d8-9fa9-d78e8bcf395e"
      Hint: HotelCTA
      Value: View hotel details
    - ID: "c0fb25d1-0c1c-42d9-a719-f2c1d69b0ff9"
      Hint: RoomAndBoardCTA
      Value: Edit
    - ID: "e25dd482-608c-43f9-b2b4-9bd6ad7008d6"
      Hint: Subtitle
      Value: "Good news, we can change your hotel! Please review the changes to your holiday package below carefully and we will update your booking after you have confirmed and paid."
