<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
    </ItemGroup>
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Foundation\SitecoreExtensions\code\easyJet.Foundation.SitecoreExtensions.csproj" />
    </ItemGroup>
</Project>