//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace easyJet.Holidays.External.Atcom.Models.Internal
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/ItemSearchRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/ItemSearchRequest", IsNullable = false)]
    public partial class ItemSearchRequest : AtcomresBaseOfferSearchRequest
    {

        /// <remarks/>
        public ItemSearchRequestBase_Prd Base_Prd;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item_Search_Type", Namespace = "AtComRes/Common")]
        public Item_Search_Type[] Item_Search_Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Set_Type", Namespace = "AtComRes/Common")]
        public Set_Type[] Set_Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item_Type", Namespace = "AtComRes/Common")]
        public Item_Type[] Item_Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public Display_Type Display_Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Display_TypeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "AtComRes/Common")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ser_Id")]
        public string[] Search_Context;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string Yield_Late_Sup;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/ItemSearchRequest")]
    public partial class ItemSearchRequestBase_Prd
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string Prd_Cd;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public Prom Prom;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Room_Code")]
        public string[] Room_Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Route", Namespace = "AtComRes/Common")]
        public Route_Tp[] Route;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "AtComRes/Common")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubServPax", IsNullable = false)]
        public SubServPax[] SubServPaxs;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string PackageNo;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accom", Namespace = "AtComRes/Common")]
        public Accom[] Accom;
    }
}
