import { PricePromiseStore } from 'frontend/components/renderings/PricePromise/PricePromiseStore';

export const mockPricePromiseStore: PricePromiseStore = {
    formKey: 'formKey',
    pricePromiseInfo: {
        isValidCheckboxSet: true,
        isValidField: jest.fn(() => true),
        validateField: jest.fn(() => []),
        onChangeField: jest.fn(),
        name: '',
        bookingReference: '',
        departureDate: '',
        link: '',
        sameDatesOfTravel: false,
        sameFlights: false,
        samePartyComposition: false,
        sameRoomType: false,
        inclusiveOn23kg: false,
        inclusiveOfTransfers: false,
        differentCompany: false,
        bookedWithinLast24h: false,
        screenshots: null,
        showABTAMembershipCheckbox: true,
        isValid: true,
    },
    forceErrors: false,
    isPricePromiseSending: false,
    isPricePromiseFailed: false,
    isFormValid: true,
    submitPricePromise: jest.fn(),
    toggleForceErrors: jest.fn(),
    isSuccessMessageShown: false,
    toggleSuccessMessage: jest.fn(),
    showABTAMembershipCheckbox: true,
    resetForm: jest.fn(),
    formData: new FormData(),
};
