<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>warnings</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\easyJet.Holidays.External.AWS\easyJet.Holidays.External.AWS.csproj" />
    <ProjectReference Include="..\easyJet.Holidays.External.Domain\easyJet.Holidays.External.Domain.csproj" />
  </ItemGroup>
</Project>