---
ID: "f9fffa63-f351-4392-b382-2ff120a2d955"
Parent: "38e9043f-1d77-45ea-b025-49dae9501026"
Template: "38e9043f-1d77-45ea-b025-49dae9501026"
Path: /sitecore/templates/Foundation/Presentation/Rendering Parameters/Personalize Placeholder Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251010T090350Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
