<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Foundation\WebApi\code\easyJet.Foundation.WebApi.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Feature\Booking\code\easyJet.Feature.Booking.csproj" />
    </ItemGroup>
</Project>