/**
 * Describes a file that represents a component definition
 */
export interface IComponentFile {
    componentName: string;
    moduleName: string;
    path: string;
}

const isStaticComponent = (componentPath: string) => componentPath.includes('/static/');

/**
 * Generates the contents of the component factory file using a predefined string template.
 * @param components - the list of component files to include
 * @returns component factory file contents
 */
// FIXME: fix EE component module import
function generateComponentFactory(components: IComponentFile[]): string {
    return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.ts to modify the generation of this file.

import dynamic from 'next/dynamic';

${components
    .filter(component => isStaticComponent(component.path))
    .map(component => `import * as ${component.moduleName} from '${component.path}';`)
    .join('\n')}

const components = new Map();
const modulesWithServerSide = new Map();

const collectServerSideModules = componentName => {
    return module => {
        if (typeof window === 'undefined' && 'getServerSideProps' in module) {
            modulesWithServerSide.set(componentName, module);
        }

        return module.default;
    };
};

${components
    .map(component => {
        if (isStaticComponent(component.path)) {
            return `components.set('${component.componentName}', ${component.moduleName});`;
        }

        return `components.set('${component.componentName}', dynamic(() => import('${component.path}').then(collectServerSideModules('${component.componentName}'))));`;
    })
    .join('\n')}


// Used server-side (page-props-factory.ts) to get import module for components with getServerSideProps function
export function componentModule(componentName: string) {
  return modulesWithServerSide.get(componentName);
}

// Used both server and client-side to get just React component
export function componentFactory(componentName: string) {
  const component = components.get(componentName);
  return component?.default || component;
}
`;
}

export default generateComponentFactory;
