---
ID: "3713a4cd-f77e-496b-8119-b0572bbc65e3"
Parent: "f1495b3f-6b08-4d4a-97f3-89dd1460f2da"
Template: "f1495b3f-6b08-4d4a-97f3-89dd1460f2da"
Path: /sitecore/templates/Feature/PageContent/Rendering Parameters/Partnership Component Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220127T181823Z
    - ID: "4ac52ca3-4d36-4580-9f70-626d688f9d7e"
      Hint: Theme
      Value: Standard
