export AWS_PROFILE := env('AWS_PROFILE', 'ejh-web-dev')

help:
  @just --list

init *args:
  terraform init -backend-config=".config.local.tfbackend" {{ args }}

workspace environment="CI":
  terraform workspace select 'Web-{{ environment }}-Lambda-RouteFileParser'

plan environment="dev":
  terraform plan --var-file='vars/variables.local.{{ environment }}.tfvars'

apply environment="dev":
  terraform apply --var-file='vars/variables.local.{{ environment }}.tfvars'

fmt:
  terraform fmt -recursive
