export AWS_PROFILE := env('AWS_PROFILE', 'ejh-web-dev')

help:
  @just --list

init *args:
  terraform init -backend-config=".config.local.tfbackend" {{ args }}

workspace:
  terraform workspace select 'SF-UAT-Lambda-SalesforceDatahubSync'

plan:
  terraform plan --var-file='vars/variables.local.uat.tfvars'

apply:
  terraform apply --var-file='vars/variables.local.uat.tfvars'

fmt:
  terraform fmt -recursive
