---
ID: "27a28811-c46e-4fdb-adb2-7a7007922109"
Parent: "aa3c3f19-d51e-48e5-9614-915acbf0fc86"
Template: "aa3c3f19-d51e-48e5-9614-915acbf0fc86"
Path: /sitecore/templates/Project/MicroApps/UserManagement/Components/Consortia/Consortium Form/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240418T195641Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
