//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace easyJet.Holidays.External.Atcom.Models.Internal.Search
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AvCache
    {

        /// <remarks/>
        public AvCacheStatus Status;

        /// <remarks/>
        public AvCacheResult Result;

        /// <remarks/>
        public AvCacheError Error;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Node;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Xsd;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheStatus
    {

        /// <remarks/>
        public AvCacheStatusTotal Total;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheStatusTotal
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResult
    {

        /// <remarks/>
        public AvCacheResultOffers Offers;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffers
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Offer")]
        public AvCacheResultOffersOffer[] Offer;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Cat", IsNullable = false)]
        public AvCacheResultOffersCat[] Facets;

        /// <remarks/>
        public AvCacheResultOffersLists Lists;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOffer
    {

        /// <remarks/>
        public AvCacheResultOffersOfferPriceFreeze PriceFreeze;

        /// <remarks/>
        public AvCacheResultOffersOfferDDDeposit DDDeposit;

        /// <remarks/>
        public AvCacheResultOffersOfferMultiCentre MultiCentre;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accom")]
        public AvCacheResultOffersOfferAccom[] Accom;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Board", IsNullable = false)]
        public AvCacheResultOffersOfferBoard[] AltBoard;

        /// <remarks/>
        public AvCacheResultOffersOfferTransport Transport;

        /// <remarks/>
        public AvCacheResultOffersOfferTransfers Transfers;

        /// <remarks/>
        public AvCacheResultOffersOfferBaggage Baggage;

        /// <remarks/>
        public AvCacheResultOffersOfferGroup Group;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Stay;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StaySpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Avail;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PricePP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PayLocalEst;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PayLocal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PayLocalEstPP;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PricePPSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Deposit;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepositSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo LowDep;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowDepSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo CoachTransfer;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoachTransferSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo CarHire;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarHireSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo WorldCare;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorldCareSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Hlo;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HloSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AvCacheResultOffersOfferType Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo DDTerms;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DDTermsSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferPriceFreeze
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint AutoCanxDays;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferDDDeposit
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferMultiCentre
    {

        /// <remarks/>
        public AvCacheResultOffersOfferMultiCentrePriced Priced;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Stay;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Itin;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Brand;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cty1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cty2;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cty3;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommPri;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Centres;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo BkToBk;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BkToBkSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Disc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DiscPP;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscPPSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AtcomId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferMultiCentrePriced
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ad;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ch;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte In;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    public enum YesNo
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccom
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Unit")]
        public AvCacheResultOffersOfferAccomUnit[] Unit;

        /// <remarks/>
        public AvCacheResultOffersOfferAccomPT Pt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Stay;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Brand;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rating;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cty1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cty2;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cty3;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommPri;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tracs;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AtcomId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AvCacheResultOffersOfferAccomType Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Ext;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Latitude;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Longitude;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnit
    {

        /// <remarks/>
        public AvCacheResultOffersOfferAccomUnitSrcInfo SrcInfo;

        /// <remarks/>
        public AvCacheResultOffersOfferAccomUnitPriced Priced;

        /// <remarks/>
        public AvCacheResultOffersOfferAccomUnitOcc Occ;

        /// <remarks/>
        public AvCacheResultOffersOfferAccomUnitPriceDetail PriceDetail;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Qty;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Disc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DiscPP;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscPPSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Board;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Avail;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Min;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Max;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MinAd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinAdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxAd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxAdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MinCh;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxCh;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxIn;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxInSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MinAdAge;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinAdAgeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MinInAge;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinInAgeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint FFPP;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FFPPSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Dc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DcSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tracs;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AtcomId;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NRefSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo NRef;
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnitPriceDetail
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PriceElement")]
        public AvCacheResultOffersOfferAccomUnitPriceDetailPriceElement[] PriceElement;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnitPriceDetailPriceElement
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PriceCur;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ConvPricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ExchRt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Qty;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PayLocal;
    }
    
        
        /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnitSrcInfo
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Accom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Board;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string System;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnitPriced
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ad;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ch;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte In;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnitOcc
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pax")]
        public AvCacheResultOffersOfferAccomUnitOccPax[] Pax;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ad;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ch;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte In;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomUnitOccPax
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Age;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferAccomPT
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepPt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrPt;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum AvCacheResultOffersOfferAccomType
    {

        /// <remarks/>
        CRZ,

        /// <remarks/>
        ACC,

        /// <remarks/>
        TOUR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferBoard
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitCode;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferTransport
    {

        /// <remarks/>
        public AvCacheResultOffersOfferTransportPriced Priced;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Route")]
        public AvCacheResultOffersOfferTransportRoute[] Route;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MinAvail;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Brand;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MajorCabin;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal JnyDurOut;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JnyDurOutSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal JnyDurRet;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JnyDurRetSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferTransportPriced
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ad;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Ch;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte In;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferTransportRoute
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Option")]
        public AvCacheResultOffersOfferTransportRouteOption[] Option;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AvCacheResultOffersOfferTransportRouteDir Dir;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CycDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepPt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime DepDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrPt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ArrDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Avail;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FltNo;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ViaPt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouteCd;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RouteKey;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Class;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Car;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OpCar;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MajorCar;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AvCacheResultOffersOfferTransportRouteFare Fare;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FareSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PricePPSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Taxes;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxesSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Equip;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Dreamliner;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DreamlinerSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Meal;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MealSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNo Ext;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AtcomId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Disc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DiscPP;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscPPSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal FltDur;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FltDurSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferTransportRouteOption
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RouteOptionCode Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Avail;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriceAd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceAdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriceCh;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceChSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    public enum RouteOptionCode
    {

        /// <remarks/>
        ELR,

        /// <remarks/>
        PRE,

        /// <remarks/>
        XSP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum AvCacheResultOffersOfferTransportRouteDir
    {

        /// <remarks/>
        O,

        /// <remarks/>
        I,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum AvCacheResultOffersOfferTransportRouteFare
    {

        /// <remarks/>
        PUB,

        /// <remarks/>
        CAT,

        /// <remarks/>
        NET,

        /// <remarks/>
        NETI,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferTransfers
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transfer")]
        public AvCacheResultOffersOfferTransfersTransfer[] Transfer;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferTransfersTransfer
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AvCacheResultOffersOfferTransfersTransferDir Dir;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AvCacheResultOffersOfferTransfersTransferRateTp RateTp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateTpSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Qty;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CrtCd;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum AvCacheResultOffersOfferTransfersTransferDir
    {

        /// <remarks/>
        IN,

        /// <remarks/>
        OUT,

        /// <remarks/>
        BOTH,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum AvCacheResultOffersOfferTransfersTransferRateTp
    {

        /// <remarks/>
        PI,

        /// <remarks/>
        PP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferBaggage
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriceAd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceAdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriceCh;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceChSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Allowance;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint ChAge;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChAgeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferGroup
    {

        /// <remarks/>
        public uint TotalOffers;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOffersSpecified;

        /// <remarks/>
        public string Price;

        /// <remarks/>
        public string PricePP;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Date", IsNullable = false)]
        public AvCacheResultOffersOfferGroupDate[] Dates;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DepPt", IsNullable = false)]
        public AvCacheResultOffersOfferGroupDepPt[] DepPts;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mode;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferGroupDate
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CycDate;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersOfferGroupDepPt
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum AvCacheResultOffersOfferType
    {

        /// <remarks/>
        INC,

        /// <remarks/>
        AO,

        /// <remarks/>
        CMP,

        /// <remarks/>
        MC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersCat
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Facet")]
        public AvCacheResultOffersCatFacet[] Facet;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersCatFacet
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Min;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Max;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersLists
    {

        /// <remarks/>
        public string Board;

        /// <remarks/>
        public string DepPt;

        /// <remarks/>
        public string ArrPt;

        /// <remarks/>
        public string DepPort;

        /// <remarks/>
        public string Stay;

        /// <remarks/>
        public string OutSlots;

        /// <remarks/>
        public string InSlots;

        /// <remarks/>
        public string CabinClass;

        /// <remarks/>
        public string Price;

        /// <remarks/>
        public string PricePP;

        /// <remarks/>
        public string Discount;

        /// <remarks/>
        public string Deposit;

        /// <remarks/>
        public YesNo DreamLiner;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DreamLinerSpecified;

        /// <remarks/>
        public YesNo Direct;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectSpecified;

        /// <remarks/>
        public YesNo InDirect;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InDirectSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dc")]
        public AvCacheResultOffersListsDC[] Dc;

        /// <remarks/>
        public string Carrier;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheResultOffersListsDC
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public YesNo Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AvCacheError
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text;
    }
}