---
ID: "0a847e2f-8249-4518-90c6-e3031c50acd9"
Parent: "f4e450a5-ed31-4105-96d1-64d17924a5ff"
Template: "f4e450a5-ed31-4105-96d1-64d17924a5ff"
Path: /sitecore/templates/Feature/Destinations/Deals Destinations/Deals Destinations Component/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{BEB43138-62AA-4A5E-936C-0918E7770FBC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210624T153802Z
    - ID: "cf756c16-02b1-4be8-8544-8a23cb2ea33e"
      Hint: IsPriceRounded
      Type: Checkbox
      Value: 1
