---
ID: "714896ea-78e3-4f6d-b196-6cd62a97dc0f"
Parent: "42400b6f-4523-424a-bfc9-165a145d6fa3"
Template: "42400b6f-4523-424a-bfc9-165a145d6fa3"
Path: /sitecore/templates/Feature/Destinations/Amend/Amend Dates/Amend Dates Seats and Bags/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "02e9c392-2043-4f1e-aad1-f14f0759bc2a"
      Hint: EnableEditCabinBagsCTA
      Type: Checkbox
      Value: 0
    - ID: "0bc65cd3-e335-412e-b00e-5faedb548993"
      Hint: SeatsIcon
      Value: |
        <image mediaid="{F6696C39-E4ED-4679-AEFC-4470A3919895}" />
    - ID: "1530b51c-5322-44d7-899f-710aa2721077"
      Hint: SeatsTitle
      Value: Seats
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230628T095818Z
    - ID: "2d620eb3-7f17-4689-8ffc-6592d50350e8"
      Hint: EnableAddSeatsCTA
      Type: Checkbox
      Value: 0
    - ID: "73fa024c-c648-47ff-979e-ca2481135fd3"
      Hint: PreviousSeatsDroppedSubtitle
      Value: Any previous seats you had are lost. Please select new seats.
    - ID: "9c07a2c7-3252-4f06-b173-1a06e06614e9"
      Hint: CabinBagsIcon
      Value: |
        <image mediaid="{0CB9F279-EC44-4D6C-A1C8-E17E1D0B8CCD}" />
    - ID: "b0e6c922-6f77-4ae9-ab45-10491c6ea1b9"
      Hint: EnableEditHoldBagsCTA
      Type: Checkbox
      Value: 0
    - ID: "bc161fb3-ab83-4ac3-9e41-da164e12b702"
      Hint: PreviousSeatsDroppedTitle
      Value: Please read carefully
    - ID: "d5c3b306-2418-4848-a90c-856525389988"
      Hint: EditHoldBagsCTATitle
      Value: Edit hold bags
    - ID: "d7be35d0-8906-4c8f-89a4-3f4aaf32ae0c"
      Hint: HoldBagsTitle
      Value: Hold Bags
    - ID: "df4fddea-4847-4b0a-8664-7af91e4c36a6"
      Hint: AddSeatsCTATitle
      Value: Add seats
    - ID: "e8a1aa88-f8a6-455d-8200-0d480e054345"
      Hint: CabinBagsTitle
      Value: Cabin Bags
    - ID: "ea95c8a4-b722-42e2-bc4d-321442591d0f"
      Hint: HoldBagsIcon
      Value: |
        <image mediaid="{82820F8E-6904-45DC-8B03-6543193B6720}" />
    - ID: "f47887de-df03-4e3a-a9cc-75d0913204af"
      Hint: EditCabinBagsCTATitle
      Value: Edit cabin bags
