<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Sitecore.ContentSearch" />
    <PackageReference Include="Sitecore.ContentSearch.Linq" />
    <PackageReference Include="Voucherify" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
  <Import Project="$(SolutionDir)SitecoreProject.props" />
  <PropertyGroup>
    <TargetFramework>$(FrameworkVersion)</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratedAssemblyInfoFile>Properties\Assemblyinfo.cs</GeneratedAssemblyInfoFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)src\Foundation\Destinations\code\easyJet.Foundation.Destinations.csproj" />
    <ProjectReference Include="..\..\DynamoDb\code\easyJet.Foundation.DynamoDb.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.config">
      <TransformOnBuild>true</TransformOnBuild>
    </Content>
    <Content Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Solr.CustomIndex.Master.config">
      <TransformOnBuild>true</TransformOnBuild>
    </Content>
    <Content Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Solr.CustomIndex.Web.config">
      <TransformOnBuild>true</TransformOnBuild>
    </Content>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.CI.config">
      <DependentUpon>easyJet.Foundation.Voucherify.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Debug.config">
      <DependentUpon>easyJet.Foundation.Voucherify.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Release.config">
      <DependentUpon>easyJet.Foundation.Voucherify.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Solr.CustomIndex.Master.Debug.config">
      <DependentUpon>easyJet.Foundation.Voucherify.Solr.CustomIndex.Master.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Solr.CustomIndex.Master.Release.config">
      <DependentUpon>easyJet.Foundation.Voucherify.Solr.CustomIndex.Master.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Solr.CustomIndex.Web.Debug.config">
      <DependentUpon>easyJet.Foundation.Voucherify.Solr.CustomIndex.Web.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.Voucherify.Solr.CustomIndex.Web.Release.config">
      <DependentUpon>easyJet.Foundation.Voucherify.Solr.CustomIndex.Web.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
  </ItemGroup>
</Project>