---
ID: "fa382c4d-3eff-4ad6-8efb-7e07d8f14679"
Parent: "d0ffeb34-f821-445a-8f02-139b83ff1e6e"
Template: "d0ffeb34-f821-445a-8f02-139b83ff1e6e"
Path: /sitecore/templates/Project/MicroApps/UserManagement/Web Forms/Sections/Users/Change Password Section/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240613T141515Z
    - ID: "4f5b492f-5a3c-4401-8fd5-e389d476db39"
      Hint: PasswordMismatchErrorMessage
      Value: The passwords entered do not match.
    - ID: "76b398cf-c3dc-481d-bf7f-5f6982923799"
      Hint: SubtitleForScreenReader
      Value: Change your Password
    - ID: "8a9bb874-a709-42c6-8dc5-cae50ca7b52e"
      Hint: Subtitle
      Value: Change your Password
    - ID: "c9b5e3c2-14f7-472a-89c4-9407258fb2a1"
      Hint: Description
      Value: Please enter your new password below. Ensure your password is at least 8 characters long.
