---
ID: "0270cd3d-f2bf-4758-8791-9cb266be2947"
Parent: "6dfdd4f0-78c8-4d0d-87a1-ac5d1ae293ec"
Template: "6dfdd4f0-78c8-4d0d-87a1-ac5d1ae293ec"
Path: /sitecore/templates/Feature/Ancillaries/SeatMap/Info Popup/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220815T120142Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
