export const GENERIC_CUSTOM_PARAMS_EMPTY = {
    genericValue1: 'null',
    genericValue2: 'null',
    genericValue3: 'null',
    genericValue4: 'null',
    destinationUrl: 'null',
};

export enum PersonalizationNames {
    Default = 'Default',
    Standard = 'Standard',
}

export enum EventCategories {
    AlertBanner = 'Alert banner',
    AlertsModule = 'Alerts module',
    BoardOptions = 'Board Options',
    Booking = 'Booking',
    BookingConfirmation = 'Booking confirmation',
    Deals = 'Deals pages',
    DestinationGuide = 'Destination Guide',
    Empty = '',
    Excursions = 'Excursions',
    ExternalExtras = 'External Extras',
    ExternalExtrasModule = 'External Extras Module',
    Extras = 'Extras',
    FeefoWidget = 'Feefo Widget',
    HolidayTypes = 'Holiday types pages',
    HolidayTypesHub = 'Holiday types hub',
    Holidays = 'Holidays',
    HolidayUnavailable = 'Holiday Unavailable',
    Homepage = 'Homepage',
    HotelDetailsPage = 'Hotel Details Page',
    HotelGallery = 'Hotel Gallery',
    InspireMe = 'Inspire Me',
    Login = 'Log in',
    NavigationBarMenu = 'Navigation Bar Menu Clicks',
    PromoDestinationCarousel = 'Promo Destination Carousel',
    SearchPod = 'Search Pod',
    Shortlist = 'Shortlist',
    SitTogetherCheckbox = 'Sit Together Checkbox',
    SpecialServiceRequest = 'Special Service Request',
    SportsEquipment = 'Sports Equipment',
    SummaryBar = 'Summary Bar',
    UrgencyMessage = 'Urgency Message',
    FullWidthBanner = 'Full Width Banner',
    Map = 'Map',
    Module = 'Module',
    Header = 'Header',
}

export enum EventActions {
    AirlineInterstitialPage = 'Airline Interstitial Page',
    AlertBanner = 'Alert banner impression',
    AlertBannerClicked = 'Alert banner clicked',
    Available = 'Available',
    Back = 'Back',
    ButtonClick = 'Button Click',
    CTAClicked = 'CTA Clicked',
    CannotAccommodateModal = 'Modal - Cannot Accommodate',
    CardDeselected = 'Card deselected',
    CardSelected = 'Card selected',
    Carousel = 'Carousel Impression',
    Checked = 'Checked',
    Close = 'Close',
    Confirmation = 'Confirmation',
    Continue = 'Continue',
    ExcursionsLoaded = 'Component loaded on page',
    ExcursionsViewed = 'Component viewed',
    FeaturedDestinations = 'Featured destinations impression',
    FeaturedHotels = 'Featured hotels impression',
    FullPriceBreakdown = 'Full price breakdown pop up',
    HeroBannerButtonClick = 'Hero banner button click',
    HeroBannerImpression = 'Hero banner impression',
    HotelSummary = 'Hotel summary component impression',
    HotelSummaryClicked = 'Hotel summary component clicked',
    Impressions = 'Impressions',
    SeatImpressions = 'Seats Impressions',
    PopupImpression = 'Pop Up Impression',
    PopupClose = 'Pop Up Close',
    PopupAccordionOpen = 'Pop Up Accordion Open',
    PopupCTAClick = 'Pop Up CTA Click',
    Interacted = 'Interacted',
    LanguageSelection = 'Language Selection',
    LargeCabinBags = 'Large Cabin Bags',
    LoginSuccessfully = 'Log in successfully',
    Map = 'Map',
    MarketSelection = 'Market Selection',
    ModuleClick = 'Module Click',
    MoreDetails = 'More details modal',
    Navigation = 'Navigation',
    NavigationBanner = 'Navigation banner impression',
    Popup = 'Pop up',
    PopupLux = 'Pop Up - LUX',
    PromoBlocks = 'Promo blocks impression',
    Quiz = 'Quiz',
    RequestSpecialService = 'Request Special Service clicked',
    SeeOptions = 'See options',
    Select = 'Select',
    Deselect = 'Deselect',
    SpecialServiceRequest = 'Special Service Request',
    SubmitRequest = 'Submit Request',
    Tile = 'Tile Impression',
    TileClick = 'Tile Click',
    Unavailable = 'Unavailable',
    Unchecked = 'Unchecked',
    ViewBooking = 'View Booking',
    CTAClick = 'CTA Click',
    ApplePay = 'apple pay',
    CreditDebitCard = 'credit debit',
    Impression = 'Impression',
    ImpressionClicked = 'Impression Clicked',
    OpenRouteMap = 'Open Route Map',
    MapPinClick = 'Map Pin Click',
    CloseMapClick = 'Close Map Click',
    POI = 'POI',
    RecentSearch = 'Recent Search',
    StartNewSearch = 'Start New Search',
}

export enum EventLabels {
    ViewHoliday = 'View Holiday',
    CheckAvailability = 'Check Availability',
    CapacityFull = 'Capacity Full',
    CapacityFullClick = 'Capacity Full - Add Hold Luggage',
    Compare = 'Compare',
    Confirmation = 'Confirmation',
    EditYourAnswers = 'Edit Your Answers',
    EditYourTransfer = 'Edit Your Transfer',
    EditYourRoomAndBoard = 'Edit Your Room & Board',
    Impression = 'Impression',
    PartialCapacityFull = 'Partial Capacity Full',
    RepeatQuiz = 'Repeat Quiz',
    Start = 'Start',
    StartNewQuiz = 'Start New Quiz',
    ViewDestination = 'View Destination',
    ViewExtras = 'View Your Extras',
    Hide = 'Hide',
    Position = 'Position',
    Back = 'Back',
    ManageHoliday = 'Manage Holiday',
    ChangeHotel = 'Change Hotel',
    PriceChange = 'Price Change',
    LoadMore = 'Load More',
    BookHotel = 'Book Hotel',
    ViewHotelDetails = 'View Hotel Details',
    LCBFull = 'LCB Full',
    Selected = 'Selected',
    Error = 'Error',
    ButtonClick = 'Button Click',
    PaymentCancelled = 'Payment Cancelled',
    DestinationGuide = 'Destination Guide',
    DestinationGuideTab = 'Destination Guide Tab',
    PromoBanner = 'Promo banner',
}

export enum EventLocations {
    HeroBannerButton = 'Hero Banner Button',
    HeroBannerImage = 'Hero Banner Image',
}

export enum BrandValues {
    LuxuryCollection = 'Luxury Collection',
}
