<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="AWSSDK.Core" />
        <PackageReference Include="AWSSDK.S3" />
    </ItemGroup>
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Foundation\Destinations\code\easyJet.Foundation.Destinations.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Foundation\Optimization\code\easyJet.Foundation.Optimization.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Foundation\AmazonS3\code\easyJet.Foundation.AmazonS3.csproj" />
    </ItemGroup>
</Project>