---
ID: "21e07e67-31d1-4b2a-8a13-0335a1894be3"
Parent: "e361c02e-7348-4c65-ba6b-fa9086fd8661"
Template: "e361c02e-7348-4c65-ba6b-fa9086fd8661"
Path: /sitecore/templates/Foundation/Presentation/Multivariant Page Design/Multivariant Page Design/__Standard Values
DB: master
SharedFields:
- ID: "89e97d97-e270-4f71-8f00-0c3b89b435d1"
  Hint: CheckByPlacheloder
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201030T111907Z
