<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <AWSProjectType>Lambda</AWSProjectType>
        <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <!-- Generate ready to run images during publishing to improve cold start time. -->
        <PublishReadyToRun>true</PublishReadyToRun>
        <AssemblyName>DatahubReplaySync</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Annotations" />
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" />
        <PackageReference Include="Amazon.Lambda.S3Events" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
        <PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="AWSSDK.SQS" />
        <PackageReference Include="CsvHelper" />
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\easyJet.Holidays.External.AWS.Domain\easyJet.Holidays.External.AWS.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="..\easyJet.Holidays.External.AWS.Domain\appsettings.shared.json">
        <Link>appsettings.shared.json</Link>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    
    <ItemGroup>
        <SonarQubeSetting Include="sonar.exclusions">
            <Value>Function.cs</Value>
        </SonarQubeSetting>
    </ItemGroup>

</Project>
