---
ID: "c894dc4d-5b01-4846-9dcb-c7313e85e168"
Parent: "6f5c699e-75ea-46aa-9409-87083826f4a0"
Template: "6f5c699e-75ea-46aa-9409-87083826f4a0"
Path: /sitecore/templates/Feature/PageContent/Card With Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210817T082801Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
