---
ID: "2488fe84-f17f-4752-8c8a-b070af799d17"
Parent: "6e9cbf06-c5b6-4af5-8028-49d7b27ba176"
Template: "6e9cbf06-c5b6-4af5-8028-49d7b27ba176"
Path: /sitecore/templates/Project/Holidays/Site Settings/Free Upgrades Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210729T142707Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
