---
ID: "6bf7f40c-357f-4e2b-b0a2-e4cf6c728d9f"
Parent: "8d0058ca-9e2b-428f-a0dc-50f8bd77a694"
Template: "8d0058ca-9e2b-428f-a0dc-50f8bd77a694"
Path: /sitecore/templates/Foundation/Destinations/Live Price/Named Search/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{056AC05C-E1D1-4FD4-BC4C-CEC966FA75E2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200709T070710Z
    - ID: "f9d78bf5-6aec-4b4b-895a-c10ad6aebae2"
      Hint: Name
      Value: $name
