---
ID: "cf10abc5-f05a-4b97-bf3f-edddcd048331"
Parent: "c45ee951-5989-4666-abe7-e19f3efe048d"
Template: "788582fd-8470-4d63-b42f-d7b03848d5dd"
Path: /sitecore/content/EasyJet/TradePortal/Settings/Pax Mix Settings
DB: master
SharedFields:
- ID: "050af006-548e-445b-9909-61576040c13b"
  Hint: PaxMixChildrenIcon
  Value: |
    <image mediaid="{C4438D39-6DF3-4330-8173-7B3928E49B8A}" />
- ID: "7e1e20c1-6885-4350-8303-f397fa25d8c4"
  Hint: IsPaxMixPopupEnabled
  Type: Checkbox
  Value: 1
- ID: "da7877ee-b4b0-4cac-9cfb-10b49947c726"
  Hint: PaxMixInfantsIcon
  Value: |
    <image mediaid="{92D20CA4-59D5-4FA7-BF0F-824EA9398488}" />
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: 
- ID: "e2cd40e4-ee0f-460c-ab93-982851c27468"
  Hint: PaxMixAdultsIcon
  Value: |
    <image mediaid="{BED40AA7-DDAE-413C-9632-E88A4E124BA9}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210429T095007Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Unicorn
    - ID: "7383b1e0-408c-49b4-831b-edd6a90cc2cf"
      Hint: PaxMixPopupSubtitle
      Value: To make sure we can show you the most relevant holidays, we need a few more details.
    - ID: "bf986428-1bd2-4fcb-8cc5-8038196781ca"
      Hint: PaxMixPopupTitle
      Value: Tell us more about who's travelling
