---
ID: "675a0aad-15b6-40d6-84a5-6109b43af2b6"
Parent: "c45ee951-5989-4666-abe7-e19f3efe048d"
Template: "97076f31-80ff-47ec-956f-750c8c76289f"
Path: /sitecore/content/EasyJet/TradePortal/Settings/Session Settings
DB: master
SharedFields:
- ID: "06263f37-4bb8-4fee-8a5a-1213ea8e11e8"
  Hint: SessionTimeout
  Value: 45
- ID: "1fc3e4f9-c192-47bc-8e6a-0ea7f488e36e"
  Hint: TimerPopupTimeout
  Value: 10
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221116T121503Z
