---
ID: "c6e1d1a7-4ed1-4445-a628-7927693ad9fa"
Parent: "c45ee951-5989-4666-abe7-e19f3efe048d"
Template: "a337c599-0872-42a5-8423-d9ea028406ae"
Path: /sitecore/content/EasyJet/TradePortal/Settings/Shared Sites Settings
DB: master
SharedFields:
- ID: "86cad11f-c68a-41d0-be2e-883bd369558d"
  Hint: DelegatedAreas
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220823T123943Z
