---
ID: "2577bc84-d0a3-40ac-ab13-63886f113cb1"
Parent: "c45ee951-5989-4666-abe7-e19f3efe048d"
Template: "6f58fe4b-8620-4381-95bd-9f66ceb9f591"
Path: /sitecore/content/EasyJet/TradePortal/Settings/Special Request Settings
DB: master
SharedFields:
- ID: "2bb3ef75-0991-41af-8e80-29c9921f3e9e"
  Hint: ChangeSsrElligableInHours
  Value: 48
- ID: "8b6bafe5-d08b-48e1-8222-fc318d8b4e84"
  Hint: IsEligibleToAmendSSRForDC
  Type: Checkbox
  Value: 1
- ID: "96e4ccd4-5fdf-4ad7-a961-bd6fc95a4496"
  Hint: IsEligibleToAmendSSRForHBG
  Type: Checkbox
  Value: 0
- ID: "b389bacc-c240-481a-9350-79a59917af39"
  Hint: IsEligibleToAddSSRForDC
  Type: Checkbox
  Value: 1
- ID: "b7b13b79-7597-4d29-8de9-5fcd5aff3625"
  Hint: IsSpecialRequestActive
  Type: Checkbox
  Value: 1
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210415T104639Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Unicorn
