---
ID: "4f3d42d1-4b2b-4ce6-921f-4a700b9f004b"
Parent: "65314b7d-b629-4a39-bb8f-e14ea70ba046"
Template: "65314b7d-b629-4a39-bb8f-e14ea70ba046"
Path: /sitecore/templates/Foundation/Destinations/Countries/Countries Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{C5C485D2-C352-4E12-AC74-7A23DF280E45}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191021T100525Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
