---
ID: "5ab1bf20-0c4a-43b8-a30c-fe0432827c78"
Parent: "86fdb776-c590-4a0c-85f9-7ce20d871d91"
Template: "86fdb776-c590-4a0c-85f9-7ce20d871d91"
Path: /sitecore/templates/Feature/Destinations/Info With Action Block Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{F220BB1A-D128-4B01-B788-09DDF3556890}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200117T075044Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
