<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Allure.Net.Commons" />
    <PackageReference Include="Allure.XUnit" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="Refit.Newtonsoft.Json" />
    <PackageReference Include="Refit.Xml" />
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\easyJet.Holidays.Api.Domain\easyJet.Holidays.Api.Domain.csproj" />
  </ItemGroup>
</Project>