---
ID: "51e5b990-bfba-4da1-a81e-4d447099ebc7"
Parent: "470e3b91-3622-4511-aea4-e39dfe863184"
Template: "470e3b91-3622-4511-aea4-e39dfe863184"
Path: /sitecore/templates/Foundation/Destinations/Accommodations/Package Theme Icons Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{30ACD59D-7149-40DC-BEBD-118B93EFF8F5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200204T124802Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
