<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="EntityFramework" />
    </ItemGroup>
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Feature\ChangeTracking\code\easyJet.Feature.ChangeTracking.csproj" />
    </ItemGroup>
</Project>