---
ID: "3eec2470-135c-49cf-936e-52793f19fdd2"
Parent: "63a74452-bad9-4c31-8a50-7bc0d13fac60"
Template: "63a74452-bad9-4c31-8a50-7bc0d13fac60"
Path: /sitecore/templates/Feature/Destinations/Comparison/Compare Deals/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{1ED3EB72-A4B0-437B-8D62-82A75E8E8B72}"
- ID: "b0169099-9303-4e6a-b049-b59c6d2171eb"
  Hint: FallbackLabel
  Value: —
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251020T145332Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7939d24f-997b-4a32-9e8e-e8585bea7e57"
      Hint: SelectedHolidaysLabel
      Value: FERIEN AUSGEWÄHLT
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251020T145428Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7939d24f-997b-4a32-9e8e-e8585bea7e57"
      Hint: SelectedHolidaysLabel
      Value: URLAUB AUSGEWÄHLT
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241113T112012Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7939d24f-997b-4a32-9e8e-e8585bea7e57"
      Hint: SelectedHolidaysLabel
      Value: HOLIDAYS SELECTED
- Language: "fr-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251020T145309Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7939d24f-997b-4a32-9e8e-e8585bea7e57"
      Hint: SelectedHolidaysLabel
      Value: SÉJOURS SÉLECTIONNÉS
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251020T145358Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7939d24f-997b-4a32-9e8e-e8585bea7e57"
      Hint: SelectedHolidaysLabel
      Value: SÉJOURS SÉLECTIONNÉS
