---
ID: "27e84054-a166-4b9b-9b6d-8e60a71376d3"
Parent: "866cc425-5fea-4b4e-b4be-1b65ffb4c9d3"
Template: "866cc425-5fea-4b4e-b4be-1b65ffb4c9d3"
Path: /sitecore/templates/Feature/MediaCenter/Media Center Filters/__Standard Values
DB: master
SharedFields:
- ID: "7af2ddf5-e9ef-4cb9-9a10-4238fc7eb847"
  Hint: Title
  Value: $name
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190726T075859Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
