---
ID: "413e9565-bc51-4cc4-9c53-320ebd6e889c"
Parent: "985aabd0-2571-40da-8edc-88ea08127551"
Template: "985aabd0-2571-40da-8edc-88ea08127551"
Path: /sitecore/templates/Feature/PageContent/Imagery/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {7E3ECDBA-C8C9-4E1C-8107-CDE554C0FD6D}
    {D3D7DD1E-254A-40B4-B427-D4A8453B2EAB}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190715T062506Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
