---
ID: "2f81c073-caf0-45c0-8d4b-27cc4d6a7521"
Parent: "ca016911-4500-439a-b8d3-6206b41b174a"
Template: "ca016911-4500-439a-b8d3-6206b41b174a"
Path: /sitecore/templates/Feature/Destinations/Amend/Amend Payment Summary/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "02fd82d8-d670-41b2-b9ce-ea660ae93000"
      Hint: AmountPaidByCard
      Value: Amount paid by card
    - ID: "0399b89b-bd1f-43ed-b17d-1f9256203f7f"
      Hint: TotalCost
      Value: Total cost
    - ID: "10c69416-c6ae-4c2c-b16f-c285b9168eb2"
      Hint: TakeFromBalanceForTransferDescription
      Value: "When you click “Confirm”, you will receive an email to confirm we have successfully changed your transfer and took off {amount} off your existing holiday balance of {balanceAmount}. You will see this refund break down on your booking and in your confirmation email."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230330T100036Z
    - ID: "26c9cb8c-50d4-451b-9b3e-01b8d742978b"
      Hint: EligibleForCreditRefundDescription
      Value: "You are eligible for a credit refund of the remaining amount {creditAmount}."
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "7e753a77-f141-450f-a35d-c943039ab30c"
      Hint: CurrentBalanceLabel
      Value: Current balance
    - ID: "86276725-7c9f-43f4-a9e1-73f130408393"
      Hint: BalanceReduction
      Value: Balance reduction
    - ID: "94e8bcf1-c799-4e84-8db5-509ce0f7a720"
      Hint: BalanceWillBePaidDescription
      Value: <b>The entire balance will be paid off.</b>
    - ID: "9bea4504-96bb-4d14-aa83-eda1423f932d"
      Hint: TakeFromBalanceForFlightDescription
      Value: "When you click “Confirm”, you will receive an email to confirm we have successfully changed your flight and took off {amount} off your existing holiday balance of {balanceAmount}. You will see this refund break down on your booking and in your confirmation email."
    - ID: "a75d4454-67ed-45c2-b7fd-b52abc2c4bc8"
      Hint: EligibleForOMOPRefundDescription
      Value: "You are eligible for a cash refund of {cashAmount}."
    - ID: "b1cdbc1a-22c1-44c1-a78f-fe8bdaf60069"
      Hint: TakeAmountOffBalance
      Value: Take amount off existing balance
    - ID: "c75dd98d-2c30-400f-9104-ae34e3e571e1"
      Hint: PreviousBalanceLabel
      Value: Previous Balance
    - ID: "e28e41f9-0000-4023-b137-0ea4647c04b6"
      Hint: ConfirmChangesLabel
      Value: Confirm changes
    - ID: "e759f2f0-8f7c-4a0a-b126-8b31276e462e"
      Hint: ConfirmRefund
      Value: Get refund
    - ID: "f42bad3c-d18c-48e5-a430-4df9c6787af2"
      Hint: RefundCreditsTitle
      Value: Holiday Credit
    - ID: "f4a11d24-1b4e-4043-a2dc-8e7edfd44e49"
      Hint: AdditionalCost
      Value: Additional cost
