---
ID: "a90406f3-3925-4131-9885-63593cb90601"
Parent: "311c3f85-feb2-432e-98a9-dfba26c95a0c"
Template: "311c3f85-feb2-432e-98a9-dfba26c95a0c"
Path: /sitecore/templates/Feature/PageContent/Hotel Poster/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "055a3063-586a-4901-93fd-3f9c2480d7e1"
      Hint: LogoCheckboxLabel
      Value: Place easyJet holidays logo
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220802T140956Z
    - ID: "2f0fd5f2-8ef7-4c8d-99be-900ddc1bad9a"
      Hint: Title
      Value: You're about to download a summary of the holiday as a PDF file
    - ID: "3c4120a8-fc36-4f06-b4a7-3274efc91838"
      Hint: DepositLabel
      Value: Book with just £60pp deposit
    - ID: "47e8018f-cd86-4191-a8d0-544d04cc9c5c"
      Hint: LogoImage
      Value: |
        <image mediaid="{01548208-7DD9-42DA-A595-49CB9F683C93}" />
    - ID: "49700807-45d4-4d80-b811-24cf3103044d"
      Hint: AirportLabel
      Value: Flying from
    - ID: "4ca74fb1-4b2a-41c2-b460-1c6dde2b8f6a"
      Hint: ExportPromoLabel
      Value: Export promotional poster
    - ID: "5069d8fd-750f-451d-8ef3-4dc379fccc84"
      Hint: RoundUpDescription
      Value: "Your original price is £{price}. We round it up."
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "5f6d8682-bf41-4eaa-af3f-a3cac85b8cf2"
      Hint: ReturnLabel
      Value: Back to extras
    - ID: "64f8b142-c4f5-4893-8268-5a51948f6ea3"
      Hint: RoundUpTitle
      Value: "Please be informed a price is round-up"
    - ID: "6fc927df-f428-4ddb-b06d-23846c68adc6"
      Hint: Description
      Value: Please have a look at a preview of the PDF
    - ID: "97653f3d-5f73-48da-87f1-82fefd428f1c"
      Hint: Title
      Value: sdfsdff
    - ID: "ae452024-e6d2-479c-8d7c-d6959dd91c40"
      Hint: BoardLabel
      Value: "Board:"
    - ID: "b399e83d-2bd4-4695-b354-c01e233039d4"
      Hint: DownloadLabel
      Value: Download
    - ID: "bfd1737f-8a11-44ff-b05f-dfa23f63866c"
      Hint: ConclusionLabel
      Value: Booking conditions apply. Prices subject to change
    - ID: "e307c736-614d-43cc-b8e6-b0818a1ebe0f"
      Hint: Description
      Value: sdfsdfs
    - ID: "f1fb6493-e07f-4e70-b0d0-ab12577bc52b"
      Hint: RoomLabel
      Value: "Room:"
    - ID: "f6172b59-8eca-43c3-9ebe-a809ff6010ef"
      Hint: ExportPromoTooltip
      Value: You're able to download a summary of the holiday as a PDF file.
    - ID: "fa397d21-84e8-4edd-b8d5-a2c475db0f84"
      Hint: Link
      Value: |
        <link linktype="internal" />
