---
ID: "90dbc140-a3b5-4a98-8962-e6aa3732618e"
Parent: "8c2b3723-24ed-4769-82d3-597f9f12acfc"
Template: "8c2b3723-24ed-4769-82d3-597f9f12acfc"
Path: /sitecore/templates/Foundation/Destinations/Star Ratings/Star Ratings Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{C170404A-44A8-4069-AFB7-22A694E46628}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190701T163407Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
