---
ID: "f85e596c-525b-406b-8ad3-9b419af322c1"
Parent: "d16c697d-b159-42da-ab16-7d103a624ffa"
Template: "d16c697d-b159-42da-ab16-7d103a624ffa"
Path: /sitecore/templates/Feature/PageContent/Footer Tile/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201013T065643Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d4586172-6292-4442-b6a1-3b0c851d8f3c"
      Hint: Title
      Value: $name
