---
ID: "96803059-b1be-4db3-af26-a4297762f204"
Parent: "d5ce025f-cb0e-4e12-917b-1a5fffe3a589"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Project/Holidays/Site Settings/Booking Settings/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230215T093847Z
