---
ID: "08a092c2-12f0-4197-b686-3ff280c73f0b"
Parent: "6eb9d51d-3d3a-465d-9709-acba91606b0f"
Template: "6eb9d51d-3d3a-465d-9709-acba91606b0f"
Path: /sitecore/templates/Project/MicroApps/UserManagement/Web Forms/_Base/Input Field/__Standard Values
DB: master
SharedFields:
- ID: "c6d980b1-1904-4de0-a5c8-587441e4ac92"
  Hint: Type
  Value: text
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220810T094013Z
