---
ID: "5f28b055-587c-4f9d-965b-5bf73231719b"
Parent: "37108e01-36bf-4f2f-ae60-b4081f5df204"
Template: "37108e01-36bf-4f2f-ae60-b4081f5df204"
Path: /sitecore/templates/Project/Holidays/Site Settings/Social Proofing Settings/__Standard Values
DB: master
SharedFields:
- ID: "3e9d7651-f97b-4252-963f-f9f6a944ced1"
  Hint: SocialProofingTrendingIcon
  Value: |
    <image mediaid="{0ABA0673-DE47-426A-9E58-1B9E4328ACB5}" />
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "0dd566de-c786-43b9-830c-5f0906adb978"
      Hint: SocialProofingTrendingText
      Value: "<b>Im Trend:</b> Mehr als 100x angesehen in den letzten 24 h"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260107T075356Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "0dd566de-c786-43b9-830c-5f0906adb978"
      Hint: SocialProofingTrendingText
      Value: "<b>Im Trend:</b> Mehr als 100x angesehen in den letzten 24 h"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260107T075517Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0dd566de-c786-43b9-830c-5f0906adb978"
      Hint: SocialProofingTrendingText
      Value: "<b>Trending now:</b> 100+ people viewed this hotel in the last 24h"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260107T073902Z
- Language: "fr-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "0dd566de-c786-43b9-830c-5f0906adb978"
      Hint: SocialProofingTrendingText
      Value: "<b>Hôtel populaire :</b> plus de 100 vues dans les dernières 24 h"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260107T075320Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "0dd566de-c786-43b9-830c-5f0906adb978"
      Hint: SocialProofingTrendingText
      Value: "<b>Hôtel populaire :</b> plus de 100 vues dans les dernières 24 h"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260107T075446Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
