<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src/Foundation/Optimizely/code/easyJet.Foundation.Optimizely.csproj" />
    </ItemGroup>
</Project>