---
ID: "3f8b6dee-a756-4211-8f47-8bffccd7a1d4"
Parent: "c30c3a39-e88f-4cc8-98b4-9d121678de2f"
Template: "c30c3a39-e88f-4cc8-98b4-9d121678de2f"
Path: /sitecore/templates/Foundation/Presentation/Rendering Parameters/Help Links Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190723T154529Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
