<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsTestProject>true</IsTestProject>
        <Nullable>warnings</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AutoFixture.AutoMoq" />
        <PackageReference Include="AutoFixture.Xunit3" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.AspNetCore.Http" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\easyJet.Holidays.Api.Domain\easyJet.Holidays.Api.Domain.csproj" />
      <ProjectReference Include="..\easyJet.Holidays.External.DataHub\easyJet.Holidays.External.DataHub.csproj" />
      <ProjectReference Include="..\easyJet.Holidays.Tests.Domain\easyJet.Holidays.Tests.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>