---
ID: "2cbb435d-7669-44bc-86d7-991763a6a801"
Parent: "f6c0b2ce-38b2-4417-9976-13ec142d5a1c"
Template: "f6c0b2ce-38b2-4417-9976-13ec142d5a1c"
Path: /sitecore/templates/Foundation/Presentation/Partial Designs Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{7C12F137-9A9F-40B6-96A8-4F37F8CBC632}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190923T092605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
