import { mockSitecoreField, mockSitecoreImageField } from 'frontend/utils/tests.utils';
import { ISearchPodDataFields } from 'frontend/components/renderings/SearchPod/models';

export const mockSearchPodDataFields: ISearchPodDataFields = {
    BackToSearchButtonText: mockSitecoreField('BackToSearchButtonText'),
    ClearRecentSearches: mockSitecoreField('ClearRecentSearches'),
    CloseRecentSearches: mockSitecoreField('CloseRecentSearches'),
    CloseSearchCriteria: mockSitecoreField('CloseSearchCriteria'),
    CloseSearchCriteriaMobile: mockSitecoreField('CloseSearchCriteriaMobile'),
    DisableRouteErrorTitle: mockSitecoreField('DisableRouteErrorTitle'),
    EditSearch: mockSitecoreField('EditSearch'),
    EditSearchMobile: mockSitecoreField('EditSearchMobile'),
    FromDropdownLabel: mockSitecoreField('FromDropdownLabel'),
    FromDropdownStatusResultsCount: mockSitecoreField('Found {number} airports'),
    FromFieldAriaDescription: mockSitecoreField('FromFieldAriaDescription'),
    FromFieldDropdownToggle: mockSitecoreField('FromFieldDropdownToggle'),
    FromFieldPlaceholder: mockSitecoreField('FromFieldPlaceholder'),
    InspirationCalloutHolidaysText: mockSitecoreField('InspirationCalloutHolidaysText'),
    InspirationCalloutHolidaysTitle: mockSitecoreField('InspirationCalloutHolidaysTitle'),
    InspirationCalloutTradePortalText: mockSitecoreField('InspirationCalloutTradePortalText'),
    InspirationCalloutTradePortalTitle: mockSitecoreField('InspirationCalloutTradePortalTitle'),
    LoadingLabel: mockSitecoreField('LoadingLabel'),
    NewSearchLabel: mockSitecoreField('NewSearchLabel'),
    NewSearchLabelMobile: mockSitecoreField('NewSearchLabelMobile'),
    NoResultFoundDescription: mockSitecoreField('NoResultFoundDescription'),
    NoResultFoundTitle: mockSitecoreField('NoResultFoundTitle'),
    PerfectHolidayTitle: mockSitecoreField('PerfectHolidayTitle'),
    RecentSearchesLabel: mockSitecoreField('RecentSearchesLabel'),
    ResetToDefaultLabel: mockSitecoreField('ResetToDefaultLabel'),
    ResultLabel: mockSitecoreField('ResultLabel'),
    ResultsLabel: mockSitecoreField('ResultsLabel'),
    SearchToHotelMessageIcon: mockSitecoreField(mockSitecoreImageField('new-icon.png')),
    CheapestMonthIcon: mockSitecoreField(mockSitecoreImageField('cheapest-month-icon.png')),
    SearchToHotelMessageText: mockSitecoreField('SearchToHotelMessageText'),
    SearchToHotelMessageTitle: mockSitecoreField('SearchToHotelMessageTitle'),
    ToAllGroupCheckboxLabel: mockSitecoreField('ToAllGroupCheckboxLabel'),
    ToDropdownLabel: mockSitecoreField('ToDropdownLabel'),
    ToFieldAriaDescription: mockSitecoreField('ToFieldAriaDescription'),
    ToFieldDropdownToggle: mockSitecoreField('ToFieldDropdownToggle'),
    ToFieldLabel: mockSitecoreField('ToFieldLabel'),
    ToFieldPlaceholder: mockSitecoreField('ToFieldPlaceholder'),
    TryAdjustDatesErrorMessage: mockSitecoreField('TryAdjustDatesErrorMessage'),
    ViewRecentSearchesPlural: mockSitecoreField('ViewRecentSearchesPlural'),
    ViewRecentSearchesSingular: mockSitecoreField('ViewRecentSearchesSingular'),
    WhenFieldAriaDescription: mockSitecoreField('WhenFieldAriaDescription'),
    WhenFieldLabel: mockSitecoreField('WhenFieldLabel'),
    WhenFieldPlaceholder: mockSitecoreField('WhenFieldPlaceholder'),
    WhoDropdownGuestsLabel: mockSitecoreField('WhoDropdownGuestsLabel'),
    WhoDropdownGuestsLimitLabel: mockSitecoreField('WhoDropdownGuestsLimitLabel'),
    WhoDropdownRoomsLabel: mockSitecoreField('WhoDropdownRoomsLabel'),
    WhoFieldDropdownLabel: mockSitecoreField('WhoFieldDropdownLabel'),
    WhoFieldLabel: mockSitecoreField('WhoFieldLabel'),
    WhoFieldPlaceholder: mockSitecoreField('WhoFieldPlaceholders'),
    DateTabLabel: mockSitecoreField('DateTabLabel'),
    MonthTabLabel: mockSitecoreField('MonthTabLabel'),
    DurationLabel: mockSitecoreField('DurationLabel'),
    WhenDropdownTitle: mockSitecoreField('WhenDropdownTitle'),
    CheapestMonthDescriptionLabel: mockSitecoreField('CheapestMonthDescriptionLabel'),
    CheapestMonthLabel: mockSitecoreField('CheapestMonthLabel'),
    CheapestMonthUnavailableLabel: mockSitecoreField('CheapestMonthUnavailableLabel'),
};

export const createMockLocalStore = (): { fields: ISearchPodDataFields } => ({
    fields: mockSearchPodDataFields,
});
