---
ID: "9c64df5b-32bd-4d6c-8bf7-fa1418258f62"
Parent: "12e7fe01-6b76-4e7d-8349-fb20d5f14c47"
Template: "12e7fe01-6b76-4e7d-8349-fb20d5f14c47"
Path: /sitecore/templates/Foundation/Destinations/Facilities/Facility Types Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{7E1CEEB8-9A59-4584-91E8-6014A5B0FF56}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190710T133846Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
