---
ID: "6581c610-8330-42df-ba32-b4e35e2b1432"
Parent: "836c6200-091f-4bd3-9b0a-007c9ae39231"
Template: "836c6200-091f-4bd3-9b0a-007c9ae39231"
Path: /sitecore/templates/Foundation/Multisite/Site/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190329T101059Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
