---
ID: "609a034a-6b35-46ca-a1e1-68780b3f28f5"
Parent: "f8081879-7250-40e0-9b3a-50325ffd568b"
Template: "f8081879-7250-40e0-9b3a-50325ffd568b"
Path: /sitecore/templates/Foundation/Destinations/Base/Payment/_Base Payment Images/__Standard Values
DB: master
SharedFields:
- ID: "1209d295-fbaa-4cd0-86eb-9aaa41eca52c"
  Hint: IssueNumberInfo
  Value: |
    <image mediaid="{9C046B89-DB21-4E98-BBDD-A39DC7B8D784}" />
- ID: "2c032182-fa5b-4632-b374-a32248deaafa"
  Hint: PaymentImages
  Type: Treelist
  Value: |
    {19D3ED30-17EA-4774-840D-7A7BFAE6926A}
    {0D275411-1860-4794-85DC-E20CCFEE7E92}
    {EA7A5C7C-672B-4164-BE58-36B1FE4415DD}
    {E04FBB64-3414-49D0-9003-684002B31EDB}
    {CA0BEA75-4E5B-4385-87CB-5866133C1345}
    {CA99592F-A46A-4F1F-94BA-AEDE0F8A2361}
- ID: "fcd4caf5-7ec5-4fa3-935c-c75565587d65"
  Hint: CvvInfo
  Value: |
    <image mediaid="{F5BF2F87-BA36-4B7E-B300-D0E3DC117EFB}" />
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230607T053716Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "626fc719-dd40-4011-bb9c-c74b66650e7f"
      Hint: CvvInfoAMEX
      Value: |
        <image mediaid="{3C3FEA8B-FB56-4261-844E-F38C68019CEB}" />
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230607T053815Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "626fc719-dd40-4011-bb9c-c74b66650e7f"
      Hint: CvvInfoAMEX
      Value: |
        <image mediaid="{3C3FEA8B-FB56-4261-844E-F38C68019CEB}" />
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220209T103457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "626fc719-dd40-4011-bb9c-c74b66650e7f"
      Hint: CvvInfoAMEX
      Value: |
        <image mediaid="{3C3FEA8B-FB56-4261-844E-F38C68019CEB}" />
- Language: "fr-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230607T053603Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "626fc719-dd40-4011-bb9c-c74b66650e7f"
      Hint: CvvInfoAMEX
      Value: |
        <image mediaid="{3C3FEA8B-FB56-4261-844E-F38C68019CEB}" />
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230607T053743Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "626fc719-dd40-4011-bb9c-c74b66650e7f"
      Hint: CvvInfoAMEX
      Value: |
        <image mediaid="{3C3FEA8B-FB56-4261-844E-F38C68019CEB}" />
