---
ID: "b47d2c71-141e-4dec-9d77-7cb066a5a8d4"
Parent: "a358efb7-ee1e-442c-82a2-4f2563e83a3c"
Template: "a358efb7-ee1e-442c-82a2-4f2563e83a3c"
Path: /sitecore/templates/Foundation/Destinations/Itinerary/Itinerary/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{EB0BE30E-074A-424E-9956-C120F63E2F2B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191015T114941Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "cbb87388-40eb-4aa9-adae-517fc4be2bf4"
      Hint: TotalDistance
      Value: 
