module.exports = {
    extends: ['stylelint-config-standard', 'stylelint-config-standard-scss'],
    customSyntax: 'postcss-scss',
    plugins: ['stylelint-order', 'stylelint-scss'],
    rules: {
        'alpha-value-notation': 'number',
        'color-function-notation': 'legacy',
        'at-rule-empty-line-before': null,
        'at-rule-no-unknown': null,
        'at-rule-disallowed-list': ['extend'],
        'color-named': ['never', , { ignore: ['inside-function'] }],
        'comment-empty-line-before': ['always', { except: ['first-nested'], ignore: ['stylelint-commands'] }],
        'comment-whitespace-inside': 'always',
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-redundant-longhand-properties': [true, { ignoreShorthands: ['inset', '/grid/'] }],
        'no-descending-specificity': null,
        'length-zero-no-unit': [true, { ignore: ['custom-properties'] }],
        'order/properties-alphabetical-order': null,
        'order/properties-order': [
            [
                'content',

                // Position
                'position',
                'z-index',
                'top',
                'right',
                'bottom',
                'left',

                // Display
                'display',
                'box-sizing',

                // Flex
                'flex',
                'flex-align',
                'flex-basis',
                'flex-direction',
                'flex-wrap',
                'flex-flow',
                'flex-shrink',
                'flex-grow',
                'flex-order',
                'flex-pack',
                'align-content',
                'align-items',
                'align-self',
                'justify-content',
                'order',

                /** Grid **/
                'grid',
                'grid-area',
                'grid-template',
                'grid-template-areas',
                'grid-template-rows',
                'grid-template-columns',
                'grid-row',
                'grid-row-start',
                'grid-row-end',
                'grid-column',
                'grid-column-start',
                'grid-column-end',
                'grid-auto-rows',
                'grid-auto-columns',
                'grid-auto-flow',
                'grid-gap',
                'grid-row-gap',
                'grid-column-gap',
                'gap',
                'row-gap',
                'column-gap',

                // Box model
                'float',
                'width',
                'min-width',
                'max-width',
                'height',
                'min-height',
                'max-height',
                'margin',
                'margin-top',
                'margin-right',
                'margin-bottom',
                'margin-left',
                'padding',
                'padding-top',
                'padding-right',
                'padding-bottom',
                'padding-left',
                'overflow',
                'overflow-x',
                'overflow-y',
                'columns',
                'column-count',
                'column-fill',
                'column-gap',
                'column-rule',
                'column-rule-width',
                'column-rule-style',
                'column-rule-color',
                'column-span',
                'column-width',
                'clip',
                'clear',
                'object-fit',
                'object-position',

                // Typography
                'font',
                'font-family',
                'font-display',
                'font-size',
                'font-style',
                'font-weight',
                'font-variant',
                'font-size-adjust',
                'font-stretch',
                'font-effect',
                'font-emphasize',
                'font-emphasize-position',
                'font-emphasize-style',
                'font-smooth',
                'src',
                'hyphens',
                'line-height',
                'vertical-align',
                'color',
                'text-align',
                'text-align-last',
                'text-emphasis',
                'text-emphasis-color',
                'text-emphasis-style',
                'text-emphasis-position',
                'text-decoration',
                'text-indent',
                'text-justify',
                'text-outline',
                'text-overflow',
                'text-overflow-ellipsis',
                'text-overflow-mode',
                'text-shadow',
                'text-transform',
                'text-wrap',
                'letter-spacing',
                'word-break',
                'word-spacing',
                'word-wrap',
                'overflow-wrap',
                'white-space',
                'direction',
                'list-style',
                'list-style-position',
                'list-style-type',
                'list-style-image',

                // Background
                'background',
                'background-color',
                'background-image',
                'background-repeat',
                'background-attachment',
                'background-position',
                'background-position-x',
                'background-position-y',
                'background-clip',
                'background-origin',
                'background-size',

                // Border
                'border',
                'border-color',
                'border-style',
                'border-width',
                'border-top',
                'border-top-color',
                'border-top-style',
                'border-top-width',
                'border-right',
                'border-right-color',
                'border-right-style',
                'border-right-width',
                'border-bottom',
                'border-bottom-color',
                'border-bottom-style',
                'border-bottom-width',
                'border-left',
                'border-left-color',
                'border-left-style',
                'border-left-width',
                'border-radius',
                'border-top-left-radius',
                'border-top-right-radius',
                'border-bottom-right-radius',
                'border-bottom-left-radius',
                'border-image',
                'border-image-source',
                'border-image-slice',
                'border-image-width',
                'border-image-outset',
                'border-image-repeat',

                // Outline
                'outline',
                'outline-width',
                'outline-style',
                'outline-color',
                'outline-offset',

                'box-shadow',
                'filter',
                'opacity',
                'visibility',
                'cursor',
                'pointer-events',
                'user-select',
                'table-layout',
                'empty-cells',
                'caption-side',
                'border-spacing',
                'border-collapse',
                'quotes',
                'counter-reset',
                'counter-increment',
                'resize',
                'page-break-after',
                'page-break-before',
                'page-break-inside',
                'zoom',

                // SVG
                'fill',
                'stroke',

                // Transform
                'transform',
                'transform-origin',
                'perspective',
                'appearance',

                // Transition
                'transition',
                'transition-delay',
                'transition-timing-function',
                'transition-duration',
                'transition-property',

                // Animation
                'animation',
                'animation-name',
                'animation-duration',
                'animation-play-state',
                'animation-timing-function',
                'animation-delay',
                'animation-iteration-count',
                'animation-direction',
                'animation-fill-mode',
            ],
            {
                unspecified: 'bottom',
            },
        ],
        'property-no-vendor-prefix': [true, { ignoreProperties: ['appearance', 'column-break-inside'] }],
        'selector-class-pattern': null,
        'selector-max-compound-selectors': 4,
        'selector-max-id': 0,
        'shorthand-property-no-redundant-values': true,
        'value-keyword-case': ['lower', { ignoreKeywords: ['Arial', 'Helvetica'] }],
        'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }],
        'property-no-unknown': [true, { ignoreProperties: ['composes'] }],

        // SCSS
        'scss/at-import-no-partial-leading-underscore': true,
        'scss/at-import-partial-extension': 'never',
        'scss/at-rule-no-unknown': true,
        'scss/dollar-variable-first-in-block': [true, { ignore: ['comments', 'imports'] }],
        'scss/double-slash-comment-whitespace-inside': 'always',
        'scss/no-duplicate-mixins': true,
        'scss/operator-no-unspaced': true,
        'scss/selector-no-redundant-nesting-selector': true,
        'scss/selector-no-union-class-name': true,
        'no-missing-end-of-source-newline': true,
        'block-opening-brace-space-before': 'always',
        'scss/dollar-variable-pattern': '([a-z]([A-Z0-9]*[a-z][a-z0-9]*[A-Z]|[a-z0-9]*[A-Z][A-Z0-9]*[a-z])[A-Za-z0-9]*)|(^[a-z]+$)',
    },
};
