---
ID: "6e215de8-fb64-4906-882f-69bee91319e5"
Parent: "4edee9c4-1042-453a-b567-958be3d89da5"
Template: "4edee9c4-1042-453a-b567-958be3d89da5"
Path: /sitecore/templates/Project/Holidays/Pages/Payment Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4696E3CC-7DA0-4264-BF00-B6E49C11B857}">
        <r
          id="{6C234F53-080F-4C8E-AC01-CE83E3C28998}"
          ph="fph-header-titlebar"
          uid="{946F8C61-8778-4258-8261-E3DAFED3EC58}" />
        <r
          id="{6C234F53-080F-4C8E-AC01-CE83E3C28998}"
          ph="fph-header-subheader"
          uid="{D2C8460D-F8C8-4887-93CE-CFB625C08D09}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190620T203155Z
