using System;
using System.Collections.Generic;
using System.Linq;
using EasyJet.Foundation.SitecoreExtensions.Extensions;

namespace easyJet.Foundation.SitecoreExtensions.Utils
{
    public static class Transliteration
    {
        private static readonly char[] PairedCharacters = { '̇' };
        private static readonly Dictionary<char, string> TransliterationMap = new Dictionary<char, string>()
        {
            { 'Á', "A" },
            { 'À', "A" },
            { 'Â', "A" },
            { 'Ä', "Ae" },
            { 'Ã', "A" },
            { 'Ă', "A" },
            { 'Å', "AA" },
            { 'Ā', "A" },
            { 'Ą', "A" },
            { 'Ć', "C" },
            { 'Ĉ', "C" },
            { 'Č', "C" },
            { 'Ċ', "C" },
            { 'Ç', "C" },
            { 'Đ', "D" },
            { 'Ď', "D" },
            { 'É', "E" },
            { 'È', "E" },
            { 'Ê', "E" },
            { 'Ë', "E" },
            { 'Ě', "E" },
            { 'Ė', "E" },
            { 'Ē', "E" },
            { 'Ę', "E" },
            { 'Ĕ', "E" },
            { 'Ĝ', "G" },
            { 'Ğ', "G" },
            { 'Ġ', "G" },
            { 'Ģ', "G" },
            { 'Ħ', "H" },
            { 'Ĥ', "H" },
            { 'Í', "I" },
            { 'Ì', "I" },
            { 'Î', "I" },
            { 'Ï', "I" },
            { 'İ', "I" },
            { 'Ĩ', "I" },
            { 'Ī', "I" },
            { 'Ĭ', "I" },
            { 'Į', "I" },
            { 'Ĵ', "J" },
            { 'Ķ', "K" },
            { 'Ł', "L" },
            { 'Ĺ', "L" },
            { 'Ľ', "L" },
            { 'Ļ', "L" },
            { 'Ŀ', "L" },
            { 'Ń', "N" },
            { 'Ň', "N" },
            { 'Ñ', "N" },
            { 'Ņ', "N" },
            { 'Ø', "Oe" },
            { 'Ó', "O" },
            { 'Ò', "O" },
            { 'Ô', "O" },
            { 'Ö', "Oe" },
            { 'Õ', "O" },
            { 'Ő', "O" },
            { 'Ō', "O" },
            { 'Ŏ', "O" },
            { 'Ŕ', "R" },
            { 'Ŗ', "R" },
            { 'Ř', "R" },
            { 'Ś', "S" },
            { 'Ŝ', "S" },
            { 'Ş', "S" },
            { 'Š', "S" },
            { 'Ŧ', "T" },
            { 'Ť', "T" },
            { 'Ţ', "T" },
            { 'Ú', "U" },
            { 'Ù', "U" },
            { 'Û', "U" },
            { 'Ü', "Ue" },
            { 'Ũ', "U" },
            { 'Ŭ', "U" },
            { 'Ű', "U" },
            { 'Ů', "U" },
            { 'Ū', "U" },
            { 'Ų', "U" },
            { 'Ŵ', "W" },
            { 'Ŷ', "Y" },
            { 'Ź', "Z" },
            { 'Ž', "Z" },
            { 'Ż', "Z" },
            { 'Ý', "Y" },
            { 'Ÿ', "Y" },
            { 'Þ', "Th" },
            { 'Æ', "Ae" },
            { 'Ĳ', "Ij" },
            { 'Œ', "Oe" },
            { 'А', "A" },
            { 'Б', "B" },
            { 'В', "V" },
            { 'Г', "G" },
            { 'Д', "D" },
            { 'Е', "E" },
            { 'Ё', "E" },
            { 'Ж', "Zh" },
            { 'З', "Z" },
            { 'И', "I" },
            { 'І', "I" },
            { 'Й', "I" },
            { 'К', "K" },
            { 'Л', "L" },
            { 'М', "M" },
            { 'Н', "N" },
            { 'О', "O" },
            { 'П', "P" },
            { 'Р', "R" },
            { 'С', "S" },
            { 'Т', "T" },
            { 'У', "U" },
            { 'Ф', "F" },
            { 'Х', "Kh" },
            { 'Ц', "Ts" },
            { 'Ч', "Ch" },
            { 'Ш', "Sh" },
            { 'Щ', "Shch" },
            { 'Ы', "Y" },
            { 'Ъ', "Ie" },
            { 'Э', "E" },
            { 'Ю', "Iu" },
            { 'Я', "Ia" },
            { 'Ѵ', "Y" },
            { 'Ґ', "G" },
            { 'Ў', "U" },
            { 'Ѫ', "U" },
            { 'Ƒ', "G" },
            { 'Ђ', "D" },
            { 'Ѕ', "Dz" },
            { 'Α', "A" },
            { 'Ά', "A" },
            { 'Β', "V" },
            { 'Γ', "G" },
            { 'Δ', "D" },
            { 'Ε', "E" },
            { 'Έ', "E" },
            { 'Ζ', "Z" },
            { 'Η', "I" },
            { 'Ή', "I" },
            { 'Θ', "Th" },
            { 'Ι', "I" },
            { 'Ί', "I" },
            { 'Ϊ', "I" },
            { 'Κ', "K" },
            { 'Λ', "L" },
            { 'Μ', "M" },
            { 'Ν', "N" },
            { 'Ξ', "X" },
            { 'Ο', "O" },
            { 'Ό', "O" },
            { 'Π', "P" },
            { 'Ρ', "R" },
            { 'Σ', "S" },
            { 'Τ', "T" },
            { 'Υ', "Y" },
            { 'Ύ', "Y" },
            { 'Ϋ', "Y" },
            { 'Φ', "F" },
            { 'Χ', "Ch" },
            { 'Ψ', "Ps" },
            { 'Ω', "O" },
            { 'Ώ', "O" },

            // LOWERCASE
            { 'á', "a" },
            { 'à', "a" },
            { 'â', "a" },
            { 'ä', "ae" },
            { 'ã', "a" },
            { 'ă', "a" },
            { 'å', "aa" },
            { 'ā', "a" },
            { 'ą', "a" },
            { 'ć', "c" },
            { 'ĉ', "c" },
            { 'č', "c" },
            { 'ċ', "c" },
            { 'ç', "c" },
            { 'đ', "d" },
            { 'ď', "d" },
            { 'é', "e" },
            { 'è', "e" },
            { 'ê', "e" },
            { 'ë', "e" },
            { 'ě', "e" },
            { 'ė', "e" },
            { 'ē', "e" },
            { 'ę', "e" },
            { 'ĕ', "e" },
            { 'ĝ', "g" },
            { 'ğ', "g" },
            { 'ġ', "g" },
            { 'ģ', "g" },
            { 'ħ', "h" },
            { 'ĥ', "h" },
            { 'í', "i" },
            { 'ì', "i" },
            { 'î', "i" },
            { 'ï', "i" },
            { 'ĩ', "i" },
            { 'ī', "i" },
            { 'ĭ', "i" },
            { 'į', "i" },
            { 'ĵ', "j" },
            { 'ķ', "k" },
            { 'ł', "l" },
            { 'ĺ', "l" },
            { 'ľ', "l" },
            { 'ļ', "l" },
            { 'ŀ', "l" },
            { 'ń', "n" },
            { 'ň', "n" },
            { 'ñ', "n" },
            { 'ņ', "n" },
            { 'ø', "oe" },
            { 'ó', "o" },
            { 'ò', "o" },
            { 'ô', "o" },
            { 'ö', "oe" },
            { 'õ', "o" },
            { 'ő', "o" },
            { 'ō', "o" },
            { 'ŏ', "o" },
            { 'ŕ', "r" },
            { 'ŗ', "r" },
            { 'ř', "r" },
            { 'ś', "s" },
            { 'ŝ', "s" },
            { 'ş', "s" },
            { 'š', "s" },
            { 'ŧ', "t" },
            { 'ť', "t" },
            { 'ţ', "t" },
            { 'ú', "u" },
            { 'ù', "u" },
            { 'û', "u" },
            { 'ü', "ue" },
            { 'ũ', "u" },
            { 'ŭ', "u" },
            { 'ű', "u" },
            { 'ů', "u" },
            { 'ū', "u" },
            { 'ų', "u" },
            { 'ŵ', "w" },
            { 'ŷ', "y" },
            { 'ź', "z" },
            { 'ž', "z" },
            { 'ż', "z" },
            { 'ý', "y" },
            { 'ÿ', "y" },
            { 'þ', "th" },
            { 'æ', "ae" },
            { 'ĳ', "ij" },
            { 'œ', "oe" },
            { 'ß', "ss" },
            { 'а', "a" },
            { 'б', "b" },
            { 'в', "v" },
            { 'г', "g" },
            { 'д', "d" },
            { 'е', "e" },
            { 'ё', "e" },
            { 'ж', "zh" },
            { 'з', "z" },
            { 'и', "i" },
            { 'і', "i" },
            { 'й', "i" },
            { 'к', "k" },
            { 'л', "l" },
            { 'м', "m" },
            { 'н', "n" },
            { 'о', "o" },
            { 'п', "p" },
            { 'р', "r" },
            { 'с', "s" },
            { 'т', "t" },
            { 'у', "u" },
            { 'ф', "f" },
            { 'х', "kh" },
            { 'ц', "ts" },
            { 'ч', "ch" },
            { 'ш', "sh" },
            { 'щ', "shch" },
            { 'ы', "y" },
            { 'ъ', "ie" },
            { 'э', "e" },
            { 'ю', "iu" },
            { 'я', "ia" },
            { 'ѵ', "y" },
            { 'ґ', "g" },
            { 'ў', "u" },
            { 'ѫ', "u" },
            { 'ƒ', "g" },
            { 'ђ', "d" },
            { 'ѕ', "dz" },
            { 'α', "a" },
            { 'ά', "a" },
            { 'β', "v" },
            { 'γ', "g" },
            { 'δ', "d" },
            { 'ε', "e" },
            { 'έ', "e" },
            { 'ζ', "z" },
            { 'η', "i" },
            { 'ή', "i" },
            { 'θ', "th" },
            { 'ι', "i" },
            { 'ί', "i" },
            { 'ϊ', "i" },
            { 'κ', "k" },
            { 'λ', "l" },
            { 'μ', "m" },
            { 'ν', "n" },
            { 'ξ', "x" },
            { 'ο', "o" },
            { 'ό', "o" },
            { 'π', "p" },
            { 'ρ', "r" },
            { 'σ', "s" },
            { 'τ', "t" },
            { 'υ', "y" },
            { 'ύ', "y" },
            { 'ϋ', "y" },
            { 'φ', "f" },
            { 'χ', "ch" },
            { 'ψ', "ps" },
            { 'ω', "o" },
            { 'ώ', "o" },
            // Special symbols
            { '\'', " " }
        };

        private static readonly Dictionary<string, string> DoubleCharactertransliterationMap = new Dictionary<string, string>()
        {
            { "i̇", "i" }
        };

        /// <summary>
        /// Transliterates text to Latin alphabet.
        /// </summary>
        /// <param name="text">Text to be transliterated.</param>
        /// <returns>Transliterated text.</returns>
        public static string ToLatin(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            return new string(TransliterateCharacters(text.RemoveExtraSpaces()).ToArray());
        }

        private static IEnumerable<char> TransliterateCharacters(string text)
        {
            for (var i = 0; i < text.Length; i++)
            {
                var character = text[i];
                var isDoubleCharacter = i < text.Length - 1 && PairedCharacters.Contains(text[i + 1]);

                if (isDoubleCharacter)
                {
                    var doubleCharacter = text.Substring(i, 2);
                    if (DoubleCharactertransliterationMap.TryGetValue(doubleCharacter, out var result))
                    {
                        foreach (var c in result)
                        {
                            yield return c;
                        }
                    }
                    else
                    {
                        yield return character;
                    }

                    i++;
                }
                else
                {
                    if (TransliterationMap.TryGetValue(character, out var result))
                    {
                        foreach (var c in result)
                        {
                            yield return c;
                        }
                    }
                    else
                    {
                        yield return character;
                    }
                }
            }
        }
    }
}
