<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>warnings</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="AutoFixture.Xunit3" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="WireMock.Net" />
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\easyJet.Holidays.Api\easyJet.Holidays.Api.csproj" />
  </ItemGroup>
</Project>