---
ID: "114234e0-82a7-4f0c-9cc7-8750dd95d357"
Parent: "1d49467d-556b-48ce-a2cb-e54d8cd24622"
Template: "1d49467d-556b-48ce-a2cb-e54d8cd24622"
Path: /sitecore/templates/Foundation/Destinations/Requested Searches/Price Math Function/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210628T154927Z
