---
ID: "c9f9d1c3-a359-4a42-8604-9797c96a6967"
Parent: "d21e6a0c-4bd2-431a-8f11-583b0550e0fb"
Template: "d21e6a0c-4bd2-431a-8f11-583b0550e0fb"
Path: /sitecore/templates/Feature/PageContent/Inspire Me/Tag/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240402T144901Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
