<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="$(SolutionDir)SitecoreProject.props" />
  <PropertyGroup>
    <TargetFramework>$(FrameworkVersion)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="App_Config\Include\Foundation\easyJet.Foundation.BeCause.Debug.config" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Config\Include\Foundation\easyJet.Foundation.BeCause.config">
      <TransformOnBuild>true</TransformOnBuild>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)src\Foundation\Destinations\code\easyJet.Foundation.Destinations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>
**/Commands/CertificateSynchronisationCommand.cs, 
**/Commands/PushHotelDataCommand.cs, 
**/Commands/SyncEcoCertificatesCommand.cs, 
**/Logging/BeCauseLogger.cs, 
**/Models/CertificationSynchronisationResult.cs, 
**/Models/Request/CompaniesSearchRequest.cs, 
**/Models/Request/CompanyMatchRequest.cs, 
**/Models/Request/CustomIdentifier.cs, 
**/Models/Request/CustomProperty.cs, 
**/Models/Request/HotelMapping.cs, 
**/Models/Request/HotelMappingRequest.cs, 
**/Models/Request/Identifier.cs, 
**/Models/Request/LocationCoordinates.cs, 
**/Models/Request/MatchCompany.cs, 
**/Models/Request/MatchCompanyAddress.cs, 
**/Models/Request/StandardsSearchRequest.cs, 
**/Models/Response/Award.cs, 
**/Models/Response/Certification.cs, 
**/Models/Response/Commitment.cs, 
**/Models/Response/Company.cs, 
**/Models/Response/CompanyAddress.cs, 
**/Models/Response/CompanyAward.cs, 
**/Models/Response/CompanyCertification.cs, 
**/Models/Response/CompanyCommitment.cs, 
**/Models/Response/CompanyField.cs, 
**/Models/Response/CompanyMatchResponse.cs, 
**/Models/Response/CreateTaskResponse.cs, 
**/Models/Response/StandardsSearchResponse.cs, 
**/Models/Response/StatusResponse.cs, 
**/Models/Response/StatusResponseResult.cs, 
**/Services/SettingsService.cs
</Value>
    </SonarQubeSetting>
  </ItemGroup>
  <ItemGroup>
    <None Update="App_Config\Include\Foundation\easyJet.Foundation.BeCause.Debug.config">
      <IsTransformFile>true</IsTransformFile>
      <DependentUpon>easyJet.Foundation.BeCause.config</DependentUpon>
    </None>
  </ItemGroup>
</Project>