---
ID: "18983528-aa8d-4c16-a5ea-8890db48eac3"
Parent: "c15d9271-2185-4adc-9e17-ec2c8d51a7a0"
Template: "c15d9271-2185-4adc-9e17-ec2c8d51a7a0"
Path: /sitecore/templates/Feature/PageContent/FAQ Folder/__Standard Values
DB: master
SharedFields:
- ID: "10e02205-dc59-4c8e-ba94-3c76cd3751a9"
  Hint: NegativeActiveIcon
  Value: |
    <image mediaid="{F735F253-7414-402D-BBD9-1CB127E26613}" />
- ID: "1d14a92d-6d32-4eba-99e3-66beb93e00f5"
  Hint: PositiveActiveIcon
  Value: |
    <image mediaid="{4121BBBA-ECAB-4110-8D06-B946F0E57B1A}" />
- ID: "92b7e225-3b1a-4c91-88fe-cf478352915d"
  Hint: PositiveInactiveIcon
  Value: |
    <image mediaid="{AD288B44-7F12-4EC3-8234-3E0BE4246B1C}" />
- ID: "d93bf10a-b180-4c1f-a8b8-8893d945d222"
  Hint: NegativeInactiveIcon
  Value: |
    <image mediaid="{B4E522FF-90FD-43BE-B8E8-9998201C826C}" />
- ID: "f9694b29-0991-49f4-ab28-bbc897839fea"
  Hint: RatingQuestion
  Value: "Was this answer useful?"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210608T140455Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
