---
ID: "aa69ff2e-d346-4d26-88c7-0ec0566076c0"
Parent: "66ec3497-e5ee-4091-b761-11e0789b5810"
Template: "66ec3497-e5ee-4091-b761-11e0789b5810"
Path: /sitecore/templates/Feature/PageContent/Social Media Poster/__Standard Values
DB: master
SharedFields:
- ID: "49816243-6b6f-45ab-b5e3-d0a5b0583b4c"
  Hint: LeftSectionTitle
  Value: Step 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0a864a08-dd62-4585-a689-66ecc92b673b"
      Hint: RightSectionTitle
      Value: Step 2
    - ID: "2392838d-26b2-48fb-b7c4-1c6e5c7950df"
      Hint: DepositLabel
      Value: BOOK NOW FOR £60 DEPOSIT
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231219T182604Z
    - ID: "2e54121b-4ed6-48f1-a55b-6b5b5e0c77d0"
      Hint: RightSectionDesc
      Value: Copy this text content for your social media post
    - ID: "3486c907-2266-4b9f-8c3b-f5b89324e36d"
      Hint: LeftSectionDesc
      Value: Copy and paste, or download the image
    - ID: "45fb7a8e-2744-4f35-9478-aec4004577ef"
      Hint: AirportLabel
      Value: "Flying from {airport}"
    - ID: "49816243-6b6f-45ab-b5e3-d0a5b0583b4c"
      Hint: LeftSectionTitle
      Value: Step 1
    - ID: "56e60c5f-83ca-4b06-80e8-30a3d694a2a3"
      Hint: PriceCheckboxLabel
      Value: Include price and number of nights
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ae40fd2e-94d4-4c16-a64a-4a313ba9bea4"
      Hint: CopyLabel
      Value: Copy text to clipboard
    - ID: "aefe13e4-44f7-4b61-87c2-b3b032b9800b"
      Hint: DownloadDesc
      Value: Or right click to copy or save as
