---
ID: "7d32d2e4-e48e-4e44-a9dd-d7b9159d24c4"
Parent: "a5492194-4104-4bb1-b995-43aa24c683c0"
Template: "a5492194-4104-4bb1-b995-43aa24c683c0"
Path: /sitecore/templates/Foundation/Destinations/Transfers/Accommodation Transfers Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{6867DAC6-4C72-4652-9011-A5B85284480F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191202T105615Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
