---
ID: "eb3333b1-16a1-4dd5-bf5f-9eb3f80906e4"
Parent: "4afc3cfd-509b-4b95-b616-b1fb097062a4"
Template: "4afc3cfd-509b-4b95-b616-b1fb097062a4"
Path: /sitecore/templates/Foundation/Destinations/Facilities/Facility Typology/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190710T134104Z
