---
ID: "eb0838f7-9157-417d-b9bd-aecbcff25097"
Parent: "879eb2a6-6077-48fa-bf9f-e49cea6e606c"
Template: "879eb2a6-6077-48fa-bf9f-e49cea6e606c"
Path: /sitecore/templates/Project/MicroApps/UserManagement/Components/Common/Navigation/Protected Navigation Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190708T122650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "bc63dcbe-8830-4744-b9d8-42b4ef91154a"
      Hint: LinkUrl
      Value: |
        <link text="$name" linktype="anchor" url="#" anchor="#" title="" class="" />
