---
ID: "24de074e-4408-4e57-aad6-2d7318c5ab9b"
Parent: "63b69a46-83dc-4664-96c8-2a3936be67fd"
Template: "63b69a46-83dc-4664-96c8-2a3936be67fd"
Path: /sitecore/templates/Feature/Destinations/Pay Balance/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1fe37127-a211-43cb-88e1-8fa590c466b8"
      Hint: UseCreditDescription
      Value: "Pay today and use your <strong>{amount}</strong> holiday credit to put towards your holiday."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200203T123101Z
    - ID: "379b8d95-c70e-493b-9129-10305856b94c"
      Hint: AmountToPayByCard
      Value: "Please enter your card details to pay the remaining {amount}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "92da82ae-e844-4144-bd90-74208bcf1885"
      Hint: PaymentDeny
      Value: |
        Unfortunately we haven&rsquo;t been able to authorise your payment. Please contact easyJet Holidays customer services on 0330 365 5005 (Opening times: 8am to 8pm) and quote the error code shown below:<br />
        Error Code: 267<rprot001><br />
        Contact Us - <a href="https://www.easyjet.com/en/help/contact">https://www.easyjet.com/en/help/contact</a><br />
        If you&rsquo;re attempting to book a holiday departing within the next 30 days please call us to ensure the matter is resolved as soon as possible.</rprot001>
    - ID: "b0278b0f-9679-443f-96ec-20362037e87f"
      Hint: ShowInstalments
      Type: Checkbox
      Value: 1
    - ID: "bbf871ce-cc34-4e34-a543-f0b91cca4ecd"
      Hint: ResidualBalance
      Value: 0
