<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\easyJet.Holidays.External.Domain\easyJet.Holidays.External.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Services\IHolidayExtrasService.cs" />
    </ItemGroup>

</Project>
