---
ID: "e8b35089-132d-4855-8ca4-5cf2aefb6fb1"
Parent: "5a096e10-91a7-48bc-92c6-7cbc866391c4"
Template: "5a096e10-91a7-48bc-92c6-7cbc866391c4"
Path: /sitecore/templates/Feature/Destinations/Luggage Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Fields:
  - ID: "7676155b-64f2-4a1d-bf3a-21370ab9ac82"
    Hint: ReadMoreLink
    Value: |
      <link text="Read more about bags" linktype="external" url="http://www.easyjet.com/en/help/baggage/cabin-bag-and-hold-luggage" anchor="" target="_blank" />
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191226T130642Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
