---
ID: "8b6b4122-def7-4149-9db9-1e0dd586557c"
Parent: "b2e19d15-e198-4719-b239-52bd8c8b0d23"
Template: "b2e19d15-e198-4719-b239-52bd8c8b0d23"
Path: /sitecore/templates/Project/Trade Portal/Pages/Feedback Form Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221010T184503Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
