###

# @name Payment Methods Settings
# @description Call for Payment Methods Setting (to check if Apple Pay is enabled or not). Notice you can change language at the end
# @expected status=200

GET {{sitecore-host}}/api/Content/ByPath?path={site}/Settings/Payment Methods Settings&withChildren=false&readAll=true&sc_lang=en
