---
ID: "9631f7e5-ca3b-4b8b-9af5-011f026cd92c"
Parent: "0ed3d67e-3dc1-41c8-a5f2-ddf3308df4e2"
Template: "0ed3d67e-3dc1-41c8-a5f2-ddf3308df4e2"
Path: /sitecore/templates/Foundation/Destinations/Filters/Recommended Filters Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {EE8ACAA4-83E6-40D4-98F3-0F0DDC61BF4D}
    {42F5F481-5C03-4678-AA41-3960BA7E5144}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260305T232312Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6bccb5a6-b93e-4a29-a772-10bb6279ea09"
      Hint: MinNumberOfOffers
      Value: 1
