<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Sitecore.Publishing.Service" />
        <PackageReference Include="Sitecore.Publishing.Service.Client.Http" />
        <PackageReference Include="AWSSDK.Core" />
        <PackageReference Include="AWSSDK.SQS" />
    </ItemGroup>
    <Import Project="$(SolutionDir)TestProject.props" />
    <PropertyGroup>
        <TargetFramework>$(FrameworkVersion)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src/Feature/ScrappingTrigger/code/easyJet.Feature.ScrappingTrigger.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Foundation\AmazonSecurityToken\code\easyJet.Foundation.AmazonSecurityToken.csproj" />
    </ItemGroup>
</Project>