---
ID: "d99f3e2c-a3b1-47c5-8a8b-c4dc8150115c"
Parent: "f2aedd6f-5be8-4833-84d2-8de7aba3d3d1"
Template: "f2aedd6f-5be8-4833-84d2-8de7aba3d3d1"
Path: /sitecore/templates/Feature/PageContent/Navigation Link Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {BC011F0A-976C-4825-9E01-8BAA7C8E6CCA}
    {18693804-D215-4F1C-9663-E1F8935C0BAA}
    {F2AEDD6F-5BE8-4833-84D2-8DE7ABA3D3D1}
    {9199B3BC-4E4F-4226-8D81-5BE345ECD811}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190708T122655Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
