<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" />
    <PackageReference Include="AWSSDK.DynamoDBv2" />
  </ItemGroup>
  <Import Project="$(SolutionDir)SitecoreProject.props" />
  <PropertyGroup>
    <TargetFramework>$(FrameworkVersion)</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratedAssemblyInfoFile>Properties\Assemblyinfo.cs</GeneratedAssemblyInfoFile>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="App_Config\Include\Foundation\easyJet.Foundation.DynamoDb.config">
      <TransformOnBuild>true</TransformOnBuild>
    </Content>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.DynamoDb.CI.config">
      <DependentUpon>easyJet.Foundation.DynamoDb.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.DynamoDb.Debug.config">
      <DependentUpon>easyJet.Foundation.DynamoDb.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="App_Config\Include\Foundation\easyJet.Foundation.DynamoDb.Release.config">
      <DependentUpon>easyJet.Foundation.DynamoDb.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
  </ItemGroup>
</Project>