//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace easyJet.Holidays.External.Atcom.Models.Internal
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/FlightExtraSearchRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AtComRes/FlightExtraSearchRequest", IsNullable = false)]
    public partial class FlightExtraSearchRequest : AtcomresBaseOfferSearchRequest
    {

        private FlightExtraSearchRequestBase_Prd base_PrdField;

        private Pax[] paxField;

        private Ref refField;

        private bool refFieldSpecified;

        /// <remarks/>
        public FlightExtraSearchRequestBase_Prd Base_Prd
        {
            get
            {
                return this.base_PrdField;
            }
            set
            {
                this.base_PrdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pax", Namespace = "AtComRes/Common")]
        public Pax[] Pax
        {
            get
            {
                return this.paxField;
            }
            set
            {
                this.paxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public Ref Ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefSpecified
        {
            get
            {
                return this.refFieldSpecified;
            }
            set
            {
                this.refFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AtComRes/FlightExtraSearchRequest")]
    public partial class FlightExtraSearchRequestBase_Prd
    {

        private Routing[] route_ListField;

        private Prom promField;

        private string acc_CdField;

        private string packageNoField;

        private Accom[] accomField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "AtComRes/Common")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Routing", IsNullable = false)]
        public Routing[] Route_List
        {
            get
            {
                return this.route_ListField;
            }
            set
            {
                this.route_ListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public Prom Prom
        {
            get
            {
                return this.promField;
            }
            set
            {
                this.promField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string Acc_Cd
        {
            get
            {
                return this.acc_CdField;
            }
            set
            {
                this.acc_CdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "AtComRes/Common")]
        public string PackageNo
        {
            get
            {
                return this.packageNoField;
            }
            set
            {
                this.packageNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accom", Namespace = "AtComRes/Common")]
        public Accom[] Accom
        {
            get
            {
                return this.accomField;
            }
            set
            {
                this.accomField = value;
            }
        }
    }
}